/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

package software.amazon.smithy.rust.codegen.client.smithy.customizations

import org.junit.jupiter.api.Test
import software.amazon.smithy.model.node.ObjectNode
import software.amazon.smithy.rust.codegen.client.testutil.clientIntegrationTest
import software.amazon.smithy.rust.codegen.core.testutil.ClientAdditionalSettings
import software.amazon.smithy.rust.codegen.core.testutil.IntegrationTestParams
import software.amazon.smithy.rust.codegen.core.testutil.asSmithyModel
import java.nio.file.Path

/**
 * Tests the `disableSchemaSerde` codegen setting, which lets a single service opt out of
 * schema-based serde even when its protocol is enabled in [SchemaSerdeAllowlist].
 *
 * The model lives in the dedicated schema-serde test namespace, so it is on the allowlist
 * independently of production rollout state. That is what makes the opt-out case meaningful:
 * the setting has to turn schema serde *off* for a service that would otherwise use it. (The
 * previous `com.example` namespace was never allowlisted, so the opt-out case passed trivially
 * and the "enabled" case was skipped.)
 */
class SchemaSerdeSettingTest {
    private val model =
        """
        namespace smithy.rust.codegen.test.schemaheaders
        use aws.protocols#awsJson1_0

        @awsJson1_0
        service TestService {
            operations: [TestOp],
            version: "1"
        }

        @optionalAuth
        operation TestOp {
            input: TestInput,
            output: TestOutput,
        }
        structure TestInput { foo: String }
        structure TestOutput { bar: String }
        """.asSmithyModel()

    /** Concatenation of every generated `.rs` file, for coarse presence/absence assertions. */
    private fun generatedSources(testDir: Path): String =
        testDir.resolve("src").toFile().walkTopDown()
            .filter { it.isFile && it.extension == "rs" }
            .joinToString("\n") { it.readText() }

    private fun generate(
        disableSchemaSerde: Boolean?,
        expectSchemaSerde: Boolean,
    ): Path =
        clientIntegrationTest(
            model,
            params =
                IntegrationTestParams(
                    cargoCommand = "cargo check",
                    // `CoreAdditionalSettings.toObjectNode` reduces over its settings, so an empty
                    // builder is not a valid "leave everything at its default" value.
                    additionalSettings =
                        disableSchemaSerde?.let {
                            ClientAdditionalSettings.builder()
                                .disableSchemaSerde(it)
                                .build()
                                .toObjectNode()
                        } ?: ObjectNode.builder().build(),
                ),
        ) { context, _ ->
            check(SchemaSerdeAllowlist.usesSchemaSerdeExclusively(context) == expectSchemaSerde) {
                "expected usesSchemaSerdeExclusively == $expectSchemaSerde for this fixture"
            }
        }

    @Test
    fun `schema serde is generated by default for an allowlisted service`() {
        val sources = generatedSources(generate(disableSchemaSerde = null, expectSchemaSerde = true))
        assert(sources.contains("pub const SCHEMA:")) {
            "Expected generated shapes to carry a `SCHEMA` constant when schema serde is enabled."
        }
        assert(sources.contains("pub fn protocol(")) {
            "Expected the service config to expose a `protocol` accessor when schema serde is enabled."
        }
    }

    @Test
    fun `disableSchemaSerde falls back to the legacy protocol_serde path`() {
        val testDir = generate(disableSchemaSerde = true, expectSchemaSerde = false)
        val sources = generatedSources(testDir)
        assert(!sources.contains("pub const SCHEMA:")) {
            "Expected no `SCHEMA` constants when disableSchemaSerde is true."
        }
        assert(!sources.contains("pub fn protocol(")) {
            "Expected no `protocol` config accessor when disableSchemaSerde is true."
        }
        assert(testDir.resolve("src/protocol_serde.rs").toFile().exists()) {
            "Expected the legacy `protocol_serde` module to be generated when disableSchemaSerde is true."
        }
    }
}
