/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

package software.amazon.smithy.rust.codegen.client.smithy.customizations

import org.junit.jupiter.api.Assumptions.assumeTrue
import org.junit.jupiter.api.Test
import software.amazon.smithy.aws.traits.protocols.AwsJson1_0Trait
import software.amazon.smithy.model.node.ObjectNode
import software.amazon.smithy.rust.codegen.client.testutil.clientIntegrationTest
import software.amazon.smithy.rust.codegen.core.testutil.ClientAdditionalSettings
import software.amazon.smithy.rust.codegen.core.testutil.IntegrationTestParams
import software.amazon.smithy.rust.codegen.core.testutil.asSmithyModel
import java.nio.file.Path

/**
 * Tests the `disableSchemaSerde` codegen setting, which lets a single service opt out of
 * schema-based serde even when its protocol is enabled in [SchemaSerdeAllowlist].
 *
 * The "enabled" case only makes sense while awsJson1_0 is on the allowlist, so it is skipped
 * otherwise rather than hard-coded — same approach as the other schema-serde decorator tests.
 */
class SchemaSerdeSettingTest {
    private val model =
        """
        namespace com.example
        use aws.protocols#awsJson1_0

        @awsJson1_0
        service TestService {
            operations: [TestOp],
            version: "1"
        }

        @optionalAuth
        operation TestOp {
            input: TestInput,
            output: TestOutput,
        }
        structure TestInput { foo: String }
        structure TestOutput { bar: String }
        """.asSmithyModel()

    /** Concatenation of every generated `.rs` file, for coarse presence/absence assertions. */
    private fun generatedSources(testDir: Path): String =
        testDir.resolve("src").toFile().walkTopDown()
            .filter { it.isFile && it.extension == "rs" }
            .joinToString("\n") { it.readText() }

    private fun generate(disableSchemaSerde: Boolean?): Path =
        clientIntegrationTest(
            model,
            params =
                IntegrationTestParams(
                    cargoCommand = "cargo check",
                    // `CoreAdditionalSettings.toObjectNode` reduces over its settings, so an empty
                    // builder is not a valid "leave everything at its default" value.
                    additionalSettings =
                        disableSchemaSerde?.let {
                            ClientAdditionalSettings.builder()
                                .disableSchemaSerde(it)
                                .build()
                                .toObjectNode()
                        } ?: ObjectNode.builder().build(),
                ),
        ) { _, _ -> }

    @Test
    fun `schema serde is generated by default for an allowlisted protocol`() {
        assumeTrue(
            SchemaSerdeAllowlist.isProtocolEnabled(AwsJson1_0Trait.ID),
            "awsJson1_0 is not on SchemaSerdeAllowlist, so there is nothing to opt out of",
        )
        val sources = generatedSources(generate(disableSchemaSerde = null))
        assert(sources.contains("pub const SCHEMA:")) {
            "Expected generated shapes to carry a `SCHEMA` constant when schema serde is enabled."
        }
        assert(sources.contains("pub fn protocol(")) {
            "Expected the service config to expose a `protocol` accessor when schema serde is enabled."
        }
    }

    @Test
    fun `disableSchemaSerde falls back to the legacy protocol_serde path`() {
        val testDir = generate(disableSchemaSerde = true)
        val sources = generatedSources(testDir)
        assert(!sources.contains("pub const SCHEMA:")) {
            "Expected no `SCHEMA` constants when disableSchemaSerde is true."
        }
        assert(!sources.contains("pub fn protocol(")) {
            "Expected no `protocol` config accessor when disableSchemaSerde is true."
        }
        assert(testDir.resolve("src/protocol_serde.rs").toFile().exists()) {
            "Expected the legacy `protocol_serde` module to be generated when disableSchemaSerde is true."
        }
    }
}
