// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
/* EventStreamUnmarshallerGenerator.kt:107 */
#[derive(Debug)]
pub struct AttemptCapturingPokemonEventUnmarshaller {
    // `protocol` is used by event variants whose payloads go through the codec.
    // When no such variant exists (e.g., all events are header-only or use primitive
    // `@eventPayload`), the field is unused but still kept for API uniformity across
    // operations.
    #[allow(dead_code)]
    protocol: ::aws_smithy_http_server::schema::SharedServerProtocol,
}

impl AttemptCapturingPokemonEventUnmarshaller {
    pub fn new(protocol: ::aws_smithy_http_server::schema::SharedServerProtocol) -> Self {
        AttemptCapturingPokemonEventUnmarshaller { protocol }
    }
}
/* EventStreamUnmarshallerGenerator.kt:143 */
impl ::aws_smithy_eventstream::frame::UnmarshallMessage
    for AttemptCapturingPokemonEventUnmarshaller
{
    /* EventStreamUnmarshallerGenerator.kt:147 */
    type Output = crate::model::AttemptCapturingPokemonEvent;
    /* EventStreamUnmarshallerGenerator.kt:148 */
    type Error = crate::error::AttemptCapturingPokemonEventError;
    /* EventStreamUnmarshallerGenerator.kt:150 */
    fn unmarshall(
        &self,
        message: &::aws_smithy_types::event_stream::Message,
    ) -> std::result::Result<
        ::aws_smithy_eventstream::frame::UnmarshalledMessage<Self::Output, Self::Error>,
        ::aws_smithy_eventstream::error::Error,
    > {
        /* EventStreamUnmarshallerGenerator.kt:160 */
        let _ = self
            .protocol
            .event_stream()
            .ok_or_else(|| {
                ::aws_smithy_eventstream::error::Error::unmarshalling(
                    "protocol does not support event streams".to_owned(),
                )
            })?
            .event_stream_media_type();
        /* EventStreamUnmarshallerGenerator.kt:162 */
        let response_headers = ::aws_smithy_eventstream::smithy::parse_response_headers(message)?;
        /* EventStreamUnmarshallerGenerator.kt:163 */
        match response_headers.message_type.as_str() {
            /* EventStreamUnmarshallerGenerator.kt:164 */
            "event" => {
                /* EventStreamUnmarshallerGenerator.kt:189 */
                match response_headers.smithy_type.as_str() {
                    /* EventStreamUnmarshallerGenerator.kt:192 */
                    "event" => {
                        /* EventStreamUnmarshallerGenerator.kt:270 */
                        let mut builder = crate::model::capturing_event::Builder::default();
                        /* EventStreamUnmarshallerGenerator.kt:368 */
                        builder = builder.payload(
                            /* EventStreamUnmarshallerGenerator.kt:369 */Some(
                                /* EventStreamUnmarshallerGenerator.kt:417 */{
                                                let capability = self.protocol.event_stream()
                                                    .ok_or_else(|| ::aws_smithy_eventstream::error::Error::unmarshalling("protocol does not support event streams"))?;
                                                let mut deser = capability.payload_codec().create_deserializer(&message.payload()[..]);
                                                let parsed = crate::model::CapturingPayload::deserialize_schema(&mut *deser)
                                                    .map_err(|err| ::aws_smithy_eventstream::error::Error::unmarshalling(format!("failed to unmarshall event payload: {err}")))?;
                                                parsed
                                            }
                            /* EventStreamUnmarshallerGenerator.kt:369 */)
                        /* EventStreamUnmarshallerGenerator.kt:368 */);
                        /* EventStreamUnmarshallerGenerator.kt:333 */
                        Ok(::aws_smithy_eventstream::frame::UnmarshalledMessage::Event(
                            crate::model::AttemptCapturingPokemonEvent::Event(builder.build()),
                        ))
                        /* EventStreamUnmarshallerGenerator.kt:192 */
                    }
                    /* EventStreamUnmarshallerGenerator.kt:196 */
                    _unknown_variant => {
                        /* EventStreamUnmarshallerGenerator.kt:206 */
                        return Err(::aws_smithy_eventstream::error::Error::unmarshalling(
                            format!("unrecognized :event-type: {_unknown_variant}"),
                        ));
                        /* EventStreamUnmarshallerGenerator.kt:196 */
                    } /* EventStreamUnmarshallerGenerator.kt:189 */
                }
                /* EventStreamUnmarshallerGenerator.kt:164 */
            }
            /* EventStreamUnmarshallerGenerator.kt:167 */
            "exception" => {
                /* EventStreamUnmarshallerGenerator.kt:493 */
                if response_headers.smithy_type.as_str() ==
                /* EventStreamUnmarshallerGenerator.kt:495 */"masterball_unsuccessful"
                {
                    /* EventStreamUnmarshallerGenerator.kt:590 */
                    let err =
                        /* EventStreamUnmarshallerGenerator.kt:591 */{
                                        let capability = self.protocol.event_stream()
                                            .ok_or_else(|| ::aws_smithy_eventstream::error::Error::unmarshalling("protocol does not support event streams"))?;
                                        let mut deser = capability.payload_codec().create_deserializer(&message.payload()[..]);
                                        let parsed = crate::error::MasterBallUnsuccessful::deserialize_schema(&mut *deser)
                                            .map_err(|err| ::aws_smithy_eventstream::error::Error::unmarshalling(format!("failed to unmarshall exception: {err}")))?;
                                        parsed
                                    }
                    /* EventStreamUnmarshallerGenerator.kt:590 */;
                    /* EventStreamUnmarshallerGenerator.kt:593 */
                    return Ok(::aws_smithy_eventstream::frame::UnmarshalledMessage::Error(
                        crate::error::AttemptCapturingPokemonEventError::MasterBallUnsuccessful(
                            err,
                        ),
                    ));
                    /* EventStreamUnmarshallerGenerator.kt:495 */
                }
                /* EventStreamUnmarshallerGenerator.kt:649 */
                return Err(aws_smithy_eventstream::error::Error::unmarshalling(
                    format!(
                        "unrecognized exception: {}",
                        response_headers.smithy_type.as_str()
                    ),
                ));
                /* EventStreamUnmarshallerGenerator.kt:167 */
            }
            /* EventStreamUnmarshallerGenerator.kt:170 */
            value => {
                /* EventStreamUnmarshallerGenerator.kt:171 */
                return Err(::aws_smithy_eventstream::error::Error::unmarshalling(
                    format!("unrecognized :message-type: {value}"),
                ));
                /* EventStreamUnmarshallerGenerator.kt:170 */
            } /* EventStreamUnmarshallerGenerator.kt:163 */
        }
        /* EventStreamUnmarshallerGenerator.kt:150 */
    }
    /* EventStreamUnmarshallerGenerator.kt:143 */
}

/* EventStreamMarshallerGenerator.kt:165 */
#[non_exhaustive]
#[derive(Debug)]
pub struct CapturePokemonEventsMarshaller {
    // `protocol` is used by event variants whose payloads go through the codec.
    // When no such variant exists (e.g., all events are header-only or use primitive
    // `@eventPayload`), the field is unused but still kept for API uniformity across
    // operations.
    #[allow(dead_code)]
    protocol: ::aws_smithy_http_server::schema::SharedServerProtocol,
}

impl CapturePokemonEventsMarshaller {
    pub fn new(protocol: ::aws_smithy_http_server::schema::SharedServerProtocol) -> Self {
        Self { protocol }
    }
}
/* EventStreamMarshallerGenerator.kt:202 */
impl ::aws_smithy_eventstream::frame::MarshallMessage for CapturePokemonEventsMarshaller {
    /* EventStreamMarshallerGenerator.kt:206 */
    type Input = crate::model::CapturePokemonEvents;
    /* EventStreamMarshallerGenerator.kt:208 */
    fn marshall(
        &self,
        input: Self::Input,
    ) -> std::result::Result<
        ::aws_smithy_types::event_stream::Message,
        ::aws_smithy_eventstream::error::Error,
    > {
        /* EventStreamMarshallerGenerator.kt:213 */
        let _structured_media_type = self
            .protocol
            .event_stream()
            .ok_or_else(|| {
                ::aws_smithy_eventstream::error::Error::marshalling(
                    "protocol does not support event streams".to_owned(),
                )
            })?
            .event_stream_media_type();
        /* EventStreamMarshallerGenerator.kt:215 */
        let mut headers = Vec::new();
        /* EventStreamMarshallerGenerator.kt:476 */
        headers.push(::aws_smithy_types::event_stream::Header::new(
            ":message-type",
            ::aws_smithy_types::event_stream::HeaderValue::String("event".into()),
        ));
        /* EventStreamMarshallerGenerator.kt:217 */
        let payload = match input {
            /* EventStreamMarshallerGenerator.kt:228 */Self::Input::Event(inner) =>  {
                /* EventStreamMarshallerGenerator.kt:476 */headers.push(::aws_smithy_types::event_stream::Header::new(":event-type", ::aws_smithy_types::event_stream::HeaderValue::String("event".into())));
                /* EventStreamMarshallerGenerator.kt:459 */if let Some(value) = inner.name {
                    /* EventStreamMarshallerGenerator.kt:301 */headers.push(
                        /* EventStreamMarshallerGenerator.kt:302 */::aws_smithy_types::event_stream::Header::new("name", ::aws_smithy_types::event_stream::HeaderValue::String(value.into()))
                    /* EventStreamMarshallerGenerator.kt:301 */);
                /* EventStreamMarshallerGenerator.kt:459 */}
                /* EventStreamMarshallerGenerator.kt:459 */if let Some(value) = inner.captured {
                    /* EventStreamMarshallerGenerator.kt:301 */headers.push(
                        /* EventStreamMarshallerGenerator.kt:302 */::aws_smithy_types::event_stream::Header::new("captured", ::aws_smithy_types::event_stream::HeaderValue::Bool(value))
                    /* EventStreamMarshallerGenerator.kt:301 */);
                /* EventStreamMarshallerGenerator.kt:459 */}
                /* EventStreamMarshallerGenerator.kt:459 */if let Some(value) = inner.shiny {
                    /* EventStreamMarshallerGenerator.kt:301 */headers.push(
                        /* EventStreamMarshallerGenerator.kt:302 */::aws_smithy_types::event_stream::Header::new("shiny", ::aws_smithy_types::event_stream::HeaderValue::Bool(value))
                    /* EventStreamMarshallerGenerator.kt:301 */);
                /* EventStreamMarshallerGenerator.kt:459 */}
                /* EventStreamMarshallerGenerator.kt:476 */headers.push(::aws_smithy_types::event_stream::Header::new(":content-type", ::aws_smithy_types::event_stream::HeaderValue::String("application/octet-stream".into())));
                /* EventStreamMarshallerGenerator.kt:459 */if let Some(inner_payload) = inner.pokedex_update {
                    /* EventStreamMarshallerGenerator.kt:349 */::aws_smithy_types::Blob::from(inner_payload).into_bytes()
                /* EventStreamMarshallerGenerator.kt:459 */}
                /* EventStreamMarshallerGenerator.kt:463 */ else  {
                    /* EventStreamMarshallerGenerator.kt:354 */::bytes::Bytes::new()
                /* EventStreamMarshallerGenerator.kt:463 */}
            /* EventStreamMarshallerGenerator.kt:228 */}
        /* EventStreamMarshallerGenerator.kt:217 */}
        /* EventStreamMarshallerGenerator.kt:245 */;
        Ok(::aws_smithy_types::event_stream::Message::new_from_parts(
            headers, payload,
        ))
        /* EventStreamMarshallerGenerator.kt:208 */
    }
    /* EventStreamMarshallerGenerator.kt:202 */
}

/* EventStreamErrorMarshallerGenerator.kt:89 */
#[non_exhaustive]
#[derive(Debug)]
pub struct CapturePokemonEventsErrorMarshaller {
    // `protocol` is used by error variants whose payloads go through the codec.
    // When no such variant exists (e.g., all errors are header-only or empty),
    // the field is unused but still kept for API uniformity across operations.
    #[allow(dead_code)]
    protocol: ::aws_smithy_http_server::schema::SharedServerProtocol,
}

impl CapturePokemonEventsErrorMarshaller {
    pub fn new(protocol: ::aws_smithy_http_server::schema::SharedServerProtocol) -> Self {
        Self { protocol }
    }
}
/* EventStreamErrorMarshallerGenerator.kt:125 */
impl ::aws_smithy_eventstream::frame::MarshallMessage for CapturePokemonEventsErrorMarshaller {
    /* EventStreamErrorMarshallerGenerator.kt:129 */
    type Input = crate::error::CapturePokemonEventsError;
    /* EventStreamErrorMarshallerGenerator.kt:131 */
    fn marshall(
        &self,
        _input: Self::Input,
    ) -> std::result::Result<
        ::aws_smithy_types::event_stream::Message,
        ::aws_smithy_eventstream::error::Error,
    > {
        /* EventStreamErrorMarshallerGenerator.kt:136 */
        let _structured_media_type = self
            .protocol
            .event_stream()
            .ok_or_else(|| {
                ::aws_smithy_eventstream::error::Error::marshalling(
                    "protocol does not support event streams".to_owned(),
                )
            })?
            .event_stream_media_type();
        /* EventStreamErrorMarshallerGenerator.kt:138 */
        let mut headers = Vec::new();
        /* EventStreamMarshallerGenerator.kt:476 */
        headers.push(::aws_smithy_types::event_stream::Header::new(
            ":message-type",
            ::aws_smithy_types::event_stream::HeaderValue::String("exception".into()),
        ));
        /* EventStreamErrorMarshallerGenerator.kt:144 */
        let payload = match _input {
            /* EventStreamErrorMarshallerGenerator.kt:149 */crate::error::CapturePokemonEventsError::InvalidPokeballError(inner) =>  {
                /* EventStreamMarshallerGenerator.kt:476 */headers.push(::aws_smithy_types::event_stream::Header::new(":exception-type", ::aws_smithy_types::event_stream::HeaderValue::String("invalid_pokeball".into())));
                /* EventStreamMarshallerGenerator.kt:358 */headers.push(::aws_smithy_types::event_stream::Header::new(":content-type", ::aws_smithy_types::event_stream::HeaderValue::String(_structured_media_type.to_string().into())));
                /* EventStreamMarshallerGenerator.kt:364 */{
                                let capability = self.protocol.event_stream()
                                    .ok_or_else(|| ::aws_smithy_eventstream::error::Error::marshalling("protocol does not support event streams".to_owned()))?;
                                let mut ser = capability.payload_codec().create_serializer();
                                ::aws_smithy_schema::serde::ShapeSerializer::write_struct(&mut *ser, crate::error::InvalidPokeballError::SCHEMA, &inner)
                                    .map_err(|err| ::aws_smithy_eventstream::error::Error::marshalling(format!("{err}")))?;
                                ::bytes::Bytes::from(::aws_smithy_schema::codec::PayloadSerializer::finish_boxed(ser))
                            }
            /* EventStreamErrorMarshallerGenerator.kt:149 */}
            /* EventStreamErrorMarshallerGenerator.kt:149 */crate::error::CapturePokemonEventsError::ThrottlingError(inner) =>  {
                /* EventStreamMarshallerGenerator.kt:476 */headers.push(::aws_smithy_types::event_stream::Header::new(":exception-type", ::aws_smithy_types::event_stream::HeaderValue::String("throttlingError".into())));
                /* EventStreamMarshallerGenerator.kt:358 */headers.push(::aws_smithy_types::event_stream::Header::new(":content-type", ::aws_smithy_types::event_stream::HeaderValue::String(_structured_media_type.to_string().into())));
                /* EventStreamMarshallerGenerator.kt:364 */{
                                let capability = self.protocol.event_stream()
                                    .ok_or_else(|| ::aws_smithy_eventstream::error::Error::marshalling("protocol does not support event streams".to_owned()))?;
                                let mut ser = capability.payload_codec().create_serializer();
                                ::aws_smithy_schema::serde::ShapeSerializer::write_struct(&mut *ser, crate::error::ThrottlingError::SCHEMA, &inner)
                                    .map_err(|err| ::aws_smithy_eventstream::error::Error::marshalling(format!("{err}")))?;
                                ::bytes::Bytes::from(::aws_smithy_schema::codec::PayloadSerializer::finish_boxed(ser))
                            }
            /* EventStreamErrorMarshallerGenerator.kt:149 */}
        /* EventStreamErrorMarshallerGenerator.kt:144 */}
        /* EventStreamErrorMarshallerGenerator.kt:167 */;
        Ok(::aws_smithy_types::event_stream::Message::new_from_parts(
            headers, payload,
        ))
        /* EventStreamErrorMarshallerGenerator.kt:131 */
    }
    /* EventStreamErrorMarshallerGenerator.kt:125 */
}
