[package]
name = "pokemon-service-lambda"
version = "0.1.0"
edition = "2021"
publish = false
authors = ["Smithy-rs Server Team <smithy-rs-server@amazon.com>"]
description = "A smithy Rust service to retrieve information about Pokémon via Lambda."

[dependencies]
async-stream = "0.3.4"
clap = { version = "4.1.11", features = ["derive"] }
hyper = {version = "0.14.26", features = ["server"] }
tokio = "1.26.0"
tracing = "0.1"

# `aws-smithy-legacy-http-server` is only guaranteed to be compatible with this
# version of `lambda_http`, or semver-compatible versions of this version.
# Depending on other versions of `lambda_http` may not work.
lambda_http = "0.8.0"

# Local paths
pokemon-service-server-sdk = { path = "../pokemon-service-server-sdk/", package = "pokemon-service-server-sdk-http0x", features = ["aws-lambda"] }
pokemon-service-common = { path = "../pokemon-service-common/" }
