use std::marker::PhantomData;

use http::Request;
use http::Response;
use metrique::AppendAndCloseOnDrop;
use metrique::OnParentDrop;
use metrique::RootEntry;
use metrique::Slot;
use metrique::writer::EntrySink;
use metrique_core::CloseEntry;

use crate::default::DefaultMetricsEntry;
use crate::default::DefaultRequestMetrics;
use crate::default::DefaultRequestMetricsConfig;
use crate::default::DefaultRequestMetricsExtension;
use crate::default::DefaultResponseMetrics;
use crate::default::DefaultResponseMetricsConfig;
use crate::default::DefaultResponseMetricsExtension;
use crate::layer::DefaultMetrics;
use crate::layer::MetricsLayer;
use crate::layer::ReqBody;
use crate::layer::ResBody;

pub struct NeedsInitialization;
pub struct Ready;

pub struct MetricsLayerBuilder<State, E, S, I, Rq, Rs>
where
    E: CloseEntry + Send + Sync + 'static,
    S: EntrySink<RootEntry<E::Closed>> + Send + Sync + 'static,
    I: Fn() -> AppendAndCloseOnDrop<E, S> + Clone,
    Rq: Fn(&mut Request<ReqBody>, &mut AppendAndCloseOnDrop<E, S>) + Clone,
    Rs: Fn(&mut Response<ResBody>, &mut AppendAndCloseOnDrop<E, S>) + Clone,
{
    pub(crate) init_metrics: Option<I>,
    pub(crate) set_request_metrics: Option<Rq>,
    pub(crate) set_response_metrics: Option<Rs>,
    pub(crate) default_request_metrics_config: DefaultRequestMetricsConfig,
    pub(crate) default_response_metrics_config: DefaultResponseMetricsConfig,
    pub(crate) _state: PhantomData<State>,
}

impl<E, S, I, Rq, Rs> MetricsLayerBuilder<NeedsInitialization, E, S, I, Rq, Rs>
where
    E: CloseEntry + Send + Sync + 'static,
    S: EntrySink<RootEntry<E::Closed>> + Send + Sync + 'static,
    I: Fn() -> AppendAndCloseOnDrop<E, S> + Clone + Send + Sync + 'static,
    Rq: Fn(&mut Request<ReqBody>, &mut AppendAndCloseOnDrop<E, S>) + Clone + Send + Sync + 'static,
    Rs: Fn(&mut Response<ResBody>, &mut AppendAndCloseOnDrop<E, S>) + Clone + Send + Sync + 'static,
{
    pub fn init_metrics(mut self, init_metrics: I) -> MetricsLayerBuilder<Ready, E, S, I, Rq, Rs> {
        self.init_metrics = Some(init_metrics);
        MetricsLayerBuilder {
            init_metrics: self.init_metrics,
            set_request_metrics: self.set_request_metrics,
            set_response_metrics: self.set_response_metrics,
            default_request_metrics_config: self.default_request_metrics_config,
            default_response_metrics_config: self.default_response_metrics_config,
            _state: PhantomData,
        }
    }
}

impl<E, S, I, Rq, Rs> MetricsLayerBuilder<Ready, E, S, I, Rq, Rs>
where
    E: CloseEntry + Send + Sync + 'static,
    S: EntrySink<RootEntry<E::Closed>> + Send + Sync + 'static,
    I: Fn() -> AppendAndCloseOnDrop<E, S> + Clone + Send + Sync + 'static,
    Rq: Fn(&mut Request<ReqBody>, &mut AppendAndCloseOnDrop<E, S>) + Clone + Send + Sync + 'static,
    Rs: Fn(&mut Response<ResBody>, &mut AppendAndCloseOnDrop<E, S>) + Clone + Send + Sync + 'static,
{
    pub fn disable_default_request_metrics(mut self) -> Self {
        self.default_request_metrics_config.disable_all = true;
        self
    }

    pub fn disable_default_response_metrics(mut self) -> Self {
        self.default_response_metrics_config.disable_all = true;
        self
    }

    pub fn disable_default_request_id_metric(mut self) -> Self {
        self.default_request_metrics_config.disable_request_id = true;
        self
    }

    pub fn disable_default_operation_name_metric(mut self) -> Self {
        self.default_request_metrics_config.disable_operation_name = true;
        self
    }

    pub fn disable_default_service_name_metric(mut self) -> Self {
        self.default_request_metrics_config.disable_service_name = true;
        self
    }

    pub fn disable_default_service_version_metric(mut self) -> Self {
        self.default_request_metrics_config.disable_service_version = true;
        self
    }

    pub fn disable_default_http_status_code(mut self) -> Self {
        self.default_response_metrics_config
            .disable_http_status_code = true;
        self
    }

    pub fn set_request_metrics(mut self, f: Rq) -> Self {
        self.set_request_metrics = Some(f);
        self
    }

    pub fn set_response_metrics(mut self, f: Rs) -> Self {
        self.set_response_metrics = Some(f);
        self
    }
}

/// This is the impl that will be generated by the proc macro when the metrics struct is annotated with #[smithy_metrics]
impl<S, I, Rq, Rs> MetricsLayerBuilder<Ready, DefaultMetrics, S, I, Rq, Rs>
where
    S: EntrySink<RootEntry<DefaultMetricsEntry>> + Send + Sync + 'static,
    I: Fn() -> AppendAndCloseOnDrop<DefaultMetrics, S> + Clone + Send + Sync + 'static,
    Rq: Fn(&mut Request<ReqBody>, &mut AppendAndCloseOnDrop<DefaultMetrics, S>)
        + Clone
        + Send
        + Sync
        + 'static,
    Rs: Fn(&mut Response<ResBody>, &mut AppendAndCloseOnDrop<DefaultMetrics, S>)
        + Clone
        + Send
        + Sync
        + 'static,
{
    // TODO: make a macro for this
    pub fn build_default(
        self,
    ) -> MetricsLayer<
        DefaultMetrics,
        S,
        I,
        Rq,
        Rs,
        fn(&mut Request<ReqBody>, &mut AppendAndCloseOnDrop<DefaultMetrics, S>),
        fn(&mut Response<ResBody>, &mut AppendAndCloseOnDrop<DefaultMetrics, S>),
    > {
        let default_req_metrics_extension_fn = |req: &mut Request<ReqBody>,
                                                metrics: &mut AppendAndCloseOnDrop<
            DefaultMetrics,
            S,
        >| {
            metrics.request_metrics = Some(Slot::new(DefaultRequestMetrics::default()));
            let default_req_metrics_slotguard = metrics
                    .request_metrics
                    .as_mut()
                    .expect("unreachable: the option is set to some in this scope")
                    .open(OnParentDrop::Discard)
                    .expect("unreachable: the slot was created in this scope and is not opened before this point");

            let ext = DefaultRequestMetricsExtension {
                metrics: default_req_metrics_slotguard,
                config: DefaultRequestMetricsConfig::default(),
            };

            req.extensions_mut().insert(ext);
        };

        let default_res_metrics_extension_fn = |res: &mut Response<ResBody>,
                                                metrics: &mut AppendAndCloseOnDrop<
            DefaultMetrics,
            S,
        >| {
            metrics.response_metrics = Some(Slot::new(DefaultResponseMetrics::default()));
            let default_res_metrics_slotguard = metrics
                    .response_metrics
                    .as_mut()
                    .expect("unreachable: the option is set to some in this scope")
                    .open(OnParentDrop::Discard)
                    .expect("unreachable: the slot was created in this scope and is not opened before this point");

            let ext = DefaultResponseMetricsExtension {
                metrics: default_res_metrics_slotguard,
                config: DefaultResponseMetricsConfig::default(),
            };

            res.extensions_mut().insert(ext);
        };

        MetricsLayer {
            init_metrics: self.init_metrics.expect("init_metrics must be provided"),
            default_req_metrics_extension_fn,
            default_res_metrics_extension_fn,
            set_request_metrics: self.set_request_metrics,
            set_response_metrics: self.set_response_metrics,
        }
    }

    pub fn build(
        self,
    ) -> MetricsLayer<
        DefaultMetrics,
        S,
        I,
        Rq,
        Rs,
        impl Fn(&mut Request<ReqBody>, &mut AppendAndCloseOnDrop<DefaultMetrics, S>)
        + Clone
        + Send
        + Sync
        + 'static,
        impl Fn(&mut Response<ResBody>, &mut AppendAndCloseOnDrop<DefaultMetrics, S>)
        + Clone
        + Send
        + Sync
        + 'static,
    > {
        let default_req_metrics_extension_fn = move |req: &mut Request<ReqBody>,
                                                     metrics: &mut AppendAndCloseOnDrop<
            DefaultMetrics,
            S,
        >| {
            metrics.request_metrics = Some(Slot::new(DefaultRequestMetrics::default()));
            let default_req_metrics_slotguard = metrics
                    .request_metrics
                    .as_mut()
                    .expect("unreachable: the option is set to some in this scope")
                    .open(OnParentDrop::Discard)
                    .expect("unreachable: the slot was created in this scope and is not opened before this point");

            let ext = DefaultRequestMetricsExtension {
                metrics: default_req_metrics_slotguard,
                config: self.default_request_metrics_config.clone(),
            };

            req.extensions_mut().insert(ext);
        };

        let default_res_metrics_extension_fn = move |res: &mut Response<ResBody>,
                                                     metrics: &mut AppendAndCloseOnDrop<
            DefaultMetrics,
            S,
        >| {
            metrics.response_metrics = Some(Slot::new(DefaultResponseMetrics::default()));
            let default_res_metrics_slotguard = metrics
                    .response_metrics
                    .as_mut()
                    .expect("unreachable: the option is set to some in this scope")
                    .open(OnParentDrop::Discard)
                    .expect("unreachable: the slot was created in this scope and is not opened before this point");

            let ext = DefaultResponseMetricsExtension {
                metrics: default_res_metrics_slotguard,
                config: self.default_response_metrics_config.clone(),
            };

            res.extensions_mut().insert(ext);
        };

        MetricsLayer {
            init_metrics: self.init_metrics.expect("init_metrics must be provided"),
            default_req_metrics_extension_fn,
            default_res_metrics_extension_fn,
            set_request_metrics: self.set_request_metrics,
            set_response_metrics: self.set_response_metrics,
        }
    }
}
