use std::marker::PhantomData;

use http::Request;
use http::Response;
use metrique::AppendAndCloseOnDrop;
use metrique::OnParentDrop;
use metrique::RootEntry;
use metrique::Slot;
use metrique::writer::EntrySink;
use metrique_core::CloseEntry;

use crate::default::DefaultMetricsEntry;
use crate::default::DefaultRequestMetrics;
use crate::default::DefaultResponseMetrics;
use crate::layer::DefaultMetrics;
use crate::layer::ReqBody;
use crate::layer::ResBody;
use crate::layer::inner::MetricsLayer as MetricsLayerInner;

pub struct NeedsInitialization;
pub struct Ready;

pub struct MetricsLayerBuilder<State, I, Rq, Rs, E, S>
where
    I: Fn() -> AppendAndCloseOnDrop<E, S> + Clone,
    Rq: Fn(&mut Request<ReqBody>, &mut AppendAndCloseOnDrop<E, S>) + Clone,
    Rs: Fn(&Response<ResBody>, &mut AppendAndCloseOnDrop<E, S>) + Clone,
    E: CloseEntry + Send + Sync + 'static,
    S: EntrySink<RootEntry<E::Closed>> + Send + Sync + 'static,
{
    pub(crate) init_metrics: Option<I>,
    pub(crate) set_request_metrics: Option<Rq>,
    pub(crate) set_response_metrics: Option<Rs>,

    pub(crate) with_default_request_metrics: bool,
    pub(crate) with_default_response_metrics: bool,
    pub(crate) with_request_id_metric: bool,
    pub(crate) with_start_metric: bool,
    pub(crate) with_operation_name_metric: bool,
    pub(crate) with_service_name_metric: bool,
    pub(crate) with_service_version_metric: bool,
    pub(crate) with_http_status_code: bool,

    pub(crate) _state: PhantomData<State>,
}

impl<I, Rq, Rs, E, S> MetricsLayerBuilder<NeedsInitialization, I, Rq, Rs, E, S>
where
    I: Fn() -> AppendAndCloseOnDrop<E, S> + Clone,
    Rq: Fn(&mut Request<ReqBody>, &mut AppendAndCloseOnDrop<E, S>) + Clone,
    Rs: Fn(&Response<ResBody>, &mut AppendAndCloseOnDrop<E, S>) + Clone,
    E: CloseEntry + Send + Sync + 'static,
    S: EntrySink<RootEntry<E::Closed>> + Send + Sync + 'static,
{
    pub fn init_metrics(mut self, init_metrics: I) -> MetricsLayerBuilder<Ready, I, Rq, Rs, E, S> {
        self.init_metrics = Some(init_metrics);
        MetricsLayerBuilder {
            init_metrics: self.init_metrics,
            set_request_metrics: self.set_request_metrics,
            set_response_metrics: self.set_response_metrics,
            with_default_request_metrics: self.with_default_request_metrics,
            with_default_response_metrics: self.with_default_response_metrics,
            with_request_id_metric: self.with_request_id_metric,
            with_start_metric: self.with_start_metric,
            with_operation_name_metric: self.with_operation_name_metric,
            with_service_name_metric: self.with_service_name_metric,
            with_service_version_metric: self.with_service_version_metric,
            with_http_status_code: self.with_http_status_code,
            _state: PhantomData,
        }
    }
}

impl<I, Rq, Rs, E, S> MetricsLayerBuilder<Ready, I, Rq, Rs, E, S>
where
    I: Fn() -> AppendAndCloseOnDrop<E, S> + Clone,
    Rq: Fn(&mut Request<ReqBody>, &mut AppendAndCloseOnDrop<E, S>) + Clone,
    Rs: Fn(&Response<ResBody>, &mut AppendAndCloseOnDrop<E, S>) + Clone,
    E: CloseEntry + Send + Sync + 'static,
    S: EntrySink<RootEntry<E::Closed>> + Send + Sync + 'static,
{
    pub fn without_default_request_metrics(mut self) -> Self {
        self.with_default_request_metrics = false;
        self
    }

    pub fn without_default_response_metrics(mut self) -> Self {
        self.with_default_response_metrics = false;
        self
    }

    pub fn without_request_id_metric(mut self) -> Self {
        self.with_request_id_metric = false;
        self
    }

    pub fn without_start_metric(mut self) -> Self {
        self.with_start_metric = false;
        self
    }

    pub fn without_operation_name_metric(mut self) -> Self {
        self.with_operation_name_metric = false;
        self
    }

    pub fn without_service_name_metric(mut self) -> Self {
        self.with_service_name_metric = false;
        self
    }

    pub fn without_service_version_metric(mut self) -> Self {
        self.with_service_version_metric = false;
        self
    }

    pub fn without_http_status_code(mut self) -> Self {
        self.with_http_status_code = false;
        self
    }

    pub fn set_request_metrics(mut self, f: Rq) -> Self {
        self.set_request_metrics = Some(f);
        self
    }

    pub fn set_response_metrics(mut self, f: Rs) -> Self {
        self.set_response_metrics = Some(f);
        self
    }
}

/// This is the impl that will be generated by the proc macro when the metrics struct is annotated with #[smithy_metrics]
impl<I, Rq, Rs, S> MetricsLayerBuilder<Ready, I, Rq, Rs, DefaultMetrics, S>
where
    I: Fn() -> AppendAndCloseOnDrop<DefaultMetrics, S> + Clone,
    Rq: Fn(&mut Request<ReqBody>, &mut AppendAndCloseOnDrop<DefaultMetrics, S>) + Clone,
    Rs: Fn(&Response<ResBody>, &mut AppendAndCloseOnDrop<DefaultMetrics, S>) + Clone,
    S: EntrySink<RootEntry<DefaultMetricsEntry>> + Send + Sync + 'static,
{
    pub fn build(self) -> MetricsLayerInner<I, Rq, Rs, DefaultMetrics, S> {
        let set_default_request_metrics = |req: &mut Request<ReqBody>,
                                           metrics: &mut AppendAndCloseOnDrop<
            DefaultMetrics,
            S,
        >| {
            metrics.request_metrics = Some(Slot::new(DefaultRequestMetrics::default()));

            let mut default_req_metrics_slotguard = metrics
                    .request_metrics
                    .as_mut()
                    .expect("unreachable: the option is set to some in this scope")
                    .open(OnParentDrop::Discard)
                    .expect("unreachable: the slot was created in this scope and is not opened before this point");

            default_req_metrics_slotguard.request_id = Some("test_request_id".to_string());

            req.extensions_mut().insert(default_req_metrics_slotguard);
        };

        let set_default_response_metrics =
            |res: &Response<ResBody>, metrics: &mut AppendAndCloseOnDrop<DefaultMetrics, S>| {
                let default_res_metrics = DefaultResponseMetrics {
                    http_status_code: Some(res.status().as_u16()),
                };

                metrics.response_metrics = Some(default_res_metrics);
            };

        MetricsLayerInner {
            init_metrics: self.init_metrics.expect("init_metrics must be provided"),
            set_default_request_metrics: self
                .with_default_request_metrics
                .then_some(set_default_request_metrics),
            set_default_response_metrics: self
                .with_default_response_metrics
                .then_some(set_default_response_metrics),
            set_request_metrics: self.set_request_metrics,
            set_response_metrics: self.set_response_metrics,
        }
    }
}
