use std::marker::PhantomData;

use http::Request;
use http::Response;
use metrique::AppendAndCloseOnDrop;
use metrique::OnParentDrop;
use metrique::RootEntry;
use metrique::Slot;
use metrique::writer::EntrySink;
use metrique_core::CloseEntry;

use crate::default::DefaultMetricsEntry;
use crate::default::DefaultRequestMetrics;
use crate::default::DefaultResponseMetrics;
use crate::layer::DefaultMetrics;
use crate::layer::MetricsLayer;
use crate::layer::ReqBody;
use crate::layer::ResBody;

pub struct NeedsInitialization;
pub struct Ready;

pub struct MetricsLayerBuilder<State, E, S, I, Rq, Rs>
where
    E: CloseEntry + Send + Sync + 'static,
    S: EntrySink<RootEntry<E::Closed>> + Send + Sync + 'static,
    I: Fn() -> AppendAndCloseOnDrop<E, S> + Clone,
    Rq: Fn(&mut Request<ReqBody>, &mut AppendAndCloseOnDrop<E, S>) + Clone,
    Rs: Fn(&mut Response<ResBody>, &mut AppendAndCloseOnDrop<E, S>) + Clone,
{
    pub(crate) init_metrics: Option<I>,
    pub(crate) set_request_metrics: Option<Rq>,
    pub(crate) set_response_metrics: Option<Rs>,

    pub(crate) with_default_request_metrics: bool,
    pub(crate) with_default_response_metrics: bool,

    pub(crate) _state: PhantomData<State>,
}

impl<E, S, I, Rq, Rs> MetricsLayerBuilder<NeedsInitialization, E, S, I, Rq, Rs>
where
    E: CloseEntry + Send + Sync + 'static,
    S: EntrySink<RootEntry<E::Closed>> + Send + Sync + 'static,
    I: Fn() -> AppendAndCloseOnDrop<E, S> + Clone + Send + Sync + 'static,
    Rq: Fn(&mut Request<ReqBody>, &mut AppendAndCloseOnDrop<E, S>) + Clone + Send + Sync + 'static,
    Rs: Fn(&mut Response<ResBody>, &mut AppendAndCloseOnDrop<E, S>) + Clone + Send + Sync + 'static,
{
    pub fn init_metrics(mut self, init_metrics: I) -> MetricsLayerBuilder<Ready, E, S, I, Rq, Rs> {
        self.init_metrics = Some(init_metrics);
        MetricsLayerBuilder {
            init_metrics: self.init_metrics,
            set_request_metrics: self.set_request_metrics,
            set_response_metrics: self.set_response_metrics,
            with_default_request_metrics: self.with_default_request_metrics,
            with_default_response_metrics: self.with_default_response_metrics,
            _state: PhantomData,
        }
    }
}

impl<E, S, I, Rq, Rs> MetricsLayerBuilder<Ready, E, S, I, Rq, Rs>
where
    E: CloseEntry + Send + Sync + 'static,
    S: EntrySink<RootEntry<E::Closed>> + Send + Sync + 'static,
    I: Fn() -> AppendAndCloseOnDrop<E, S> + Clone + Send + Sync + 'static,
    Rq: Fn(&mut Request<ReqBody>, &mut AppendAndCloseOnDrop<E, S>) + Clone + Send + Sync + 'static,
    Rs: Fn(&mut Response<ResBody>, &mut AppendAndCloseOnDrop<E, S>) + Clone + Send + Sync + 'static,
{
    pub fn without_default_request_metrics(mut self) -> Self {
        self.with_default_request_metrics = false;
        self
    }

    pub fn without_default_response_metrics(mut self) -> Self {
        self.with_default_response_metrics = false;
        self
    }

    pub fn set_request_metrics(mut self, f: Rq) -> Self {
        self.set_request_metrics = Some(f);
        self
    }

    pub fn set_response_metrics(mut self, f: Rs) -> Self {
        self.set_response_metrics = Some(f);
        self
    }
}

/// This is the impl that will be generated by the proc macro when the metrics struct is annotated with #[smithy_metrics]
impl<S, I, Rq, Rs> MetricsLayerBuilder<Ready, DefaultMetrics, S, I, Rq, Rs>
where
    S: EntrySink<RootEntry<DefaultMetricsEntry>> + Send + Sync + 'static,
    I: Fn() -> AppendAndCloseOnDrop<DefaultMetrics, S> + Clone + Send + Sync + 'static,
    Rq: Fn(&mut Request<ReqBody>, &mut AppendAndCloseOnDrop<DefaultMetrics, S>)
        + Clone
        + Send
        + Sync
        + 'static,
    Rs: Fn(&mut Response<ResBody>, &mut AppendAndCloseOnDrop<DefaultMetrics, S>)
        + Clone
        + Send
        + Sync
        + 'static,
{
    pub fn build(self) -> MetricsLayer<DefaultMetrics, S, I, Rq, Rs> {
        let default_req_metrics_extension_fn = |req: &mut Request<ReqBody>,
                                                metrics: &mut AppendAndCloseOnDrop<
            DefaultMetrics,
            S,
        >| {
            metrics.request_metrics = Some(Slot::new(DefaultRequestMetrics::default()));
            let default_req_metrics_slotguard = metrics
                    .request_metrics
                    .as_mut()
                    .expect("unreachable: the option is set to some in this scope")
                    .open(OnParentDrop::Discard)
                    .expect("unreachable: the slot was created in this scope and is not opened before this point");

            req.extensions_mut().insert(default_req_metrics_slotguard);
        };

        let default_res_metrics_extension_fn = |res: &mut Response<ResBody>,
                                                metrics: &mut AppendAndCloseOnDrop<
            DefaultMetrics,
            S,
        >| {
            metrics.response_metrics = Some(Slot::new(DefaultResponseMetrics::default()));
            let default_res_metrics_slotguard = metrics
                    .response_metrics
                    .as_mut()
                    .expect("unreachable: the option is set to some in this scope")
                    .open(OnParentDrop::Discard)
                    .expect("unreachable: the slot was created in this scope and is not opened before this point");

            res.extensions_mut().insert(default_res_metrics_slotguard);
        };

        MetricsLayer {
            init_metrics: self.init_metrics.expect("init_metrics must be provided"),
            default_req_metrics_extension_fn,
            default_res_metrics_extension_fn,
            set_request_metrics: self.set_request_metrics,
            set_response_metrics: self.set_response_metrics,
        }
    }
}
