// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#![allow(dead_code)]
static FLAVOR_TEXT_MEMBER_FLAVOR_TEXT: ::aws_smithy_schema::Schema<'static> =
    ::aws_smithy_schema::Schema::new_member(
        ::aws_smithy_schema::ShapeId::from_parts(
            "com.aws.example#FlavorText$flavorText",
            "com.aws.example",
            "FlavorText",
        ),
        ::aws_smithy_schema::ShapeType::String,
        "flavorText",
        0,
    );
static FLAVOR_TEXT_MEMBER_LANGUAGE: ::aws_smithy_schema::Schema<'static> =
    ::aws_smithy_schema::Schema::new_member(
        ::aws_smithy_schema::ShapeId::from_parts(
            "com.aws.example#FlavorText$language",
            "com.aws.example",
            "FlavorText",
        ),
        ::aws_smithy_schema::ShapeType::String,
        "language",
        1,
    );
static FLAVOR_TEXT_SCHEMA: ::aws_smithy_schema::Schema<'static> =
    ::aws_smithy_schema::Schema::new_struct(
        ::aws_smithy_schema::ShapeId::from_parts(
            "com.aws.example#FlavorText",
            "com.aws.example",
            "FlavorText",
        ),
        ::aws_smithy_schema::ShapeType::Structure,
        &[
            &FLAVOR_TEXT_MEMBER_FLAVOR_TEXT,
            &FLAVOR_TEXT_MEMBER_LANGUAGE,
        ],
    );
pub(crate) const FLAVOR_TEXT: &'static ::aws_smithy_schema::Schema<'static> = &FLAVOR_TEXT_SCHEMA;
