// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#![allow(dead_code)]
static STORAGE_ACCESS_NOT_AUTHORIZED_SCHEMA: ::aws_smithy_schema::Schema<'static> = ::aws_smithy_schema::Schema::new_struct(
                            ::aws_smithy_schema::ShapeId::from_parts("com.aws.example#StorageAccessNotAuthorized", "com.aws.example", "StorageAccessNotAuthorized"),
                            ::aws_smithy_schema::ShapeType::Structure,
                            &[],
                        );
pub(crate) const STORAGE_ACCESS_NOT_AUTHORIZED: &'static ::aws_smithy_schema::Schema<'static> =
                        &STORAGE_ACCESS_NOT_AUTHORIZED_SCHEMA;

