// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct GetPokemonSpeciesOutput {
    /// The name for this resource.
    pub name: ::std::string::String,
    /// A list of flavor text entries for this Pokémon species.
    pub flavor_text_entries: ::std::vec::Vec<crate::types::FlavorText>,
}
impl GetPokemonSpeciesOutput {
    /// The name for this resource.
    pub fn name(&self) -> &str {
        use std::ops::Deref;
        self.name.deref()
    }
    /// A list of flavor text entries for this Pokémon species.
    pub fn flavor_text_entries(&self) -> &[crate::types::FlavorText] {
        use std::ops::Deref;
        self.flavor_text_entries.deref()
    }
}
static GETPOKEMONSPECIESOUTPUT_MEMBER_NAME: ::aws_smithy_schema::Schema<'static> = ::aws_smithy_schema::Schema::new_member(
    ::aws_smithy_schema::ShapeId::from_parts(
        "com.aws.example.synthetic#GetPokemonSpeciesOutput$name",
        "com.aws.example.synthetic",
        "GetPokemonSpeciesOutput",
    ),
    ::aws_smithy_schema::ShapeType::String,
    "name",
    0,
);
static GETPOKEMONSPECIESOUTPUT_MEMBER_FLAVOR_TEXT_ENTRIES_MEMBER: ::aws_smithy_schema::Schema<'static> = ::aws_smithy_schema::Schema::new_member(
    ::aws_smithy_schema::ShapeId::from_parts("com.aws.example#FlavorTextEntries$member", "com.aws.example", "FlavorTextEntries"),
    ::aws_smithy_schema::ShapeType::Structure,
    "member",
    0,
);
static GETPOKEMONSPECIESOUTPUT_MEMBER_FLAVOR_TEXT_ENTRIES: ::aws_smithy_schema::Schema<'static> = ::aws_smithy_schema::Schema::new_member(
    ::aws_smithy_schema::ShapeId::from_parts(
        "com.aws.example.synthetic#GetPokemonSpeciesOutput$flavorTextEntries",
        "com.aws.example.synthetic",
        "GetPokemonSpeciesOutput",
    ),
    ::aws_smithy_schema::ShapeType::List,
    "flavorTextEntries",
    1,
)
.with_list_member(&GETPOKEMONSPECIESOUTPUT_MEMBER_FLAVOR_TEXT_ENTRIES_MEMBER);
static GETPOKEMONSPECIESOUTPUT_SCHEMA: ::aws_smithy_schema::Schema<'static> = ::aws_smithy_schema::Schema::new_struct(
    ::aws_smithy_schema::ShapeId::from_parts(
        "com.aws.example.synthetic#GetPokemonSpeciesOutput",
        "com.aws.example.synthetic",
        "GetPokemonSpeciesOutput",
    ),
    ::aws_smithy_schema::ShapeType::Structure,
    &[&GETPOKEMONSPECIESOUTPUT_MEMBER_NAME, &GETPOKEMONSPECIESOUTPUT_MEMBER_FLAVOR_TEXT_ENTRIES],
)
.with_original_name("GetPokemonSpeciesOutput");
impl GetPokemonSpeciesOutput {
    /// The schema for this shape.
    pub const SCHEMA: &'static ::aws_smithy_schema::Schema<'static> = &GETPOKEMONSPECIESOUTPUT_SCHEMA;
}
impl ::aws_smithy_schema::serde::SerializableStruct for GetPokemonSpeciesOutput {
    #[allow(unused_variables, clippy::diverging_sub_expression)]
    fn serialize_members(
        &self,
        ser: &mut dyn ::aws_smithy_schema::serde::ShapeSerializer,
    ) -> ::std::result::Result<(), ::aws_smithy_schema::serde::SerdeError> {
        {
            let val = &self.name;
            ser.write_string(&GETPOKEMONSPECIESOUTPUT_MEMBER_NAME, val)?;
        }
        {
            let val = &self.flavor_text_entries;

            ser.write_list(
                &GETPOKEMONSPECIESOUTPUT_MEMBER_FLAVOR_TEXT_ENTRIES,
                &|ser: &mut dyn ::aws_smithy_schema::serde::ShapeSerializer| {
                    for item in val {
                        ser.write_struct(crate::types::FlavorText::SCHEMA, item)?;
                    }
                    Ok(())
                },
            )?;
        }
        Ok(())
    }
}
impl GetPokemonSpeciesOutput {
    /// Deserializes this structure from a [`ShapeDeserializer`].
    pub fn deserialize(
        deserializer: &mut dyn ::aws_smithy_schema::serde::ShapeDeserializer,
    ) -> ::std::result::Result<Self, ::aws_smithy_schema::serde::SerdeError> {
        #[allow(unused_variables, unused_mut)]
        let mut builder = Self::builder();
        #[allow(
            unused_variables,
            unreachable_code,
            clippy::single_match,
            clippy::match_single_binding,
            clippy::diverging_sub_expression
        )]
        deserializer.read_struct(&GETPOKEMONSPECIESOUTPUT_SCHEMA, &mut |member, deser| {
            match member.member_index() {
                Some(0) => {
                    builder.name = Some(deser.read_string(member)?);
                }
                Some(1) => {
                    builder.flavor_text_entries = Some({
                        let mut container = Vec::new();
                        deser.read_list(member, &mut |deser| {
                            container.push(crate::types::FlavorText::deserialize(deser)?);
                            Ok(())
                        })?;
                        container
                    });
                }
                _ => {}
            }
            Ok(())
        })?;
        builder.name = builder.name.or(Some(String::new()));
        builder.flavor_text_entries = builder.flavor_text_entries.or(Some(Vec::new()));
        builder.build().map_err(|e| aws_smithy_schema::serde::SerdeError::custom(e.to_string()))
    }
}
impl GetPokemonSpeciesOutput {
    /// Deserializes this structure from a body deserializer and HTTP response.
    pub fn deserialize_with_response(
        deserializer: &mut dyn ::aws_smithy_schema::serde::ShapeDeserializer,
        _headers: &::aws_smithy_runtime_api::http::Headers,
        _status: u16,
        _body: &[u8],
    ) -> ::std::result::Result<Self, ::aws_smithy_schema::serde::SerdeError> {
        Self::deserialize(deserializer)
    }
}
impl GetPokemonSpeciesOutput {
    /// Creates a new builder-style object to manufacture [`GetPokemonSpeciesOutput`](crate::operation::get_pokemon_species::GetPokemonSpeciesOutput).
    pub fn builder() -> crate::operation::get_pokemon_species::builders::GetPokemonSpeciesOutputBuilder {
        crate::operation::get_pokemon_species::builders::GetPokemonSpeciesOutputBuilder::default()
    }
}

/// A builder for [`GetPokemonSpeciesOutput`](crate::operation::get_pokemon_species::GetPokemonSpeciesOutput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct GetPokemonSpeciesOutputBuilder {
    pub(crate) name: ::std::option::Option<::std::string::String>,
    pub(crate) flavor_text_entries: ::std::option::Option<::std::vec::Vec<crate::types::FlavorText>>,
}
impl GetPokemonSpeciesOutputBuilder {
    /// The name for this resource.
    /// This field is required.
    pub fn name(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.name = ::std::option::Option::Some(input.into());
        self
    }
    /// The name for this resource.
    pub fn set_name(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.name = input;
        self
    }
    /// The name for this resource.
    pub fn get_name(&self) -> &::std::option::Option<::std::string::String> {
        &self.name
    }
    /// Appends an item to `flavor_text_entries`.
    ///
    /// To override the contents of this collection use [`set_flavor_text_entries`](Self::set_flavor_text_entries).
    ///
    /// A list of flavor text entries for this Pokémon species.
    pub fn flavor_text_entries(mut self, input: crate::types::FlavorText) -> Self {
        let mut v = self.flavor_text_entries.unwrap_or_default();
        v.push(input);
        self.flavor_text_entries = ::std::option::Option::Some(v);
        self
    }
    /// A list of flavor text entries for this Pokémon species.
    pub fn set_flavor_text_entries(mut self, input: ::std::option::Option<::std::vec::Vec<crate::types::FlavorText>>) -> Self {
        self.flavor_text_entries = input;
        self
    }
    /// A list of flavor text entries for this Pokémon species.
    pub fn get_flavor_text_entries(&self) -> &::std::option::Option<::std::vec::Vec<crate::types::FlavorText>> {
        &self.flavor_text_entries
    }
    /// Consumes the builder and constructs a [`GetPokemonSpeciesOutput`](crate::operation::get_pokemon_species::GetPokemonSpeciesOutput).
    /// This method will fail if any of the following fields are not set:
    /// - [`name`](crate::operation::get_pokemon_species::builders::GetPokemonSpeciesOutputBuilder::name)
    /// - [`flavor_text_entries`](crate::operation::get_pokemon_species::builders::GetPokemonSpeciesOutputBuilder::flavor_text_entries)
    pub fn build(
        self,
    ) -> ::std::result::Result<crate::operation::get_pokemon_species::GetPokemonSpeciesOutput, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(crate::operation::get_pokemon_species::GetPokemonSpeciesOutput {
            name: self.name.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "name",
                    "name was not specified but it is required when building GetPokemonSpeciesOutput",
                )
            })?,
            flavor_text_entries: self.flavor_text_entries.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "flavor_text_entries",
                    "flavor_text_entries was not specified but it is required when building GetPokemonSpeciesOutput",
                )
            })?,
        })
    }
}
