#!/bin/bash
#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

set -eux
cd smithy-rs/rust-runtime/aws-smithy-http-server-python/examples

make test
