#!/bin/bash
#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#

C_YELLOW='\033[1;33m'
C_RESET='\033[0m'

set -eux
cd smithy-rs

for runtime_path in \
    "rust-runtime" \
    "aws/rust-runtime"
do
    echo -e "${C_YELLOW}Testing ${runtime_path}...${C_RESET}"
    pushd "${runtime_path}" &>/dev/null
    cargo clippy --all-features
    cargo test --all-features
    cargo doc --no-deps --document-private-items --all-features
    cargo +"${RUST_NIGHTLY_VERSION}" minimal-versions check --all-features
    popd &>/dev/null

    echo -e "${C_YELLOW}Running additional per-crate checks for ${runtime_path}...${C_RESET}"
    ./tools/additional-per-crate-checks.sh "${runtime_path}"
done
