#!/bin/bash
#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#

# this job runs `cargo check` only instead of `cargo test --all-features`

set -eux
cd aws-sdk

# Remove examples from workspace
sed -i '/"examples\//d' Cargo.toml

cargo check --all-targets --all-features
