#!/bin/bash
#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0.
#

set -eux
cd workspace/smithy-rs
sdk-lints check --all
sdk-lints fix --all
./gradlew ktlint
