#!/bin/bash
#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#

set -eux
cd aws-sdk

cargo deny --all-features check --config ../smithy-rs/.cargo-deny-config.toml licenses bans sources
