#!/bin/bash
#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#

set -eux

# Docs, clippy, etc on the smoketest itself
pushd aws-sdk-smoketest &>/dev/null

# Override "fail on warning" for smoke test docs since DynamoDB's modeled docs cause rustdoc warnings
RUSTDOCFLAGS="" cargo doc --no-deps --document-private-items --all-features

cargo clippy --all-features
cargo +"${RUST_NIGHTLY_VERSION}" udeps
popd &>/dev/null

# Move the smoketest artifacts into smithy-rs and check the integration tests
# (which use path dependencies into the generated artifacts) against them.
mkdir -p smithy-rs/aws/sdk/build
mv aws-sdk-smoketest smithy-rs/aws/sdk/build/aws-sdk
pushd smithy-rs/aws/sdk/integration-tests
cargo check
popd &>/dev/null
