#!/bin/bash
#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#

C_YELLOW='\033[1;33m'
C_RESET='\033[0m'

set -eux
cd smithy-rs

# Make aws-config (which depends on generated services) available to additional checks
mkdir -p aws/sdk/build
mv ../aws-sdk-smoketest aws/sdk/build/aws-sdk

for runtime_path in \
    "rust-runtime" \
    "aws/rust-runtime"
do
    echo -e "${C_YELLOW}Testing ${runtime_path}...${C_RESET}"
    pushd "${runtime_path}" &>/dev/null
    cargo clippy --all-features
    cargo test --all-features
    cargo doc --no-deps --document-private-items --all-features
    cargo +"${RUST_NIGHTLY_VERSION}" minimal-versions check --all-features
    popd &>/dev/null
done

# test_tool tool_path rust_version
function test_tool {
    local tool_path="$1"
    local rust_version="$2"

    echo -e "${C_YELLOW}Testing ${tool_path}...${C_RESET}"
    pushd "${tool_path}" &>/dev/null
    cargo +"${rust_version}" clippy --all-features
    cargo +"${rust_version}" test --all-features
    popd &>/dev/null
}

test_tool "tools/api-linter" "${RUST_NIGHTLY_VERSION}"
test_tool "tools/crate-hasher" "${RUST_STABLE_VERSION}"
test_tool "tools/publisher" "${RUST_STABLE_VERSION}"
test_tool "tools/sdk-lints" "${RUST_STABLE_VERSION}"
test_tool "tools/sdk-sync" "${RUST_STABLE_VERSION}"
test_tool "tools/sdk-versioner" "${RUST_STABLE_VERSION}"
test_tool "tools/smithy-rs-tool-common" "${RUST_STABLE_VERSION}"

echo -e "${C_YELLOW}Running additional per-crate checks...${C_RESET}"
./tools/additional-per-crate-checks.sh ./tools/
