#!/bin/bash
#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#

C_YELLOW='\033[1;33m'
C_RESET='\033[0m'

set -eux
cd smithy-rs

function run_cargo_cmd() {
  local cargo_cmd=$1
  local cargo_cmd_flags=$2
  local nightly_override=$3

    echo -e "## ${C_YELLOW}Running 'cargo $cargo_cmd' on ${runtime_path}...${C_RESET}"
    cargo $nightly_override $cargo_cmd $cargo_cmd_flags
}

for runtime_path in \
    "rust-runtime" \
    "aws/rust-runtime"
do
    echo -e "# ${C_YELLOW}Testing ${runtime_path}...${C_RESET}"
    pushd "${runtime_path}" &>/dev/null

    run_cargo_cmd "clippy" "--all-features" ""
    run_cargo_cmd "test" "--all-features" ""
    run_cargo_cmd "doc" "--no-deps --document-private-items --all-features" ""
    run_cargo_cmd "minimal-versions check" "--all-features" "+${RUST_NIGHTLY_VERSION}"

    for crate_path in *; do
        if [[ -f "${crate_path}/external-types.toml" ]]; then
            # Skip `aws-config` since it has its own checks in `check-aws-config`
            if [[ "${crate_path}" != "aws-config" ]]; then
                echo -e "## ${C_YELLOW}Running 'cargo check-external-types' on ${crate_path}...${C_RESET}"
                pushd "${crate_path}" &>/dev/null
                # Override "fail on warning" for docs since `cargo-check-external-types` relies on rustdoc JSON output.
                RUSTDOCFLAGS="" cargo +"${RUST_NIGHTLY_VERSION}" check-external-types --all-features --config external-types.toml
                popd &>/dev/null
            fi
        fi
    done

    popd &>/dev/null

    echo -e "${C_YELLOW}Running additional per-crate checks for ${runtime_path}...${C_RESET}"
    ./tools/additional-per-crate-checks.sh "${runtime_path}"
done
