#!/bin/bash
#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#

set -eux
cd aws-sdk-smoketest
# We run these on the generated SDK due to aws-config depending on generated services
../smithy-rs/tools/additional-per-crate-checks.sh ./sdk/
