#!/bin/bash
#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#

C_YELLOW='\033[1;33m'
C_RESET='\033[0m'
set -eux

# This script takes an optional argument to specify the path to the previous release's versions.toml file
PREVIOUS_RELEASE_VERSIONS_ARG=
if [[ $# -ge 1 ]]; then
    echo "Given previous release manifest path: $1"
    PREVIOUS_RELEASE_VERSIONS_ARG="-Paws.sdk.previous.release.versions.manifest=$1"
fi

echo -e "${C_YELLOW}Taking examples from 'awsdocs/aws-doc-sdk-examples'...${C_RESET}"
examples_revision=$(cd aws-doc-sdk-examples; git rev-parse HEAD)
mv aws-doc-sdk-examples/rust_dev_preview smithy-rs/aws/sdk/examples
rm -rf smithy-rs/aws/sdk/examples/.cargo
rm smithy-rs/aws/sdk/examples/Cargo.toml

echo -e "${C_YELLOW}Generating services...${C_RESET}"
cd smithy-rs

# Intentionally not quoting PREVIOUS_RELEASE_VERSIONS_ARG so that if it has no value, it doesn't confuse gradle
# shellcheck disable=SC2086
./gradlew \
    -Paws.fullsdk=true \
    -Paws.sdk.examples.revision="${examples_revision}" \
    ${PREVIOUS_RELEASE_VERSIONS_ARG} \
    aws:sdk:assemble
mv aws/sdk/build/aws-sdk ../artifacts/
