#!/bin/bash
#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#

set -eux
cd smithy-rs

# TODO(https://github.com/awslabs/smithy-rs/issues/1493): Remove the `aws.services` property once the
# non-smoketest models have been removed from smithy-rs
./gradlew aws:sdk:assemble '-Paws.services=+config,+dynamodb,+ec2,+glacier,+iam,+kms,+polly,+qldbsession,+s3,+s3control,+sts,+sso,+transcribestreaming,+route53'
python3 aws/sdk/test-services.py > aws/sdk/build/aws-sdk/services-with-tests
mv aws/sdk/build/aws-sdk ../artifacts/aws-sdk-smoketest
