#!/bin/bash
#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0.
#

set -eux
cd smithy-rs

./gradlew rust-runtime:assemble
mv rust-runtime/build/smithy-rs ../artifacts/smithy-rs-runtime
