#!/bin/bash
#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0.
#

C_YELLOW='\033[1;33m'
C_RESET='\033[0m'

set -eux

echo -e "${C_YELLOW}Taking examples from 'awsdocs/aws-doc-sdk-examples'...${C_RESET}"
mv aws-doc-sdk-examples/rust_dev_preview smithy-rs/aws/sdk/examples
rm -rf smithy-rs/aws/sdk/examples/.cargo
rm smithy-rs/aws/sdk/examples/Cargo.toml

echo -e "${C_YELLOW}Generating services...${C_RESET}"
cd smithy-rs
./gradlew -Paws.fullsdk=true aws:sdk:assemble
mv aws/sdk/build/aws-sdk ../artifacts/
