#!/bin/bash
#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0.
#

set -eux

cargo --version
git --version
java --version
node --version
publisher --version
sdk-versioner --version
python3 --version
rustc +"${RUST_NIGHTLY_VERSION}" --version
rustc --version
