// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`DoNothing`](crate::operation::do_nothing::builders::DoNothingFluentBuilder) operation.
    ///
    /// - The fluent builder takes no input, just [`send`](crate::operation::do_nothing::builders::DoNothingFluentBuilder::send) it.
    /// - On success, responds with [`DoNothingOutput`](crate::operation::do_nothing::DoNothingOutput)
    /// - On failure, responds with [`SdkError<DoNothingError>`](crate::operation::do_nothing::DoNothingError)
    pub fn do_nothing(&self) -> crate::operation::do_nothing::builders::DoNothingFluentBuilder {
        crate::operation::do_nothing::builders::DoNothingFluentBuilder::new(self.handle.clone())
    }
}
