// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_get_storage_output_output(
    input: &crate::output::GetStorageOutput,
    writer: ::aws_smithy_xml::encode::ElWriter,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    {
        let mut inner_writer = scope.start_el("collection").finish();
        for list_item_1 in &input.collection {
            {
                let mut inner_writer = inner_writer.start_el("member").finish();
                inner_writer.data(list_item_1.as_str());
            }
        }
    }
    scope.finish();
    Ok(())
}
