// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_resource_not_found_exception_error(
    error: &crate::error::ResourceNotFoundException,
) -> ::std::result::Result<String, ::aws_smithy_types::error::operation::SerializationError> {
    let mut out = String::new();
    {
        let mut writer = ::aws_smithy_xml::encode::XmlWriter::new(&mut out);
        #[allow(unused_mut)]
        let mut root = writer.start_el("Error");
        crate::protocol_serde::shape_resource_not_found_exception::ser_resource_not_found_exception(
            error, root,
        )?
    }
    Ok(out)
}

pub fn ser_resource_not_found_exception(
    input: &crate::error::ResourceNotFoundException,
    writer: ::aws_smithy_xml::encode::ElWriter,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    {
        let mut inner_writer = scope.start_el("message").finish();
        inner_writer.data(input.message.as_str());
    }
    scope.finish();
    Ok(())
}
