// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
/// The service builder for [`TickService`].
///
/// Constructed via [`TickService::builder`].
pub struct TickServiceBuilder<Body, L, HttpPl, ModelPl> {
    fizz_buzz: Option<::aws_smithy_http_server::routing::Route<Body>>,
    layer: L,
    http_plugin: HttpPl,
    model_plugin: ModelPl,
}

impl<Body, L, HttpPl, ModelPl> TickServiceBuilder<Body, L, HttpPl, ModelPl> {
    /// Sets the [`FizzBuzz`](crate::operation_shape::FizzBuzz) operation.
    ///
    /// This should be an async function satisfying the [`Handler`](::aws_smithy_http_server::operation::Handler) trait.
    /// See the [operation module documentation](::aws_smithy_http_server::operation) for more information.
    ///
    /// # Example
    ///
    /// ```no_run
    /// use sdk::{TickService, TickServiceConfig};
    ///
    /// use sdk::{input, output, error};
    ///
    /// async fn handler(input: input::FizzBuzzInput) -> Result<output::FizzBuzzOutput, error::FizzBuzzError> {
    ///     todo!()
    /// }
    ///
    /// let config = TickServiceConfig::builder().build();
    /// let app = TickService::builder(config)
    ///     .fizz_buzz(handler)
    ///     /* Set other handlers */
    ///     .build()
    ///     .unwrap();
    /// # let app: TickService<::aws_smithy_http_server::routing::RoutingService<::aws_smithy_http_server::protocol::rpc_v2_cbor::router::RpcV2CborRouter<::aws_smithy_http_server::routing::Route>, ::aws_smithy_http_server::protocol::rpc_v2_cbor::RpcV2Cbor>> = app;
    /// ```
    ///
                    pub fn fizz_buzz<HandlerType, HandlerExtractors, UpgradeExtractors>(self, handler: HandlerType) -> Self
                    where
                        HandlerType: ::aws_smithy_http_server::operation::Handler<crate::operation_shape::FizzBuzz, HandlerExtractors>,

                        ModelPl: ::aws_smithy_http_server::plugin::Plugin<
                            TickService<L>,
                            crate::operation_shape::FizzBuzz,
                            ::aws_smithy_http_server::operation::IntoService<crate::operation_shape::FizzBuzz, HandlerType>
                        >,
                        ::aws_smithy_http_server::operation::UpgradePlugin::<UpgradeExtractors>: ::aws_smithy_http_server::plugin::Plugin<
                            TickService<L>,
                            crate::operation_shape::FizzBuzz,
                            ModelPl::Output
                        >,
                        HttpPl: ::aws_smithy_http_server::plugin::Plugin<
                            TickService<L>,
                            crate::operation_shape::FizzBuzz,
                            <
                                ::aws_smithy_http_server::operation::UpgradePlugin::<UpgradeExtractors>
                                as ::aws_smithy_http_server::plugin::Plugin<
                                    TickService<L>,
                                    crate::operation_shape::FizzBuzz,
                                    ModelPl::Output
                                >
                            >::Output
                        >,

                        HttpPl::Output: ::tower::Service<::http::Request<Body>, Response = ::http::Response<::aws_smithy_http_server::body::BoxBody>, Error = ::std::convert::Infallible> + Clone + Send + 'static,
                        <HttpPl::Output as ::tower::Service<::http::Request<Body>>>::Future: Send + 'static,

                    {
        use ::aws_smithy_http_server::operation::OperationShapeExt;
        use ::aws_smithy_http_server::plugin::Plugin;
        let svc = crate::operation_shape::FizzBuzz::from_handler(handler);
        let svc = self.model_plugin.apply(svc);
        let svc = ::aws_smithy_http_server::operation::UpgradePlugin::<UpgradeExtractors>::new()
            .apply(svc);
        let svc = self.http_plugin.apply(svc);
        self.fizz_buzz_custom(svc)
    }

    /// Sets the [`FizzBuzz`](crate::operation_shape::FizzBuzz) operation.
    ///
    /// This should be an async function satisfying the [`Handler`](::aws_smithy_http_server::operation::Handler) trait.
    /// See the [operation module documentation](::aws_smithy_http_server::operation) for more information.
    ///
    /// # Example
    ///
    /// ```no_run
    /// use sdk::{TickService, TickServiceConfig};
    ///
    /// use sdk::{input, output, error};
    ///
    /// async fn handler(input: input::FizzBuzzInput) -> Result<output::FizzBuzzOutput, error::FizzBuzzError> {
    ///     todo!()
    /// }
    ///
    /// let config = TickServiceConfig::builder().build();
    /// let svc = ::tower::util::service_fn(handler);
    /// let app = TickService::builder(config)
    ///     .fizz_buzz_service(svc)
    ///     /* Set other handlers */
    ///     .build()
    ///     .unwrap();
    /// # let app: TickService<::aws_smithy_http_server::routing::RoutingService<::aws_smithy_http_server::protocol::rpc_v2_cbor::router::RpcV2CborRouter<::aws_smithy_http_server::routing::Route>, ::aws_smithy_http_server::protocol::rpc_v2_cbor::RpcV2Cbor>> = app;
    /// ```
    ///
                    pub fn fizz_buzz_service<S, ServiceExtractors, UpgradeExtractors>(self, service: S) -> Self
                    where
                        S: ::aws_smithy_http_server::operation::OperationService<crate::operation_shape::FizzBuzz, ServiceExtractors>,

                        ModelPl: ::aws_smithy_http_server::plugin::Plugin<
                            TickService<L>,
                            crate::operation_shape::FizzBuzz,
                            ::aws_smithy_http_server::operation::Normalize<crate::operation_shape::FizzBuzz, S>
                        >,
                        ::aws_smithy_http_server::operation::UpgradePlugin::<UpgradeExtractors>: ::aws_smithy_http_server::plugin::Plugin<
                            TickService<L>,
                            crate::operation_shape::FizzBuzz,
                            ModelPl::Output
                        >,
                        HttpPl: ::aws_smithy_http_server::plugin::Plugin<
                            TickService<L>,
                            crate::operation_shape::FizzBuzz,
                            <
                                ::aws_smithy_http_server::operation::UpgradePlugin::<UpgradeExtractors>
                                as ::aws_smithy_http_server::plugin::Plugin<
                                    TickService<L>,
                                    crate::operation_shape::FizzBuzz,
                                    ModelPl::Output
                                >
                            >::Output
                        >,

                        HttpPl::Output: ::tower::Service<::http::Request<Body>, Response = ::http::Response<::aws_smithy_http_server::body::BoxBody>, Error = ::std::convert::Infallible> + Clone + Send + 'static,
                        <HttpPl::Output as ::tower::Service<::http::Request<Body>>>::Future: Send + 'static,

                    {
        use ::aws_smithy_http_server::operation::OperationShapeExt;
        use ::aws_smithy_http_server::plugin::Plugin;
        let svc = crate::operation_shape::FizzBuzz::from_service(service);
        let svc = self.model_plugin.apply(svc);
        let svc = ::aws_smithy_http_server::operation::UpgradePlugin::<UpgradeExtractors>::new()
            .apply(svc);
        let svc = self.http_plugin.apply(svc);
        self.fizz_buzz_custom(svc)
    }

    /// Sets the [`FizzBuzz`](crate::operation_shape::FizzBuzz) to a custom [`Service`](tower::Service).
    /// not constrained by the Smithy contract.
    fn fizz_buzz_custom<S>(mut self, svc: S) -> Self
    where
        S: ::tower::Service<
                ::http::Request<Body>,
                Response = ::http::Response<::aws_smithy_http_server::body::BoxBody>,
                Error = ::std::convert::Infallible,
            > + Clone
            + Send
            + 'static,
        S::Future: Send + 'static,
    {
        self.fizz_buzz = Some(::aws_smithy_http_server::routing::Route::new(svc));
        self
    }
}

impl<Body, L, HttpPl, ModelPl> TickServiceBuilder<Body, L, HttpPl, ModelPl> {
    /// Constructs a [`TickService`] from the arguments provided to the builder.
    ///
    /// Forgetting to register a handler for one or more operations will result in an error.
    ///
    /// Check out [`TickServiceBuilder::build_unchecked`] if you'd prefer the service to return status code 500 when an
    /// unspecified route is requested.
    pub fn build(
        self,
    ) -> ::std::result::Result<
        TickService<
            ::aws_smithy_http_server::routing::RoutingService<
                ::aws_smithy_http_server::protocol::rpc_v2_cbor::router::RpcV2CborRouter<
                    L::Service,
                >,
                ::aws_smithy_http_server::protocol::rpc_v2_cbor::RpcV2Cbor,
            >,
        >,
        MissingOperationsError,
    >
    where
        L: ::tower::Layer<::aws_smithy_http_server::routing::Route<Body>>,
    {
        let router = {
            use ::aws_smithy_http_server::operation::OperationShape;
            let mut missing_operation_names = std::collections::HashMap::new();
            if self.fizz_buzz.is_none() {
                missing_operation_names
                    .insert(crate::operation_shape::FizzBuzz::ID, ".fizz_buzz()");
            }
            if !missing_operation_names.is_empty() {
                return Err(MissingOperationsError {
                    operation_names2setter_methods: missing_operation_names,
                });
            }
            let unexpected_error_msg = "this should never panic since we are supposed to check beforehand that a handler has been registered for this operation; please file a bug report under https://github.com/smithy-lang/smithy-rs/issues";

            ::aws_smithy_http_server::protocol::rpc_v2_cbor::router::RpcV2CborRouter::from_iter([(
                request_specs::fizz_buzz(),
                self.fizz_buzz.expect(unexpected_error_msg),
            )])
        };
        let svc = ::aws_smithy_http_server::routing::RoutingService::new(router);
        let svc = svc.map(|s| s.layer(self.layer));
        Ok(TickService { svc })
    }

    /// Constructs a [`TickService`] from the arguments provided to the builder.
    /// Operations without a handler default to returning 500 Internal Server Error to the caller.
    ///
    /// Check out [`TickServiceBuilder::build`] if you'd prefer the builder to fail if one or more operations do
    /// not have a registered handler.
    pub fn build_unchecked(self) -> TickService<L::Service>
    where
        Body: Send + 'static,
        L: ::tower::Layer<
            ::aws_smithy_http_server::routing::RoutingService<
                ::aws_smithy_http_server::protocol::rpc_v2_cbor::router::RpcV2CborRouter<
                    ::aws_smithy_http_server::routing::Route<Body>,
                >,
                ::aws_smithy_http_server::protocol::rpc_v2_cbor::RpcV2Cbor,
            >,
        >,
    {
        let router =
            ::aws_smithy_http_server::protocol::rpc_v2_cbor::router::RpcV2CborRouter::from_iter([
                (
                    request_specs::fizz_buzz(),
                    self.fizz_buzz.unwrap_or_else(|| {
                        let svc = ::aws_smithy_http_server::operation::MissingFailure::<
                            ::aws_smithy_http_server::protocol::rpc_v2_cbor::RpcV2Cbor,
                        >::default();
                        ::aws_smithy_http_server::routing::Route::new(svc)
                    }),
                ),
            ]);
        let svc = self
            .layer
            .layer(::aws_smithy_http_server::routing::RoutingService::new(
                router,
            ));
        TickService { svc }
    }
}

/// The error encountered when calling the [`TickServiceBuilder::build`] method if one or more operation handlers are not
/// specified.
#[derive(Debug)]
pub struct MissingOperationsError {
    operation_names2setter_methods:
        std::collections::HashMap<::aws_smithy_http_server::shape_id::ShapeId, &'static str>,
}

impl std::fmt::Display for MissingOperationsError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "You must specify a handler for all operations attached to `TickService`.\n\
                            We are missing handlers for the following operations:\n",
        )?;
        for operation_name in self.operation_names2setter_methods.keys() {
            writeln!(f, "- {}", operation_name.absolute())?;
        }

        writeln!(
            f,
            "\nUse the dedicated methods on `TickServiceBuilder` to register the missing handlers:"
        )?;
        for setter_name in self.operation_names2setter_methods.values() {
            writeln!(f, "- {}", setter_name)?;
        }
        Ok(())
    }
}

impl std::error::Error for MissingOperationsError {}

mod request_specs {
    pub(super) fn fizz_buzz() -> &'static str {
        "TickService.FizzBuzz"
    }
}

#[allow(missing_docs)] // documentation missing in model
///
/// See the [root](crate) documentation for more information.
#[derive(Clone)]
pub struct TickService<
    S = ::aws_smithy_http_server::routing::RoutingService<
        ::aws_smithy_http_server::protocol::rpc_v2_cbor::router::RpcV2CborRouter<
            ::aws_smithy_http_server::routing::Route<::aws_smithy_http_server::body::BoxBody>,
        >,
        ::aws_smithy_http_server::protocol::rpc_v2_cbor::RpcV2Cbor,
    >,
> {
    // This is the router wrapped by layers.
    svc: S,
}

impl TickService<()> {
    /// Constructs a builder for [`TickService`].
    /// You must specify a configuration object holding any plugins and layers that should be applied
    /// to the operations in this service.
    pub fn builder<
        Body,
        L,
        HttpPl: ::aws_smithy_http_server::plugin::HttpMarker,
        ModelPl: ::aws_smithy_http_server::plugin::ModelMarker,
    >(
        config: TickServiceConfig<L, HttpPl, ModelPl>,
    ) -> TickServiceBuilder<Body, L, HttpPl, ModelPl> {
        TickServiceBuilder {
            fizz_buzz: None,
            layer: config.layers,
            http_plugin: config.http_plugins,
            model_plugin: config.model_plugins,
        }
    }

    /// Constructs a builder for [`TickService`].
    /// You must specify what plugins should be applied to the operations in this service.
    ///
    /// Use [`TickService::builder_without_plugins`] if you don't need to apply plugins.
    ///
    /// Check out [`HttpPlugins`](::aws_smithy_http_server::plugin::HttpPlugins) and
    /// [`ModelPlugins`](::aws_smithy_http_server::plugin::ModelPlugins) if you need to apply
    /// multiple plugins.
    #[deprecated(
        since = "0.57.0",
        note = "please use the `builder` constructor and register plugins on the `TickServiceConfig` object instead; see https://github.com/smithy-lang/smithy-rs/discussions/3096"
    )]
    pub fn builder_with_plugins<
        Body,
        HttpPl: ::aws_smithy_http_server::plugin::HttpMarker,
        ModelPl: ::aws_smithy_http_server::plugin::ModelMarker,
    >(
        http_plugin: HttpPl,
        model_plugin: ModelPl,
    ) -> TickServiceBuilder<Body, ::tower::layer::util::Identity, HttpPl, ModelPl> {
        TickServiceBuilder {
            fizz_buzz: None,
            layer: ::tower::layer::util::Identity::new(),
            http_plugin,
            model_plugin,
        }
    }

    /// Constructs a builder for [`TickService`].
    ///
    /// Use [`TickService::builder_with_plugins`] if you need to specify plugins.
    #[deprecated(
        since = "0.57.0",
        note = "please use the `builder` constructor instead; see https://github.com/smithy-lang/smithy-rs/discussions/3096"
    )]
    pub fn builder_without_plugins<Body>() -> TickServiceBuilder<
        Body,
        ::tower::layer::util::Identity,
        ::aws_smithy_http_server::plugin::IdentityPlugin,
        ::aws_smithy_http_server::plugin::IdentityPlugin,
    > {
        Self::builder_with_plugins(
            ::aws_smithy_http_server::plugin::IdentityPlugin,
            ::aws_smithy_http_server::plugin::IdentityPlugin,
        )
    }
}

impl<S> TickService<S> {
    /// Converts [`TickService`] into a [`MakeService`](tower::make::MakeService).
    pub fn into_make_service(self) -> ::aws_smithy_http_server::routing::IntoMakeService<Self> {
        ::aws_smithy_http_server::routing::IntoMakeService::new(self)
    }

    /// Converts [`TickService`] into a [`MakeService`](tower::make::MakeService) with [`ConnectInfo`](::aws_smithy_http_server::request::connect_info::ConnectInfo).
    pub fn into_make_service_with_connect_info<C>(
        self,
    ) -> ::aws_smithy_http_server::routing::IntoMakeServiceWithConnectInfo<Self, C> {
        ::aws_smithy_http_server::routing::IntoMakeServiceWithConnectInfo::new(self)
    }
}

impl<S>
    TickService<
        ::aws_smithy_http_server::routing::RoutingService<
            ::aws_smithy_http_server::protocol::rpc_v2_cbor::router::RpcV2CborRouter<S>,
            ::aws_smithy_http_server::protocol::rpc_v2_cbor::RpcV2Cbor,
        >,
    >
{
    /// Applies a [`Layer`](::tower::Layer) uniformly to all routes.
    #[deprecated(
        since = "0.57.0",
        note = "please add layers to the `TickServiceConfig` object instead; see https://github.com/smithy-lang/smithy-rs/discussions/3096"
    )]
    pub fn layer<L>(
        self,
        layer: &L,
    ) -> TickService<
        ::aws_smithy_http_server::routing::RoutingService<
            ::aws_smithy_http_server::protocol::rpc_v2_cbor::router::RpcV2CborRouter<L::Service>,
            ::aws_smithy_http_server::protocol::rpc_v2_cbor::RpcV2Cbor,
        >,
    >
    where
        L: ::tower::Layer<S>,
    {
        TickService {
            svc: self.svc.map(|s| s.layer(layer)),
        }
    }

    /// Applies [`Route::new`](::aws_smithy_http_server::routing::Route::new) to all routes.
    ///
    /// This has the effect of erasing all types accumulated via layers.
    pub fn boxed<B>(
        self,
    ) -> TickService<
        ::aws_smithy_http_server::routing::RoutingService<
            ::aws_smithy_http_server::protocol::rpc_v2_cbor::router::RpcV2CborRouter<
                ::aws_smithy_http_server::routing::Route<B>,
            >,
            ::aws_smithy_http_server::protocol::rpc_v2_cbor::RpcV2Cbor,
        >,
    >
    where
        S: ::tower::Service<
            ::http::Request<B>,
            Response = ::http::Response<::aws_smithy_http_server::body::BoxBody>,
            Error = std::convert::Infallible,
        >,
        S: Clone + Send + 'static,
        S::Future: Send + 'static,
    {
        self.layer(&::tower::layer::layer_fn(
            ::aws_smithy_http_server::routing::Route::new,
        ))
    }
}

impl<S, R> ::tower::Service<R> for TickService<S>
where
    S: ::tower::Service<R>,
{
    type Response = S::Response;
    type Error = S::Error;
    type Future = S::Future;

    fn poll_ready(
        &mut self,
        cx: &mut std::task::Context,
    ) -> std::task::Poll<::std::result::Result<(), Self::Error>> {
        self.svc.poll_ready(cx)
    }

    fn call(&mut self, request: R) -> Self::Future {
        self.svc.call(request)
    }
}

/// An enumeration of all [operations](https://smithy.io/2.0/spec/service-types.html#operation) in TickService.
#[allow(clippy::enum_variant_names)]
#[derive(Debug, PartialEq, Eq, Clone, Copy)]
pub enum Operation {
    FizzBuzz,
}

impl Operation {
    /// Returns the [operations](https://smithy.io/2.0/spec/service-types.html#operation) [`ShapeId`](::aws_smithy_http_server::shape_id::ShapeId).
    pub fn shape_id(&self) -> ::aws_smithy_http_server::shape_id::ShapeId {
        match self {
            Operation::FizzBuzz => ::aws_smithy_http_server::shape_id::ShapeId::new(
                "smithy.example.eventstreaming#FizzBuzz",
                "smithy.example.eventstreaming",
                "FizzBuzz",
            ),
        }
    }
}
impl<L> ::aws_smithy_http_server::service::ContainsOperation<crate::operation_shape::FizzBuzz>
    for TickService<L>
{
    const VALUE: Operation = Operation::FizzBuzz;
}

impl<S> ::aws_smithy_http_server::service::ServiceShape for TickService<S> {
    const ID: ::aws_smithy_http_server::shape_id::ShapeId =
        ::aws_smithy_http_server::shape_id::ShapeId::new(
            "smithy.example.eventstreaming#TickService",
            "smithy.example.eventstreaming",
            "TickService",
        );

    const VERSION: Option<&'static str> = Some("");

    type Protocol = ::aws_smithy_http_server::protocol::rpc_v2_cbor::RpcV2Cbor;

    type Operations = Operation;
}
/// Configuration for the [`TickService`]. This is the central place where to register and
/// configure [`::tower::Layer`]s, HTTP plugins, and model plugins.
///
/// ```rust,no_run
/// # use sdk::TickServiceConfig;
/// # use ::aws_smithy_http_server::plugin::IdentityPlugin;
/// # use ::tower::layer::util::Identity;
/// # let authentication_plugin = IdentityPlugin;
/// # let authorization_plugin = IdentityPlugin;
/// # let server_request_id_provider_layer = Identity::new();
/// let config = TickServiceConfig::builder()
///     // Layers get executed first...
///     .layer(server_request_id_provider_layer)
///     // ...then HTTP plugins...
///     .http_plugin(authentication_plugin)
///     // ...and right after deserialization, model plugins.
///     .model_plugin(authorization_plugin)
///     .build();
/// ```
///
/// See the [`plugin`] system for details.
///
/// [`plugin`]: ::aws_smithy_http_server::plugin
#[derive(::std::fmt::Debug)]
pub struct TickServiceConfig<L, H, M> {
    layers: L,
    http_plugins: H,
    model_plugins: M,
}

impl TickServiceConfig<(), (), ()> {
    /// Returns a builder to construct the configuration.
    pub fn builder() -> TickServiceConfigBuilder<
        ::tower::layer::util::Identity,
        ::aws_smithy_http_server::plugin::IdentityPlugin,
        ::aws_smithy_http_server::plugin::IdentityPlugin,
    > {
        TickServiceConfigBuilder {
            layers: ::tower::layer::util::Identity::new(),
            http_plugins: ::aws_smithy_http_server::plugin::IdentityPlugin,
            model_plugins: ::aws_smithy_http_server::plugin::IdentityPlugin,
        }
    }
}

/// Builder returned by [`TickServiceConfig::builder()`].
#[derive(::std::fmt::Debug)]
pub struct TickServiceConfigBuilder<L, H, M> {
    pub(crate) layers: L,
    pub(crate) http_plugins: H,
    pub(crate) model_plugins: M,
}

impl<L, H, M> TickServiceConfigBuilder<L, H, M> {
    /// Add a [`::tower::Layer`] to the service.
    pub fn layer<NewLayer>(
        self,
        layer: NewLayer,
    ) -> TickServiceConfigBuilder<::tower::layer::util::Stack<NewLayer, L>, H, M> {
        TickServiceConfigBuilder {
            layers: ::tower::layer::util::Stack::new(layer, self.layers),
            http_plugins: self.http_plugins,
            model_plugins: self.model_plugins,
        }
    }

    /// Add a HTTP [plugin] to the service.
    ///
    /// [plugin]: ::aws_smithy_http_server::plugin
    // We eagerly require `NewPlugin: HttpMarker`, despite not really needing it, because compiler
    // errors get _substantially_ better if the user makes a mistake.
    pub fn http_plugin<NewPlugin: ::aws_smithy_http_server::plugin::HttpMarker>(
        self,
        http_plugin: NewPlugin,
    ) -> TickServiceConfigBuilder<L, ::aws_smithy_http_server::plugin::PluginStack<NewPlugin, H>, M>
    {
        TickServiceConfigBuilder {
            layers: self.layers,
            http_plugins: ::aws_smithy_http_server::plugin::PluginStack::new(
                http_plugin,
                self.http_plugins,
            ),
            model_plugins: self.model_plugins,
        }
    }

    /// Add a model [plugin] to the service.
    ///
    /// [plugin]: ::aws_smithy_http_server::plugin
    // We eagerly require `NewPlugin: ModelMarker`, despite not really needing it, because compiler
    // errors get _substantially_ better if the user makes a mistake.
    pub fn model_plugin<NewPlugin: ::aws_smithy_http_server::plugin::ModelMarker>(
        self,
        model_plugin: NewPlugin,
    ) -> TickServiceConfigBuilder<L, H, ::aws_smithy_http_server::plugin::PluginStack<NewPlugin, M>>
    {
        TickServiceConfigBuilder {
            layers: self.layers,
            http_plugins: self.http_plugins,
            model_plugins: ::aws_smithy_http_server::plugin::PluginStack::new(
                model_plugin,
                self.model_plugins,
            ),
        }
    }

    /// Build the configuration.
    pub fn build(self) -> super::TickServiceConfig<L, H, M> {
        super::TickServiceConfig {
            layers: self.layers,
            http_plugins: self.http_plugins,
            model_plugins: self.model_plugins,
        }
    }
}
/// A macro to help with scoping [plugins](crate::server::plugin) to a subset of all operations.
///
/// In contrast to [`crate::server::scope`](crate::server::scope), this macro has knowledge
/// of the service and any operations _not_ specified will be placed in the opposing group.
///
/// # Example
///
/// ```rust
/// scope! {
///     /// Includes [`FizzBuzz`], excluding all other operations.
///     struct ScopeA {
///         includes: [FizzBuzz]
///     }
/// }
///
/// scope! {
///     /// Excludes [`FizzBuzz`], excluding all other operations.
///     struct ScopeB {
///         excludes: [FizzBuzz]
///     }
/// }
///
/// # use sdk::server::plugin::{Plugin, Scoped};
/// # use sdk::scope;
/// # struct MockPlugin;
/// # impl<S, Op, T> Plugin<S, Op, T> for MockPlugin { type Output = u32; fn apply(&self, input: T) -> u32 { 3 } }
/// # let scoped_a = Scoped::new::<ScopeA>(MockPlugin);
/// # let scoped_b = Scoped::new::<ScopeB>(MockPlugin);
/// # let a = Plugin::<(), sdk::operation_shape::FizzBuzz, u64>::apply(&scoped_a, 6);
/// # let b = Plugin::<(), sdk::operation_shape::FizzBuzz, u64>::apply(&scoped_b, 6);
/// # assert_eq!(a, 3_u32);
/// # assert_eq!(b, 6_u64);
/// ```
#[macro_export]
macro_rules! scope {
                    // Completed, render impls
                    (@ $ name: ident, $ contains: ident () ($($ temp: ident)*) ($($ not_member: ident)*)) => {
                        $(
                            impl $ crate::server::plugin::scoped::Membership<$ temp> for $ name {
                                type Contains = $ crate::server::plugin::scoped::$ contains;
                            }
                        )*
                        $(
                            impl $ crate::server::plugin::scoped::Membership<$ not_member> for $ name {
                                type Contains = $ crate::server::plugin::scoped::$ contains;
                            }
                        )*
                    };
                    // All `not_member`s exhausted, move `temp` into `not_member`
                    (@ $ name: ident, $ contains: ident ($($ member: ident)*) ($($ temp: ident)*) ()) => {
                        scope! { @ $ name, $ contains ($($ member)*) () ($($ temp)*) }
                    };

                        // FizzBuzz match found, pop from both `member` and `not_member`
                        (@ $ name: ident, $ contains: ident (FizzBuzz $($ member: ident)*) ($($ temp: ident)*) (FizzBuzz $($ not_member: ident)*)) => {
                            scope! { @ $ name, $ contains ($($ member)*) ($($ temp)*) ($($ not_member)*) }
                        };
                        // FizzBuzz match not found, pop from `not_member` into `temp` stack
                        (@ $ name: ident, $ contains: ident (FizzBuzz $($ member: ident)*) ($($ temp: ident)*) ($ other: ident $($ not_member: ident)*)) => {
                            scope! { @ $ name, $ contains (FizzBuzz $($ member)*) ($ other $($ temp)*) ($($ not_member)*) }
                        };

                    (
                        $(#[$ attrs:meta])*
                        $ vis:vis struct $ name:ident {
                            includes: [$($ include:ident),*]
                        }
                    ) => {
                        use $ crate::operation_shape::*;
                        $ crate::server::scope! {
                            $(#[$ attrs])*
                            $ vis struct $ name {
                                includes: [$($ include),*],
                                excludes: []
                            }
                        }
                        scope! { @ $ name, False ($($ include)*) () (FizzBuzz) }
                    };
                    (
                        $(#[$ attrs:meta])*
                        $ vis:vis struct $ name:ident {
                            excludes: [$($ exclude:ident),*]
                        }
                    ) => {
                        use $ crate::operation_shape::*;

                        $ crate::server::scope! {
                            $(#[$ attrs])*
                            $ vis struct $ name {
                                includes: [],
                                excludes: [$($ exclude),*]
                            }
                        }
                        scope! { @ $ name, True ($($ exclude)*) () (FizzBuzz) }
                    };
                }
