// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
/* CborSerializerGenerator.kt:244 */
pub fn ser_unsupported_region_error_error(
    value: &crate::error::UnsupportedRegionError,
) -> ::std::result::Result<
    ::std::vec::Vec<u8>,
    ::aws_smithy_types::error::operation::SerializationError,
> {
    /* CborSerializerGenerator.kt:249 */
    let mut encoder = ::aws_smithy_cbor::Encoder::new(::std::vec::Vec::new());
    /* CborSerializerGenerator.kt:251 */
    {
        /* CborSerializerGenerator.kt:252 */
        let encoder = &mut encoder;
        /* CborSerializerGenerator.kt:428 */
        crate::protocol_rpcv2_cbor::protocol_serde::shape_unsupported_region_error::ser_unsupported_region_error(encoder, value )?;
        /* CborSerializerGenerator.kt:251 */
    }
    /* CborSerializerGenerator.kt:258 */
    ::std::result::Result::Ok(encoder.into_writer())
    /* CborSerializerGenerator.kt:244 */
}

/* CborSerializerGenerator.kt:394 */
pub fn ser_unsupported_region_error(
    encoder: &mut ::aws_smithy_cbor::Encoder,
    #[allow(unused)] input: &crate::error::UnsupportedRegionError,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    /* CborSerializerGenerator.kt:402 */
    encoder.begin_map();
    /* AddTypeFieldToServerErrorsCborCustomization.kt:47 */
    encoder
        .str("__type")
        .str("com.aws.example#UnsupportedRegionError");
    /* SerializerUtil.kt:42 */
    {
        /* CborSerializerGenerator.kt:487 */
        encoder.str("region").str(input.region.as_str());
        /* SerializerUtil.kt:42 */
    }
    /* CborSerializerGenerator.kt:418 */
    encoder.end();
    /* CborSerializerGenerator.kt:419 */
    Ok(())
    /* CborSerializerGenerator.kt:394 */
}
