// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
/* CborSerializerGenerator.kt:394 */
pub fn ser_flavor_text(
    encoder: &mut ::aws_smithy_cbor::Encoder,
    #[allow(unused)] input: &crate::model::FlavorText,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    /* CborSerializerGenerator.kt:402 */
    encoder.begin_map();
    /* SerializerUtil.kt:42 */
    {
        /* CborSerializerGenerator.kt:487 */
        encoder.str("flavorText").str(input.flavor_text.as_str());
        /* SerializerUtil.kt:42 */
    }
    /* SerializerUtil.kt:42 */
    {
        /* CborSerializerGenerator.kt:487 */
        encoder.str("language").str(input.language.as_str());
        /* SerializerUtil.kt:42 */
    }
    /* CborSerializerGenerator.kt:418 */
    encoder.end();
    /* CborSerializerGenerator.kt:419 */
    Ok(())
    /* CborSerializerGenerator.kt:394 */
}
