// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
/* CborSerializerGenerator.kt:394 */
pub fn ser_validation_exception_field(
    encoder: &mut ::aws_smithy_cbor::Encoder,
    #[allow(unused)] input: &crate::model::ValidationExceptionField,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    /* CborSerializerGenerator.kt:402 */
    encoder.begin_map();
    /* SerializerUtil.kt:42 */
    {
        /* CborSerializerGenerator.kt:487 */
        encoder.str("path").str(input.path.as_str());
        /* SerializerUtil.kt:42 */
    }
    /* SerializerUtil.kt:42 */
    {
        /* CborSerializerGenerator.kt:487 */
        encoder.str("message").str(input.message.as_str());
        /* SerializerUtil.kt:42 */
    }
    /* CborSerializerGenerator.kt:418 */
    encoder.end();
    /* CborSerializerGenerator.kt:419 */
    Ok(())
    /* CborSerializerGenerator.kt:394 */
}
