// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_storage_access_not_authorized_error(error: &crate::error::StorageAccessNotAuthorized) -> ::std::result::Result<String, ::aws_smithy_types::error::operation::SerializationError> {
    let mut out = String::new();
     {
        let mut writer = ::aws_smithy_xml::encode::XmlWriter::new(&mut out);
                                #[allow(unused_mut)]
                                let mut root = writer.start_el("Error");
        crate::protocol_serde::shape_storage_access_not_authorized::ser_storage_access_not_authorized(error, root)?
    }
    Ok(out)
}

pub fn ser_storage_access_not_authorized(input: &crate::error::StorageAccessNotAuthorized, writer: ::aws_smithy_xml::encode::ElWriter) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    let _ = input;
    #[allow(unused_mut)]
    let mut scope = writer.finish();
    scope.finish();
    Ok(())
}

