// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_get_server_statistics_output_output(input: &crate::output::GetServerStatisticsOutput, writer: ::aws_smithy_xml::encode::ElWriter) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    #[allow(unused_mut)]
    let mut scope = writer.finish();
     {
        let mut inner_writer = scope.start_el("calls_count").finish();
        inner_writer.data(
            ::aws_smithy_types::primitive::Encoder::from(input.calls_count).encode()
        );
    }
    scope.finish();
    Ok(())
}

