// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct StreamPokemonRadioInput {}
static STREAMPOKEMONRADIOINPUT_SCHEMA: ::aws_smithy_schema::Schema<'static> = ::aws_smithy_schema::Schema::new_struct(
    ::aws_smithy_schema::ShapeId::from_parts(
        "com.aws.example.synthetic#StreamPokemonRadioInput",
        "com.aws.example.synthetic",
        "StreamPokemonRadioInput",
    ),
    ::aws_smithy_schema::ShapeType::Structure,
    &[],
)
.with_http(aws_smithy_schema::traits::HttpTrait::new("GET", "/radio", None))
.with_no_body_members();
impl StreamPokemonRadioInput {
    /// The schema for this shape.
    pub const SCHEMA: &'static ::aws_smithy_schema::Schema<'static> = &STREAMPOKEMONRADIOINPUT_SCHEMA;
}
impl ::aws_smithy_schema::serde::SerializableStruct for StreamPokemonRadioInput {
    #[allow(unused_variables, clippy::diverging_sub_expression)]
    fn serialize_members(
        &self,
        ser: &mut dyn ::aws_smithy_schema::serde::ShapeSerializer,
    ) -> ::std::result::Result<(), ::aws_smithy_schema::serde::SerdeError> {
        Ok(())
    }
}
impl StreamPokemonRadioInput {
    /// Deserializes this structure from a [`ShapeDeserializer`].
    pub fn deserialize(
        deserializer: &mut dyn ::aws_smithy_schema::serde::ShapeDeserializer,
    ) -> ::std::result::Result<Self, ::aws_smithy_schema::serde::SerdeError> {
        #[allow(unused_variables, unused_mut)]
        let mut builder = Self::builder();
        #[allow(
            unused_variables,
            unreachable_code,
            clippy::single_match,
            clippy::match_single_binding,
            clippy::diverging_sub_expression
        )]
        deserializer.read_struct(&STREAMPOKEMONRADIOINPUT_SCHEMA, &mut |member, deser| {
            match member.member_index() {
                _ => {}
            }
            Ok(())
        })?;
        builder.build().map_err(|e| aws_smithy_schema::serde::SerdeError::custom(e.to_string()))
    }
}
impl StreamPokemonRadioInput {
    /// Deserializes this structure from a body deserializer and HTTP response.
    pub fn deserialize_with_response(
        _deserializer: &mut dyn ::aws_smithy_schema::serde::ShapeDeserializer,
        _headers: &::aws_smithy_runtime_api::http::Headers,
        _status: u16,
        _body: &[u8],
    ) -> ::std::result::Result<Self, ::aws_smithy_schema::serde::SerdeError> {
        Self::builder()
            .build()
            .map_err(|e| aws_smithy_schema::serde::SerdeError::custom(e.to_string()))
    }
}
impl StreamPokemonRadioInput {
    /// Creates a new builder-style object to manufacture [`StreamPokemonRadioInput`](crate::operation::stream_pokemon_radio::StreamPokemonRadioInput).
    pub fn builder() -> crate::operation::stream_pokemon_radio::builders::StreamPokemonRadioInputBuilder {
        crate::operation::stream_pokemon_radio::builders::StreamPokemonRadioInputBuilder::default()
    }
}

/// A builder for [`StreamPokemonRadioInput`](crate::operation::stream_pokemon_radio::StreamPokemonRadioInput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct StreamPokemonRadioInputBuilder {}
impl StreamPokemonRadioInputBuilder {
    /// Consumes the builder and constructs a [`StreamPokemonRadioInput`](crate::operation::stream_pokemon_radio::StreamPokemonRadioInput).
    pub fn build(
        self,
    ) -> ::std::result::Result<crate::operation::stream_pokemon_radio::StreamPokemonRadioInput, ::aws_smithy_types::error::operation::BuildError>
    {
        ::std::result::Result::Ok(crate::operation::stream_pokemon_radio::StreamPokemonRadioInput {})
    }
}
