# This Cargo.toml is unused in generated code. It exists solely to enable these tests to compile in-situ
[package]
name = "polly-tests"
version = "0.1.0"
authors = ["John DiSanti <jdisanti@amazon.com>"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/smithy-lang/smithy-rs"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
aws-credential-types = { path = "../../build/aws-sdk/sdk/aws-credential-types", features = ["test-util"] }
aws-sdk-polly = { path = "../../build/aws-sdk/sdk/polly", features = ["behavior-version-latest"] }
aws-smithy-http = { path = "../../build/aws-sdk/sdk/aws-smithy-http" }
bytes = "1.0.0"
http-1x = { package = "http", version = "1" }
tokio = { version = "1.23.1", features = ["full"]}
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
