// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
/* ServerSchemaGenerators.kt:97 */
static CAPTURE_POKEMON_SHAPE: ::aws_smithy_schema::Schema<'static> =
    ::aws_smithy_schema::Schema::new(
        ::aws_smithy_schema::ShapeId::from_parts(
            "com.aws.example#CapturePokemon",
            "com.aws.example",
            "CapturePokemon",
        ),
        ::aws_smithy_schema::ShapeType::Operation,
    )
    .with_http(::aws_smithy_schema::traits::HttpTrait::new(
        "POST",
        "/capture-pokemon-event/{region}",
        Some(200),
    ));

static CAPTURE_POKEMON_ERRORS: &[&::aws_smithy_schema::Schema<'static>] = &[
    crate::error::InvalidPokeballError::SCHEMA,
    crate::error::MasterBallUnsuccessful::SCHEMA,
    crate::error::ThrottlingError::SCHEMA,
    crate::error::UnsupportedRegionError::SCHEMA,
    crate::error::ValidationException::SCHEMA,
];

/// Descriptor for the `com.aws.example#CapturePokemon` operation.
pub(crate) static CAPTURE_POKEMON: ::aws_smithy_schema::OperationSchema<'static> =
    ::aws_smithy_schema::OperationSchema::new(
        &CAPTURE_POKEMON_SHAPE,
        crate::input::CapturePokemonInput::SCHEMA,
        crate::output::CapturePokemonOutput::SCHEMA,
        CAPTURE_POKEMON_ERRORS,
    );
/* ServerSchemaGenerators.kt:97 */
static CHECK_HEALTH_SHAPE: ::aws_smithy_schema::Schema<'static> = ::aws_smithy_schema::Schema::new(
    ::aws_smithy_schema::ShapeId::from_parts(
        "com.aws.example#CheckHealth",
        "com.aws.example",
        "CheckHealth",
    ),
    ::aws_smithy_schema::ShapeType::Operation,
)
.with_http(::aws_smithy_schema::traits::HttpTrait::new(
    "GET",
    "/ping",
    Some(200),
));

static CHECK_HEALTH_ERRORS: &[&::aws_smithy_schema::Schema<'static>] = &[];

/// Descriptor for the `com.aws.example#CheckHealth` operation.
pub(crate) static CHECK_HEALTH: ::aws_smithy_schema::OperationSchema<'static> =
    ::aws_smithy_schema::OperationSchema::new(
        &CHECK_HEALTH_SHAPE,
        crate::input::CheckHealthInput::SCHEMA,
        crate::output::CheckHealthOutput::SCHEMA,
        CHECK_HEALTH_ERRORS,
    );
/* ServerSchemaGenerators.kt:97 */
static DO_NOTHING_SHAPE: ::aws_smithy_schema::Schema<'static> = ::aws_smithy_schema::Schema::new(
    ::aws_smithy_schema::ShapeId::from_parts(
        "com.aws.example#DoNothing",
        "com.aws.example",
        "DoNothing",
    ),
    ::aws_smithy_schema::ShapeType::Operation,
)
.with_http(::aws_smithy_schema::traits::HttpTrait::new(
    "GET",
    "/do-nothing",
    Some(200),
));

static DO_NOTHING_ERRORS: &[&::aws_smithy_schema::Schema<'static>] = &[];

/// Descriptor for the `com.aws.example#DoNothing` operation.
pub(crate) static DO_NOTHING: ::aws_smithy_schema::OperationSchema<'static> =
    ::aws_smithy_schema::OperationSchema::new(
        &DO_NOTHING_SHAPE,
        crate::input::DoNothingInput::SCHEMA,
        crate::output::DoNothingOutput::SCHEMA,
        DO_NOTHING_ERRORS,
    );
/* ServerSchemaGenerators.kt:97 */
static GET_POKEMON_SPECIES_SHAPE: ::aws_smithy_schema::Schema<'static> =
    ::aws_smithy_schema::Schema::new(
        ::aws_smithy_schema::ShapeId::from_parts(
            "com.aws.example#GetPokemonSpecies",
            "com.aws.example",
            "GetPokemonSpecies",
        ),
        ::aws_smithy_schema::ShapeType::Operation,
    )
    .with_http(::aws_smithy_schema::traits::HttpTrait::new(
        "GET",
        "/pokemon-species/{name}",
        Some(200),
    ));

static GET_POKEMON_SPECIES_ERRORS: &[&::aws_smithy_schema::Schema<'static>] = &[
    crate::error::ResourceNotFoundException::SCHEMA,
    crate::error::ValidationException::SCHEMA,
];

/// Descriptor for the `com.aws.example#GetPokemonSpecies` operation.
pub(crate) static GET_POKEMON_SPECIES: ::aws_smithy_schema::OperationSchema<'static> =
    ::aws_smithy_schema::OperationSchema::new(
        &GET_POKEMON_SPECIES_SHAPE,
        crate::input::GetPokemonSpeciesInput::SCHEMA,
        crate::output::GetPokemonSpeciesOutput::SCHEMA,
        GET_POKEMON_SPECIES_ERRORS,
    );
/* ServerSchemaGenerators.kt:97 */
static GET_SERVER_STATISTICS_SHAPE: ::aws_smithy_schema::Schema<'static> =
    ::aws_smithy_schema::Schema::new(
        ::aws_smithy_schema::ShapeId::from_parts(
            "com.aws.example#GetServerStatistics",
            "com.aws.example",
            "GetServerStatistics",
        ),
        ::aws_smithy_schema::ShapeType::Operation,
    )
    .with_http(::aws_smithy_schema::traits::HttpTrait::new(
        "GET",
        "/stats",
        Some(200),
    ));

static GET_SERVER_STATISTICS_ERRORS: &[&::aws_smithy_schema::Schema<'static>] = &[];

/// Descriptor for the `com.aws.example#GetServerStatistics` operation.
pub(crate) static GET_SERVER_STATISTICS: ::aws_smithy_schema::OperationSchema<'static> =
    ::aws_smithy_schema::OperationSchema::new(
        &GET_SERVER_STATISTICS_SHAPE,
        crate::input::GetServerStatisticsInput::SCHEMA,
        crate::output::GetServerStatisticsOutput::SCHEMA,
        GET_SERVER_STATISTICS_ERRORS,
    );
/* ServerSchemaGenerators.kt:97 */
static GET_STORAGE_SHAPE: ::aws_smithy_schema::Schema<'static> = ::aws_smithy_schema::Schema::new(
    ::aws_smithy_schema::ShapeId::from_parts(
        "com.aws.example#GetStorage",
        "com.aws.example",
        "GetStorage",
    ),
    ::aws_smithy_schema::ShapeType::Operation,
)
.with_http(::aws_smithy_schema::traits::HttpTrait::new(
    "GET",
    "/pokedex/{user}",
    Some(200),
));

static GET_STORAGE_ERRORS: &[&::aws_smithy_schema::Schema<'static>] = &[
    crate::error::ResourceNotFoundException::SCHEMA,
    crate::error::StorageAccessNotAuthorized::SCHEMA,
    crate::error::ValidationException::SCHEMA,
];

/// Descriptor for the `com.aws.example#GetStorage` operation.
pub(crate) static GET_STORAGE: ::aws_smithy_schema::OperationSchema<'static> =
    ::aws_smithy_schema::OperationSchema::new(
        &GET_STORAGE_SHAPE,
        crate::input::GetStorageInput::SCHEMA,
        crate::output::GetStorageOutput::SCHEMA,
        GET_STORAGE_ERRORS,
    );
/* ServerSchemaGenerators.kt:97 */
static STREAM_POKEMON_RADIO_SHAPE: ::aws_smithy_schema::Schema<'static> =
    ::aws_smithy_schema::Schema::new(
        ::aws_smithy_schema::ShapeId::from_parts(
            "com.aws.example#StreamPokemonRadio",
            "com.aws.example",
            "StreamPokemonRadio",
        ),
        ::aws_smithy_schema::ShapeType::Operation,
    )
    .with_http(::aws_smithy_schema::traits::HttpTrait::new(
        "GET",
        "/radio",
        Some(200),
    ));

static STREAM_POKEMON_RADIO_ERRORS: &[&::aws_smithy_schema::Schema<'static>] = &[];

/// Descriptor for the `com.aws.example#StreamPokemonRadio` operation.
pub(crate) static STREAM_POKEMON_RADIO: ::aws_smithy_schema::OperationSchema<'static> =
    ::aws_smithy_schema::OperationSchema::new(
        &STREAM_POKEMON_RADIO_SHAPE,
        crate::input::StreamPokemonRadioInput::SCHEMA,
        crate::output::StreamPokemonRadioOutput::SCHEMA,
        STREAM_POKEMON_RADIO_ERRORS,
    );
