// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#![allow(dead_code, unused_imports)]

            pub(crate) use service::POKEMON_SERVICE;

pub(crate) mod operations;

pub(crate) mod service;

pub(crate) mod error;

pub(crate) mod input;

pub(crate) mod model;

pub(crate) mod output;

