#!/usr/bin/env python3
import os
import sys

expected = [os.path.realpath("/tmp"), [
    "-c", "user.name=Some Author",
    "-c", "user.email=author@example.com",
    "commit", "-m", "Test message",
]]
actual = [os.getcwd(), sys.argv[1:]]
if expected != actual:
    print(f"ERROR\nExpect: {expected}\nActual: {actual}")
    sys.exit(1)
