#!/usr/bin/env python3
import os
import sys

expected = [os.path.realpath("/tmp"), [
    "-c", "user.name=some-dev",
    "-c", "user.email=some-email@example.com",
    "merge", "--squash", "test-branch-name"
]]
actual = [os.getcwd(), sys.argv[1:]]
if expected != actual:
    print(f"ERROR\nExpect: {expected}\nActual: {actual}")
    sys.exit(1)
