#!/bin/bash
#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Run by CI to check the canary-lambda
set -e
cd "$(dirname $0)"

cargo test
cargo clippy
