[package]
name = "canary-runner"
version = "0.1.0"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>"]
description = "Tool used to run the canary tests in CI"
edition = "2021"
license = "Apache-2.0"
publish = false

[workspace]

[dependencies]
anyhow = "1"
async-trait = "0.1.74"
aws-config = { version = "1", features = ["behavior-version-latest"] }
aws-sdk-cloudwatch = "1"
aws-sdk-lambda = "1"
aws-sdk-s3 = "1"
base64 = "0.13"
clap = { version = "3.2.17", features = ["derive"] }
hex = "0.4.3"
lazy_static = "1"
octorust = "0.7.0"
regex = "1.11.1"
semver = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha1 = "0.10.1"
smithy-rs-tool-common = { version = "0.1", path = "../../ci-build/smithy-rs-tool-common", features = ["async"] }
tokio = { version = "1.20.1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3.15", features = ["env-filter", "fmt"] }
zip = { version = "0.6.2", default-features = false, features = ["deflate"] }

[dev-dependencies]
pretty_assertions = "1.3"
