[package]
name = "aws-smithy-mocks"
version = "0.1.1"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>"]
description = "Testing utilities for smithy-rs generated clients"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/smithy-lang/smithy-rs"

[dependencies]
aws-smithy-types = { path = "../aws-smithy-types" }
aws-smithy-runtime-api = { path = "../aws-smithy-runtime-api", features = ["client", "http-1x"] }
aws-smithy-http-client = { path = "../aws-smithy-http-client", features = ["test-util"] }
http = "1"

[dev-dependencies]
tokio = { version = "1", features = ["full"]}
aws-smithy-async = { path = "../aws-smithy-async", features = ["rt-tokio"] }
aws-smithy-runtime = { path = "../aws-smithy-runtime", features = ["client"] }

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu"]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
rustdoc-args = ["--cfg", "docsrs"]
# End of docs.rs metadata
