#!/bin/bash
#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0.
#

set -e

if [[ ! -d smithy-rs ]]; then
  echo "A fresh copy of smithy-rs must be checked out from the path this script is executed from." >&2
  exit 1
fi

START_PATH="$(realpath $(pwd))"
rm -rf "${START_PATH}/artifacts"
mkdir -p "${START_PATH}/gradle"

SCRIPT_PATH="$(realpath $(dirname $0))"
cd "${SCRIPT_PATH}"

ACTION_PATH="$(mktemp -d -t smithy-rs-build.XXXXXX)"

cp build.docker-compose.yml "${ACTION_PATH}/"
mkdir -p "${ACTION_PATH}/workspace/artifacts"
cp -r "${START_PATH}/smithy-rs" "${ACTION_PATH}/workspace/smithy-rs"
if [[ -d "${START_PATH}/smithy-rs-target" ]]; then
    mv "${START_PATH}/smithy-rs-target" "${ACTION_PATH}/workspace/smithy-rs/target"
fi
echo "${ACTION_PATH}"
