#!/bin/bash
#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0.
#

set -ue

# Check to see if the original image is available
docker inspect smithy-rs-build-image-original:latest &>/dev/null

# Build a local user version of the image
docker build -t smithy-rs-build-image --file add-local-user.dockerfile --build-arg=USER_ID=$(id -u) .
