#!/bin/bash
#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0.
#

set -ue

SCRIPT_PATH="$(realpath "$(dirname "$0")")"
cd "${SCRIPT_PATH}"

# Check to see if the base image is available
docker inspect smithy-rs-base-image:latest &>/dev/null

# Build a local user version of the image
docker build -t smithy-rs-build-image --file add-local-user.dockerfile --build-arg=USER_ID="$(id -u)" .
