#!/bin/bash
#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#

set -eux

cargo --version
changelogger --version
crate-hasher --version
difftags --version
git --version
java --version
publisher --version
python3 --version
rustc +"${RUST_NIGHTLY_VERSION}" --version
rustc --version
sdk-versioner --version
cargo semver-checks --version
mdbook --version
