#!/bin/bash
#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

set -e
cd "$(dirname "$0")"

cargo clippy
cargo "+${RUST_NIGHTLY_VERSION}" test
