[build]
target = ["wasm32-unknown-unknown", "wasm32-wasip1"]

[target.wasm32-wasi]
rustflags = ["-C", "opt-level=1"]
runner = [
    "wasmtime",
    "-C", "cache=n",
    "-S", "preview2=y",
    "-S", "http=y"
]

# Requires for getrandom crate to compile
# https://docs.rs/getrandom/0.3.3/getrandom/#webassembly-support
[target.wasm32-unknown-unknown]
rustflags = ['--cfg', 'getrandom_backend="wasm_js"']
