#!/bin/bash
#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#

set -eux
cd smithy-rs

# TODO(enableNewSmithyRuntimeCleanup): Only run the orchestrator version of this
./gradlew codegen-client-test:test -Psmithy.runtime.mode=middleware
./gradlew codegen-client-test:test -Psmithy.runtime.mode=orchestrator
