#!/bin/bash
#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#

# This script tests the SDK smoke test services against the orchestrator implementation

C_YELLOW='\033[1;33m'
C_RESET='\033[0m'

set -eu
cd smithy-rs

services_that_pass_tests=(\
    "aws-config"\
    "config"\
    "dynamodb"\
    "ec2"\
    "ecs"\
    "glacier"\
    "iam"\
    "kms"\
    "lambda"\
    "polly"\
    "qldbsession"\
    "route53"\
    "s3"\
    "s3control"\
    "sso"\
    "sts"\
    "timestreamquery"\
    "timestreamwrite"\
    "transcribestreaming"\
)

./gradlew aws:sdk:assemble -Psmithy.runtime.mode=orchestrator

cd aws/sdk/build/aws-sdk/sdk
for service in "${services_that_pass_tests[@]}"; do
    pushd "${service}"
    echo -e "${C_YELLOW}# Running 'cargo test --all-features' on '${service}'${C_RESET}"
    RUSTFLAGS="${RUSTFLAGS:-} --cfg aws_sdk_orchestrator_mode" cargo test --all-features --all-targets --no-fail-fast
    echo -e "${C_YELLOW}# Running 'cargo clippy --all-features' on '${service}'${C_RESET}"
    RUSTFLAGS="${RUSTFLAGS:-} --cfg aws_sdk_orchestrator_mode" cargo clippy --all-features
    popd
done

echo "SUCCESS"
