#!/bin/bash
#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#

C_YELLOW='\033[1;33m'
C_RESET='\033[0m'

set -eux
cd aws-sdk/examples

for example in *; do
    echo -e "${C_YELLOW}Checking examples/${example}...${C_RESET}"
    pushd "${example}" &>/dev/null
    cargo check && cargo clean
    popd &>/dev/null
done
