#!/bin/bash
#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

set -eux
cd smithy-rs/examples

#TODO(https://github.com/smithy-lang/smithy-rs/issues/4303): Remove `cp` when the issue is resolved
cp ../rust-runtime/Cargo.lock .

make test clippy
