#!/bin/bash
#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#

set -eux
cd smithy-rs

sdk-lints check --all
sdk-lints fix --all

# shellcheck disable=SC2046
rustfmt --check --edition 2021 $(find . -name '*.rs' -print | grep -v /target/)

./gradlew -p buildSrc test
./gradlew ktlint
