#!/bin/bash
#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#

set -eux
cd aws-sdk

# Remove examples from workspace since they don't have license metadata
sed -i '/"examples\//d' Cargo.toml

cargo deny --version
cargo deny --all-features check \
  --hide-inclusion-graph \
  --config ../smithy-rs/.cargo-deny-config.toml \
  licenses bans sources
