#!/bin/bash
#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#

set -eux
cd smithy-rs
rm -rf ~/.cargo/registry/cache/
./gradlew aws:sdk-codegen:test
