#!/bin/bash
#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#

set -eux

cd smithy-rs/examples
make
cargo b

cd ..
mdbook test design -L target/debug/deps
