#!/bin/bash
#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#

C_YELLOW='\033[1;33m'
C_RESET='\033[0m'

set -eu
cd smithy-rs

echo -e "## ${C_YELLOW}Running SDK adhoc tests...${C_RESET}"
./gradlew aws:sdk-adhoc-test:clean
./gradlew aws:sdk-adhoc-test:check
