#!/bin/bash
#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#

set -eux
cd aws-sdk

# Check if the $ENABLE_SMOKETESTS environment variable is set
if [ -n "$ENABLE_SMOKETESTS" ]; then
    # Invoking `cargo test` at the root directory implicitly checks for the validity
    # of the top-level `Cargo.toml`
    RUSTFLAGS="--cfg smoketests" cargo test --all-features
else
    cargo test --all-features
fi

for test_dir in tests/*; do
    if [ -f "${test_dir}/Cargo.toml" ]; then
        echo "#### Testing ${test_dir}..."
        cargo test --all-features --manifest-path "${test_dir}/Cargo.toml"
    fi
done
