#!/bin/bash
#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#

set -eux

export RUSTFLAG="--cfg aws_sdk_unstable"

cd smithy-rs

./gradlew codegen-client-test:test
