#!/bin/bash
#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#

set -eux
export RUSTFLAGS="--cfg aws_sdk_unstable"

cd aws-sdk-smoketest
cargo test --all-features
