#!/bin/bash
#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#

# This script tests the SDK smoke test services against the middleware implementation

C_YELLOW='\033[1;33m'
C_RESET='\033[0m'

set -eu
cd smithy-rs

./gradlew aws:sdk:assemble -Psmithy.runtime.mode=middleware

cd aws/sdk/build/aws-sdk/sdk
for service in */; do
    pushd "${service}"
    echo -e "${C_YELLOW}# Running 'cargo test --all-features' on '${service}'${C_RESET}"
    RUSTFLAGS="${RUSTFLAGS:-} --cfg aws_sdk_middleware_mode" cargo test --all-features --all-targets --no-fail-fast
    echo -e "${C_YELLOW}# Running 'cargo clippy --all-features' on '${service}'${C_RESET}"
    RUSTFLAGS="${RUSTFLAGS:-} --cfg aws_sdk_middleware_mode" cargo clippy --all-features
    popd
done

echo "SUCCESS"
