#!/bin/bash
#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#

# This script tests the SDK smoke test services against the orchestrator implementation

C_YELLOW='\033[1;33m'
C_RESET='\033[0m'

set -eu
cd smithy-rs

# TODO(enableNewSmithyRuntime): Move these into `services_that_compile` as more progress is made
services_that_fail_compile=(\
    "s3"\
    "s3control"\
    "transcribestreaming"\
)

# TODO(enableNewSmithyRuntime): Move these into `services_that_pass_tests` as more progress is made
services_that_compile=(\
    "dynamodb"\
    "glacier"\
    "route53"\
    "sts"\
)

services_that_pass_tests=(\
    "config"\
    "ec2"\
    "ecs"\
    "iam"\
    "kms"\
    "lambda"\
    "polly"\
    "qldbsession"\
    "sso"\
)

./gradlew aws:sdk:assemble -Psmithy.runtime.mode=orchestrator

cd aws/sdk/build/aws-sdk/sdk
for service in "${services_that_compile[@]}"; do
    pushd "${service}"
    echo -e "${C_YELLOW}# Running 'cargo check --all-features' on '${service}'${C_RESET}"
    cargo check --all-features
    popd
done

for service in "${services_that_pass_tests[@]}"; do
    pushd "${service}"
    echo -e "${C_YELLOW}# Running 'cargo test --all-features' on '${service}'${C_RESET}"
    cargo test --all-features --no-fail-fast
    popd
done

echo "SUCCESS"
