#!/bin/bash
#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#

set -eux

SMITHY_RS_DIR="$(pwd)/smithy-rs"
ARTIFACTS_DIR="$(pwd)/artifacts/smithy-rs-release"
CHANGELOG_DIR="${SMITHY_RS_DIR}/.changelog"
mkdir -p "${ARTIFACTS_DIR}"

pushd "${SMITHY_RS_DIR}"
# Duplicate AWS SDK changelog entries into a separate file
changelogger split \
    --source "${CHANGELOG_DIR}" \
    --destination aws/SDK_CHANGELOG.next.json
# Render the smithy-rs changelog entries
changelogger render \
    --independent-versioning \
    --change-set smithy-rs \
    --source "${CHANGELOG_DIR}" \
    --source-to-truncate "${CHANGELOG_DIR}" \
    --changelog-output CHANGELOG.md \
    --release-manifest-output "${ARTIFACTS_DIR}"
# Commit changelog changes if there are any
git add .
git diff --staged --quiet || \
    git -c "user.name=AWS SDK Rust Bot" \
        -c "user.email=aws-sdk-rust-primary@amazon.com" \
        commit \
        -am "Update changelog"

echo "Synchronizing the SDK lockfile with runtime lockfiles and with crate dependencies specified in CargoDependency.kt..."
./gradlew aws:sdk:syncAwsSdkLockfile
# Verify that crate dependencies in runtime lockfiles are covered by the updated SDK lockfile
sdk-lockfiles audit
# Commit the updated SDK lockfile
git add aws/sdk/Cargo.lock
git diff --staged --quiet || \
  git -c 'user.name=AWS SDK Rust Bot' \
      -c 'user.email=aws-sdk-rust-primary@amazon.com' \
      commit aws/sdk/Cargo.lock \
      -m "Synchronize the SDK lockfile"

# Generate the crates to publish
./gradlew rust-runtime:assemble
popd

# Move crates into `crates-to-publish` part of the `smithy-rs-release` artifact
mv "${SMITHY_RS_DIR}/rust-runtime/build/smithy-rs/rust-runtime" \
   "${ARTIFACTS_DIR}/crates-to-publish"

# Clone smithy-rs repo changes (changelog updates) into
# the `smithy-rs-release` artifact for push to GitHub
pushd "${ARTIFACTS_DIR}"
git clone "${SMITHY_RS_DIR}"
# Copy over the original remotes so that it's possible to push to `origin`
cp "${SMITHY_RS_DIR}/.git/config" smithy-rs/.git/config
popd
