#!/bin/bash
#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#

set -eux

SMITHY_RS_DIR="$(pwd)/smithy-rs"
ARTIFACTS_DIR="$(pwd)/artifacts/generate-new-changelog-next-toml"

changelogger init > "${SMITHY_RS_DIR}/CHANGELOG.next.toml"

pushd "${ARTIFACTS_DIR}"
cp -r "${SMITHY_RS_DIR}" .
git -C smithy-rs status
popd
