// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub enum AttemptCapturingPokemonEvent {
    #[allow(missing_docs)] // documentation missing in model
    Event(crate::types::CapturingEvent),
    /// The `Unknown` variant represents cases where new union variant was received. Consider upgrading the SDK to the latest available version.
    /// An unknown enum variant
    ///
    /// _Note: If you encounter this error, consider upgrading your SDK to the latest version._
    /// The `Unknown` variant represents cases where the server sent a value that wasn't recognized
    /// by the client. This can happen when the server adds new functionality, but the client has not been updated.
    /// To investigate this, consider turning on debug logging to print the raw HTTP response.
    #[non_exhaustive]
    Unknown,
}
impl AttemptCapturingPokemonEvent {
    #[allow(irrefutable_let_patterns)]
    /// Tries to convert the enum instance into [`Event`](crate::types::AttemptCapturingPokemonEvent::Event), extracting the inner [`CapturingEvent`](crate::types::CapturingEvent).
    /// Returns `Err(&Self)` if it can't be converted.
    pub fn as_event(&self) -> ::std::result::Result<&crate::types::CapturingEvent, &Self> {
        if let AttemptCapturingPokemonEvent::Event(val) = &self {
            ::std::result::Result::Ok(val)
        } else {
            ::std::result::Result::Err(self)
        }
    }
    /// Returns true if this is a [`Event`](crate::types::AttemptCapturingPokemonEvent::Event).
    pub fn is_event(&self) -> bool {
        self.as_event().is_ok()
    }
    /// Returns true if the enum instance is the `Unknown` variant.
    pub fn is_unknown(&self) -> bool {
        matches!(self, Self::Unknown)
    }
}
static ATTEMPTCAPTURINGPOKEMONEVENT_MEMBER_EVENT: ::aws_smithy_schema::Schema<'static> = ::aws_smithy_schema::Schema::new_member(
    ::aws_smithy_schema::ShapeId::from_parts(
        "com.aws.example#AttemptCapturingPokemonEvent$event",
        "com.aws.example",
        "AttemptCapturingPokemonEvent",
    ),
    ::aws_smithy_schema::ShapeType::Structure,
    "event",
    0,
);
static ATTEMPTCAPTURINGPOKEMONEVENT_SCHEMA: ::aws_smithy_schema::Schema<'static> = ::aws_smithy_schema::Schema::new_struct(
    ::aws_smithy_schema::ShapeId::from_parts(
        "com.aws.example#AttemptCapturingPokemonEvent",
        "com.aws.example",
        "AttemptCapturingPokemonEvent",
    ),
    ::aws_smithy_schema::ShapeType::Union,
    &[&ATTEMPTCAPTURINGPOKEMONEVENT_MEMBER_EVENT],
)
.with_streaming();
impl AttemptCapturingPokemonEvent {
    /// The schema for this shape.
    pub const SCHEMA: &'static ::aws_smithy_schema::Schema<'static> = &ATTEMPTCAPTURINGPOKEMONEVENT_SCHEMA;
}
impl ::aws_smithy_schema::serde::SerializableStruct for AttemptCapturingPokemonEvent {
    #[allow(unused_variables, clippy::diverging_sub_expression)]
    fn serialize_members(
        &self,
        ser: &mut dyn ::aws_smithy_schema::serde::ShapeSerializer,
    ) -> ::std::result::Result<(), ::aws_smithy_schema::serde::SerdeError> {
        match self {
            Self::Event(val) => {
                ser.write_struct(&ATTEMPTCAPTURINGPOKEMONEVENT_MEMBER_EVENT, val)?;
            }
            Self::Unknown => return Err(::aws_smithy_schema::serde::SerdeError::custom("cannot serialize unknown union variant")),
        }
        Ok(())
    }
}
impl AttemptCapturingPokemonEvent {
    /// Deserializes this union from a [`ShapeDeserializer`].
    pub fn deserialize(
        deserializer: &mut dyn ::aws_smithy_schema::serde::ShapeDeserializer,
    ) -> ::std::result::Result<Self, ::aws_smithy_schema::serde::SerdeError> {
        let mut result: ::std::option::Option<Self> = ::std::option::Option::None;
        #[allow(unused_variables, unreachable_code, clippy::single_match, clippy::match_single_binding)]
        deserializer.read_struct(&ATTEMPTCAPTURINGPOKEMONEVENT_SCHEMA, &mut |member, deser| {
            result = ::std::option::Option::Some(match member.member_index() {
                Some(0) => Self::Event(crate::types::CapturingEvent::deserialize(deser)?),
                _ => Self::Unknown,
            });
            Ok(())
        })?;
        result.ok_or_else(|| ::aws_smithy_schema::serde::SerdeError::custom("expected a union variant"))
    }
}
