// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// Describes one specific validation failure for an input member.
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct ValidationExceptionField {
    /// A JSONPointer expression to the structure member whose value failed to satisfy the modeled constraints.
    pub path: ::std::string::String,
    /// A detailed description of the validation failure.
    pub message: ::std::string::String,
}
impl ValidationExceptionField {
    /// A JSONPointer expression to the structure member whose value failed to satisfy the modeled constraints.
    pub fn path(&self) -> &str {
        use std::ops::Deref;
        self.path.deref()
    }
    /// A detailed description of the validation failure.
    pub fn message(&self) -> &str {
        use std::ops::Deref;
        self.message.deref()
    }
}
static VALIDATIONEXCEPTIONFIELD_MEMBER_PATH: ::aws_smithy_schema::Schema<'static> = ::aws_smithy_schema::Schema::new_member(
    ::aws_smithy_schema::ShapeId::from_parts(
        "smithy.framework#ValidationExceptionField$path",
        "smithy.framework",
        "ValidationExceptionField",
    ),
    ::aws_smithy_schema::ShapeType::String,
    "path",
    0,
);
static VALIDATIONEXCEPTIONFIELD_MEMBER_MESSAGE: ::aws_smithy_schema::Schema<'static> = ::aws_smithy_schema::Schema::new_member(
    ::aws_smithy_schema::ShapeId::from_parts(
        "smithy.framework#ValidationExceptionField$message",
        "smithy.framework",
        "ValidationExceptionField",
    ),
    ::aws_smithy_schema::ShapeType::String,
    "message",
    1,
);
static VALIDATIONEXCEPTIONFIELD_SCHEMA: ::aws_smithy_schema::Schema<'static> = ::aws_smithy_schema::Schema::new_struct(
    ::aws_smithy_schema::ShapeId::from_parts(
        "smithy.framework#ValidationExceptionField",
        "smithy.framework",
        "ValidationExceptionField",
    ),
    ::aws_smithy_schema::ShapeType::Structure,
    &[&VALIDATIONEXCEPTIONFIELD_MEMBER_PATH, &VALIDATIONEXCEPTIONFIELD_MEMBER_MESSAGE],
);
impl ValidationExceptionField {
    /// The schema for this shape.
    pub const SCHEMA: &'static ::aws_smithy_schema::Schema<'static> = &VALIDATIONEXCEPTIONFIELD_SCHEMA;
}
impl ::aws_smithy_schema::serde::SerializableStruct for ValidationExceptionField {
    #[allow(unused_variables, clippy::diverging_sub_expression)]
    fn serialize_members(
        &self,
        ser: &mut dyn ::aws_smithy_schema::serde::ShapeSerializer,
    ) -> ::std::result::Result<(), ::aws_smithy_schema::serde::SerdeError> {
        {
            let val = &self.path;
            ser.write_string(&VALIDATIONEXCEPTIONFIELD_MEMBER_PATH, val)?;
        }
        {
            let val = &self.message;
            ser.write_string(&VALIDATIONEXCEPTIONFIELD_MEMBER_MESSAGE, val)?;
        }
        Ok(())
    }
}
impl ValidationExceptionField {
    /// Deserializes this structure from a [`ShapeDeserializer`].
    pub fn deserialize(
        deserializer: &mut dyn ::aws_smithy_schema::serde::ShapeDeserializer,
    ) -> ::std::result::Result<Self, ::aws_smithy_schema::serde::SerdeError> {
        #[allow(unused_variables, unused_mut)]
        let mut builder = Self::builder();
        #[allow(
            unused_variables,
            unreachable_code,
            clippy::single_match,
            clippy::match_single_binding,
            clippy::diverging_sub_expression
        )]
        deserializer.read_struct(&VALIDATIONEXCEPTIONFIELD_SCHEMA, &mut |member, deser| {
            match member.member_index() {
                Some(0) => {
                    builder.path = Some(deser.read_string(member)?);
                }
                Some(1) => {
                    builder.message = Some(deser.read_string(member)?);
                }
                _ => {}
            }
            Ok(())
        })?;
        builder.path = builder.path.or(Some(String::new()));
        builder.message = builder.message.or(Some(String::new()));
        builder.build().map_err(|e| aws_smithy_schema::serde::SerdeError::custom(e.to_string()))
    }
}
impl ValidationExceptionField {
    /// Deserializes this structure from a body deserializer and HTTP response.
    pub fn deserialize_with_response(
        deserializer: &mut dyn ::aws_smithy_schema::serde::ShapeDeserializer,
        _headers: &::aws_smithy_runtime_api::http::Headers,
        _status: u16,
        _body: &[u8],
    ) -> ::std::result::Result<Self, ::aws_smithy_schema::serde::SerdeError> {
        Self::deserialize(deserializer)
    }
}
impl ValidationExceptionField {
    /// Creates a new builder-style object to manufacture [`ValidationExceptionField`](crate::types::ValidationExceptionField).
    pub fn builder() -> crate::types::builders::ValidationExceptionFieldBuilder {
        crate::types::builders::ValidationExceptionFieldBuilder::default()
    }
}

/// A builder for [`ValidationExceptionField`](crate::types::ValidationExceptionField).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct ValidationExceptionFieldBuilder {
    pub(crate) path: ::std::option::Option<::std::string::String>,
    pub(crate) message: ::std::option::Option<::std::string::String>,
}
impl ValidationExceptionFieldBuilder {
    /// A JSONPointer expression to the structure member whose value failed to satisfy the modeled constraints.
    /// This field is required.
    pub fn path(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.path = ::std::option::Option::Some(input.into());
        self
    }
    /// A JSONPointer expression to the structure member whose value failed to satisfy the modeled constraints.
    pub fn set_path(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.path = input;
        self
    }
    /// A JSONPointer expression to the structure member whose value failed to satisfy the modeled constraints.
    pub fn get_path(&self) -> &::std::option::Option<::std::string::String> {
        &self.path
    }
    /// A detailed description of the validation failure.
    /// This field is required.
    pub fn message(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.message = ::std::option::Option::Some(input.into());
        self
    }
    /// A detailed description of the validation failure.
    pub fn set_message(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.message = input;
        self
    }
    /// A detailed description of the validation failure.
    pub fn get_message(&self) -> &::std::option::Option<::std::string::String> {
        &self.message
    }
    /// Consumes the builder and constructs a [`ValidationExceptionField`](crate::types::ValidationExceptionField).
    /// This method will fail if any of the following fields are not set:
    /// - [`path`](crate::types::builders::ValidationExceptionFieldBuilder::path)
    /// - [`message`](crate::types::builders::ValidationExceptionFieldBuilder::message)
    pub fn build(self) -> ::std::result::Result<crate::types::ValidationExceptionField, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(crate::types::ValidationExceptionField {
            path: self.path.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "path",
                    "path was not specified but it is required when building ValidationExceptionField",
                )
            })?,
            message: self.message.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "message",
                    "message was not specified but it is required when building ValidationExceptionField",
                )
            })?,
        })
    }
}
