// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#![allow(dead_code)]
static GETSERVERSTATISTICSOUTPUT_MEMBER_CALLS_COUNT: ::aws_smithy_schema::Schema<'static> = ::aws_smithy_schema::Schema::new_member(
                            ::aws_smithy_schema::ShapeId::from_parts(
                                "com.aws.example.synthetic#GetServerStatisticsOutput$calls_count",
                                "com.aws.example.synthetic",
                                "GetServerStatisticsOutput",
                            ),
                            ::aws_smithy_schema::ShapeType::Long,
                            "calls_count",
                            0,
                        );
static GETSERVERSTATISTICSOUTPUT_SCHEMA: ::aws_smithy_schema::Schema<'static> = ::aws_smithy_schema::Schema::new_struct(
                            ::aws_smithy_schema::ShapeId::from_parts("com.aws.example.synthetic#GetServerStatisticsOutput", "com.aws.example.synthetic", "GetServerStatisticsOutput"),
                            ::aws_smithy_schema::ShapeType::Structure,
                            &[&GETSERVERSTATISTICSOUTPUT_MEMBER_CALLS_COUNT],
                        )
    .with_http(aws_smithy_schema::traits::HttpTrait::new("GET", "/stats", None))
    .with_original_name("GetServerStatisticsOutput");
impl crate::output::GetServerStatisticsOutput {
                /// The schema for this shape.
                pub const SCHEMA: &'static ::aws_smithy_schema::Schema<'static> = &GETSERVERSTATISTICSOUTPUT_SCHEMA;
            }
impl ::aws_smithy_schema::serde::SerializableStruct for crate::output::GetServerStatisticsOutput {
                #[allow(unused_variables, clippy::diverging_sub_expression)]
                fn serialize_members(&self, ser: &mut dyn ::aws_smithy_schema::serde::ShapeSerializer) -> ::std::result::Result<(), ::aws_smithy_schema::serde::SerdeError> {
                    {
                                let val = &self.calls_count;
                                ser.write_long(&GETSERVERSTATISTICSOUTPUT_MEMBER_CALLS_COUNT, *val)?;
                            }
                    Ok(())
                }
            }
#[allow(clippy::needless_question_mark)]
            pub(crate) fn deser_get_server_statistics_output(
                deserializer: &mut dyn ::aws_smithy_schema::serde::ShapeDeserializer,
            ) -> ::std::result::Result<crate::output::get_server_statistics_output::Builder, ::aws_smithy_schema::serde::SerdeError> {
                #[allow(unused_mut)]
                let mut builder = crate::output::get_server_statistics_output::Builder::default();
                #[allow(unused_variables, unreachable_code, clippy::single_match, clippy::match_single_binding)]
                deserializer.read_struct(&GETSERVERSTATISTICSOUTPUT_SCHEMA, &mut |member, deser| {
                    match member.member_index() {

                Some(0) => {
                    if deser.is_null() { deser.read_null()?; } else {
                        builder = ::std::mem::take(&mut builder).calls_count(deser.read_long(member)?);
                    }
                }

                        _ => {}
                    }
                    Ok(())
                })?;

                Ok(builder)
            }

