[package]
name = "aws-smithy-types-convert"
version = "0.60.9"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>"]
description = "Conversion of types from aws-smithy-types to other libraries."
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/smithy-lang/smithy-rs"

[features]
convert-chrono = ["aws-smithy-types", "chrono"]
convert-time = ["aws-smithy-types", "time"]
convert-streams = ["aws-smithy-async", "futures-core"]

[dependencies]
aws-smithy-types = { path = "../aws-smithy-types", optional = true }
aws-smithy-async = { path = "../aws-smithy-async", optional = true }
chrono = { version = "0.4.35", optional = true, default-features = false, features = ["std"] }
time = { version = "0.3.4", optional = true }
futures-core = { version = "0.3.31", optional = true }

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu"]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
rustdoc-args = ["--cfg", "docsrs"]
# End of docs.rs metadata
