[package]
name = "aws-smithy-xml"
version = "0.60.10"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>", "Russell Cohen <rcoh@amazon.com>"]
description = "XML parsing logic for Smithy protocols."
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/smithy-lang/smithy-rs"

[dependencies]
xmlparser = "0.13.5"

[dev-dependencies]
aws-smithy-protocol-test = { path = "../aws-smithy-protocol-test" }
base64 = "0.13.0"
proptest = "1"

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu"]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
rustdoc-args = ["--cfg", "docsrs"]
# End of docs.rs metadata
