// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#![allow(dead_code)]
static GET_POKEMON_SPECIES_INPUT_MEMBER_NAME: ::aws_smithy_schema::Schema<'static> =
    ::aws_smithy_schema::Schema::new_member(
        ::aws_smithy_schema::ShapeId::from_parts(
            "com.aws.example.synthetic#GetPokemonSpeciesInput$name",
            "com.aws.example.synthetic",
            "GetPokemonSpeciesInput",
        ),
        ::aws_smithy_schema::ShapeType::String,
        "name",
        0,
    )
    .with_http_label();
static GET_POKEMON_SPECIES_INPUT_SCHEMA: ::aws_smithy_schema::Schema<'static> =
    ::aws_smithy_schema::Schema::new_struct(
        ::aws_smithy_schema::ShapeId::from_parts(
            "com.aws.example.synthetic#GetPokemonSpeciesInput",
            "com.aws.example.synthetic",
            "GetPokemonSpeciesInput",
        ),
        ::aws_smithy_schema::ShapeType::Structure,
        &[&GET_POKEMON_SPECIES_INPUT_MEMBER_NAME],
    )
    .with_http(aws_smithy_schema::traits::HttpTrait::new(
        "GET",
        "/pokemon-species/{name}",
        None,
    ))
    .with_no_body_members()
    .with_original_name("GetPokemonSpeciesInput");
pub(crate) const GET_POKEMON_SPECIES_INPUT: &'static ::aws_smithy_schema::Schema<'static> =
    &GET_POKEMON_SPECIES_INPUT_SCHEMA;
