#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#

[package]
name = "stub"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
aws-config = {path = "../../../aws/sdk/build/aws-sdk/sdk/aws-config", features = ["client-hyper"] }
aws-credential-types = { path = "../../../aws/sdk/build/aws-sdk/sdk/aws-credential-types", features = ["hardcoded-credentials"] }
aws-sdk-sts = { path = "../../../aws/sdk/build/aws-sdk/sdk/sts" }
aws-smithy-http-client = { path = "../../../aws/sdk/build/aws-sdk/sdk/aws-smithy-http-client", features = ["rustls-aws-lc"] }
exitcode = "1"
tokio = { version = "1", features = ["full"] }
rustls = "0.23.23"
rustls-pemfile = "1"
x509-parser = "0.17"
