// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#![allow(dead_code)]
static ATTEMPT_CAPTURING_POKEMON_EVENT_MEMBER_EVENT: ::aws_smithy_schema::Schema<'static> = ::aws_smithy_schema::Schema::new_member(
                            ::aws_smithy_schema::ShapeId::from_parts(
                                "com.aws.example#AttemptCapturingPokemonEvent$event",
                                "com.aws.example",
                                "AttemptCapturingPokemonEvent",
                            ),
                            ::aws_smithy_schema::ShapeType::Structure,
                            "event",
                            0,
                        );
static ATTEMPT_CAPTURING_POKEMON_EVENT_SCHEMA: ::aws_smithy_schema::Schema<'static> = ::aws_smithy_schema::Schema::new_struct(
                            ::aws_smithy_schema::ShapeId::from_parts("com.aws.example#AttemptCapturingPokemonEvent", "com.aws.example", "AttemptCapturingPokemonEvent"),
                            ::aws_smithy_schema::ShapeType::Union,
                            &[&ATTEMPT_CAPTURING_POKEMON_EVENT_MEMBER_EVENT],
                        )
    .with_streaming();
pub(crate) const ATTEMPT_CAPTURING_POKEMON_EVENT: &'static ::aws_smithy_schema::Schema<'static> =
                        &ATTEMPT_CAPTURING_POKEMON_EVENT_SCHEMA;

