// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#![allow(dead_code)]
static CHECKHEALTHINPUT_SCHEMA: ::aws_smithy_schema::Schema<'static> =
    ::aws_smithy_schema::Schema::new_struct(
        ::aws_smithy_schema::ShapeId::from_parts(
            "com.aws.example.synthetic#CheckHealthInput",
            "com.aws.example.synthetic",
            "CheckHealthInput",
        ),
        ::aws_smithy_schema::ShapeType::Structure,
        &[],
    )
    .with_http(aws_smithy_schema::traits::HttpTrait::new(
        "GET", "/ping", None,
    ))
    .with_no_body_members();
impl crate::input::CheckHealthInput {
    /// The schema for this shape.
    pub const SCHEMA: &'static ::aws_smithy_schema::Schema<'static> = &CHECKHEALTHINPUT_SCHEMA;
}
impl ::aws_smithy_schema::serde::SerializableStruct for crate::input::CheckHealthInput {
    #[allow(unused_variables, clippy::diverging_sub_expression)]
    fn serialize_members(
        &self,
        ser: &mut dyn ::aws_smithy_schema::serde::ShapeSerializer,
    ) -> ::std::result::Result<(), ::aws_smithy_schema::serde::SerdeError> {
        Ok(())
    }
}
#[allow(clippy::needless_question_mark)]
pub(crate) fn deser_check_health_input(
    deserializer: &mut dyn ::aws_smithy_schema::serde::ShapeDeserializer,
) -> ::std::result::Result<crate::input::CheckHealthInput, ::aws_smithy_schema::serde::SerdeError> {
    #[allow(unused_mut)]
    let mut builder = crate::input::check_health_input::Builder::default();
    #[allow(
        unused_variables,
        unreachable_code,
        clippy::single_match,
        clippy::match_single_binding
    )]
    deserializer.read_struct(&CHECKHEALTHINPUT_SCHEMA, &mut |member, deser| {
        match member.member_index() {
            _ => {}
        }
        Ok(())
    })?;

    Ok(builder.build())
}
impl ::aws_smithy_http_server::deserialize::DeserializableShape for crate::input::CheckHealthInput {
    fn deserialize(
        deserializer: &mut dyn ::aws_smithy_schema::serde::ShapeDeserializer,
    ) -> ::std::result::Result<Self, ::aws_smithy_http_server::deserialize::DeserializeError> {
        Ok(deser_check_health_input(deserializer)?)
    }
}
