[package]
name = "aws-smithy-observability"
version = "0.1.0"
authors = [
  "AWS Rust SDK Team <aws-sdk-rust@amazon.com>",
]
description = "Smithy observability implementation."
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/awslabs/smithy-rs"

[dependencies]
aws-smithy-runtime-api = { path = "../aws-smithy-runtime-api" }
once_cell = "1.19.0"

[dev-dependencies]
serial_test = "3.1.1"


[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu"]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
rustdoc-args = ["--cfg", "docsrs"]
# End of docs.rs metadata
