# This Cargo.toml is unused in generated code. It exists solely to enable these tests to compile in-situ
[package]
name = "metrics-tests"
version = "0.1.0"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/smithy-lang/smithy-rs"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
aws-config = { path = "../../build/aws-sdk/sdk/aws-config", features = ["test-util", "behavior-version-latest"] }
aws-sdk-dynamodb = { path = "../../build/aws-sdk/sdk/dynamodb", features = ["test-util", "behavior-version-latest"] }
aws-sdk-s3 = { path = "../../build/aws-sdk/sdk/s3", features = ["test-util", "behavior-version-latest"] }
aws-smithy-observability = { path = "../../build/aws-sdk/sdk/aws-smithy-observability" }
aws-smithy-observability-otel = { path = "../../build/aws-sdk/sdk/aws-smithy-observability-otel" }
aws-smithy-runtime = { path = "../../build/aws-sdk/sdk/aws-smithy-runtime", features = ["client", "test-util"]}
aws-smithy-types = { path = "../../build/aws-sdk/sdk/aws-smithy-types" }
http = "0.2.0"
opentelemetry = { version = "0.26.0", features = ["metrics"] }
opentelemetry_sdk = { version = "0.26.0", features = ["metrics", "testing"] }
serial_test = "3.1.1"
tokio = { version = "1.23.1", features = ["full", "test-util"] }
