// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct MasterBallUnsuccessful {
    #[allow(missing_docs)] // documentation missing in model
    pub message: ::std::option::Option<::std::string::String>,
    pub(crate) meta: ::aws_smithy_types::error::ErrorMetadata,
}
static MASTERBALLUNSUCCESSFUL_MEMBER_MESSAGE: ::aws_smithy_schema::Schema<'static> = ::aws_smithy_schema::Schema::new_member(
    ::aws_smithy_schema::ShapeId::from_parts(
        "com.aws.example#MasterBallUnsuccessful$message",
        "com.aws.example",
        "MasterBallUnsuccessful",
    ),
    ::aws_smithy_schema::ShapeType::String,
    "message",
    0,
);
static MASTERBALLUNSUCCESSFUL_SCHEMA: ::aws_smithy_schema::Schema<'static> = ::aws_smithy_schema::Schema::new_struct(
    ::aws_smithy_schema::ShapeId::from_parts("com.aws.example#MasterBallUnsuccessful", "com.aws.example", "MasterBallUnsuccessful"),
    ::aws_smithy_schema::ShapeType::Structure,
    &[&MASTERBALLUNSUCCESSFUL_MEMBER_MESSAGE],
);
impl MasterBallUnsuccessful {
    /// The schema for this shape.
    pub const SCHEMA: &'static ::aws_smithy_schema::Schema<'static> = &MASTERBALLUNSUCCESSFUL_SCHEMA;
}
impl ::aws_smithy_schema::serde::SerializableStruct for MasterBallUnsuccessful {
    #[allow(unused_variables, clippy::diverging_sub_expression)]
    fn serialize_members(
        &self,
        ser: &mut dyn ::aws_smithy_schema::serde::ShapeSerializer,
    ) -> ::std::result::Result<(), ::aws_smithy_schema::serde::SerdeError> {
        if let Some(ref val) = self.message {
            ser.write_string(&MASTERBALLUNSUCCESSFUL_MEMBER_MESSAGE, val)?;
        }
        Ok(())
    }
}
impl MasterBallUnsuccessful {
    /// Deserializes this structure from a [`ShapeDeserializer`].
    pub fn deserialize(
        deserializer: &mut dyn ::aws_smithy_schema::serde::ShapeDeserializer,
    ) -> ::std::result::Result<Self, ::aws_smithy_schema::serde::SerdeError> {
        #[allow(unused_variables, unused_mut)]
        let mut builder = Self::builder();
        #[allow(
            unused_variables,
            unreachable_code,
            clippy::single_match,
            clippy::match_single_binding,
            clippy::diverging_sub_expression
        )]
        deserializer.read_struct(&MASTERBALLUNSUCCESSFUL_SCHEMA, &mut |member, deser| {
            match member.member_index() {
                Some(0) => {
                    if deser.is_null() {
                        deser.read_null()?;
                    } else {
                        builder.message = Some(deser.read_string(member)?);
                    }
                }
                _ => {}
            }
            Ok(())
        })?;
        Ok(builder.build())
    }
}
impl MasterBallUnsuccessful {
    /// Deserializes this structure from a body deserializer and HTTP response.
    pub fn deserialize_with_response(
        deserializer: &mut dyn ::aws_smithy_schema::serde::ShapeDeserializer,
        _headers: &::aws_smithy_runtime_api::http::Headers,
        _status: u16,
        body: &[u8],
    ) -> ::std::result::Result<Self, ::aws_smithy_schema::serde::SerdeError> {
        if body.is_empty() {
            return Ok(Self::builder().build());
        }
        Self::deserialize(deserializer)
    }
}
impl MasterBallUnsuccessful {
    /// Returns the error message.
    pub fn message(&self) -> ::std::option::Option<&str> {
        self.message.as_deref()
    }
}
impl ::std::fmt::Display for MasterBallUnsuccessful {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        ::std::write!(f, "MasterBallUnsuccessful")?;
        if let ::std::option::Option::Some(inner_1) = &self.message {
            {
                ::std::write!(f, ": {inner_1}")?;
            }
        }
        Ok(())
    }
}
impl ::std::error::Error for MasterBallUnsuccessful {}
impl ::aws_smithy_types::error::metadata::ProvideErrorMetadata for MasterBallUnsuccessful {
    fn meta(&self) -> &::aws_smithy_types::error::ErrorMetadata {
        &self.meta
    }
}
impl MasterBallUnsuccessful {
    /// Creates a new builder-style object to manufacture [`MasterBallUnsuccessful`](crate::types::error::MasterBallUnsuccessful).
    pub fn builder() -> crate::types::error::builders::MasterBallUnsuccessfulBuilder {
        crate::types::error::builders::MasterBallUnsuccessfulBuilder::default()
    }
}

/// A builder for [`MasterBallUnsuccessful`](crate::types::error::MasterBallUnsuccessful).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct MasterBallUnsuccessfulBuilder {
    pub(crate) message: ::std::option::Option<::std::string::String>,
    meta: std::option::Option<::aws_smithy_types::error::ErrorMetadata>,
}
impl MasterBallUnsuccessfulBuilder {
    #[allow(missing_docs)] // documentation missing in model
    pub fn message(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.message = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_message(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.message = input;
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_message(&self) -> &::std::option::Option<::std::string::String> {
        &self.message
    }
    /// Sets error metadata
    pub fn meta(mut self, meta: ::aws_smithy_types::error::ErrorMetadata) -> Self {
        self.meta = Some(meta);
        self
    }

    /// Sets error metadata
    pub fn set_meta(&mut self, meta: std::option::Option<::aws_smithy_types::error::ErrorMetadata>) -> &mut Self {
        self.meta = meta;
        self
    }
    /// Consumes the builder and constructs a [`MasterBallUnsuccessful`](crate::types::error::MasterBallUnsuccessful).
    pub fn build(self) -> crate::types::error::MasterBallUnsuccessful {
        crate::types::error::MasterBallUnsuccessful {
            message: self.message,
            meta: self.meta.unwrap_or_default(),
        }
    }
}
