[package]
name = "sdk-lockfiles"
version = "0.1.3"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>"]
description = """
A CLI tool to audit lockfiles for Smithy runtime crates, AWS runtime crates, `aws-config`, and the workspace containing
SDK crates
"""
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
anyhow = "1.0.87"
cargo-lock = { version = "9.0.0", features = ["dependency-tree"] }
clap = { version = "4.4.11", features = ["derive", "env"] }
petgraph = "0.6.5"
smithy-rs-tool-common = { path = "../smithy-rs-tool-common" }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

[dev-dependencies]
itertools = "0.13.0"
tracing-test = "0.2.4"
