# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

name: 'Free Disk Space'
description: 'Free up disk space on GitHub Actions runners'
runs:
  using: 'composite'
  steps:
    - name: Free up disk space
      shell: bash
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
