/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

//! A model plugin that makes operation metadata available to handlers through task-local storage.

use std::{
    convert::Infallible,
    task::{Context, Poll},
    time::Instant,
};

use http::request::Parts;
use pokemon_service_server_sdk::server::{
    operation::OperationShape,
    plugin::{ModelMarker, Plugin},
    request::FromParts,
    shape_id::ShapeId,
};
use tokio::task::futures::TaskLocalFuture;
use tower::Service;

/// Metadata created for each request to a modeled operation.
#[derive(Clone, Debug)]
pub struct MiddlewareData {
    /// The operation handling the request.
    pub operation: ShapeId,
    /// A unique ID generated by this middleware for the request.
    pub request_id: String,
    /// The instant at which the modeled operation began processing the request.
    pub started_at: Instant,
}

tokio::task_local! {
    static MIDDLEWARE_DATA: MiddlewareData;
}

/// Handler extractor for metadata supplied by [`MiddlewareDataPlugin`].
///
/// Extraction itself never fails. [`MiddlewareExt::data`] returns `None` when the handler is
/// invoked without the plugin installed.
#[derive(Debug)]
pub struct MiddlewareExt(());

impl MiddlewareExt {
    /// Returns a clone of the current request's middleware data.
    pub fn data(&self) -> Option<MiddlewareData> {
        MIDDLEWARE_DATA.try_with(Clone::clone).ok()
    }

    /// Borrows the current request's middleware data for the duration of `f`.
    pub fn with<R>(&self, f: impl FnOnce(&MiddlewareData) -> R) -> Option<R> {
        MIDDLEWARE_DATA.try_with(f).ok()
    }
}

impl<P> FromParts<P> for MiddlewareExt {
    type Rejection = Infallible;

    fn from_parts(_parts: &mut Parts) -> Result<Self, Self::Rejection> {
        Ok(Self(()))
    }
}

/// Model plugin that installs [`MiddlewareData`] for the lifetime of each operation future.
#[derive(Clone, Copy, Debug, Default)]
pub struct MiddlewareDataPlugin;

impl ModelMarker for MiddlewareDataPlugin {}

impl<Ser, Op, T> Plugin<Ser, Op, T> for MiddlewareDataPlugin
where
    Op: OperationShape,
{
    type Output = MiddlewareDataService<T>;

    fn apply(&self, inner: T) -> Self::Output {
        MiddlewareDataService {
            inner,
            operation: Op::ID,
        }
    }
}

/// Service installed by [`MiddlewareDataPlugin`].
#[derive(Clone, Debug)]
pub struct MiddlewareDataService<S> {
    inner: S,
    operation: ShapeId,
}

impl<Input, Exts, S> Service<(Input, Exts)> for MiddlewareDataService<S>
where
    S: Service<(Input, Exts)>,
{
    type Response = S::Response;
    type Error = S::Error;
    type Future = TaskLocalFuture<MiddlewareData, S::Future>;

    fn poll_ready(&mut self, cx: &mut Context<'_>) -> Poll<Result<(), Self::Error>> {
        self.inner.poll_ready(cx)
    }

    fn call(&mut self, req: (Input, Exts)) -> Self::Future {
        let data = MiddlewareData {
            operation: self.operation.clone(),
            request_id: uuid::Uuid::new_v4().to_string(),
            started_at: Instant::now(),
        };
        MIDDLEWARE_DATA.scope(data, self.inner.call(req))
    }
}
