// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::fmt::Debug)]
pub struct CapturePokemonInput  {
    #[allow(missing_docs)] // documentation missing in model
    pub events: ::aws_smithy_http::event_stream::EventStreamSender<crate::types::AttemptCapturingPokemonEvent, crate::types::error::AttemptCapturingPokemonEventError>,
}
impl  CapturePokemonInput  {
    #[allow(missing_docs)] // documentation missing in model
    pub fn events(&self) -> &::aws_smithy_http::event_stream::EventStreamSender<crate::types::AttemptCapturingPokemonEvent, crate::types::error::AttemptCapturingPokemonEventError> {
        &self.events
    }
}
static CAPTUREPOKEMONINPUT_MEMBER_EVENTS: ::aws_smithy_schema::Schema<'static> = ::aws_smithy_schema::Schema::new_member(
                            ::aws_smithy_schema::ShapeId::from_parts(
                                "com.aws.example.synthetic#CapturePokemonInput$events",
                                "com.aws.example.synthetic",
                                "CapturePokemonInput",
                            ),
                            ::aws_smithy_schema::ShapeType::Union,
                            "events",
                            0,
                        );
static CAPTUREPOKEMONINPUT_SCHEMA: ::aws_smithy_schema::Schema<'static> = ::aws_smithy_schema::Schema::new_struct(
                            ::aws_smithy_schema::ShapeId::from_parts("com.aws.example.synthetic#CapturePokemonInput", "com.aws.example.synthetic", "CapturePokemonInput"),
                            ::aws_smithy_schema::ShapeType::Structure,
                            &[&CAPTUREPOKEMONINPUT_MEMBER_EVENTS],
                        )
    .with_original_name("CapturePokemonInput");
impl CapturePokemonInput {
                /// The schema for this shape.
                pub const SCHEMA: &'static ::aws_smithy_schema::Schema<'static> = &CAPTUREPOKEMONINPUT_SCHEMA;
            }
impl ::aws_smithy_schema::serde::SerializableStruct for CapturePokemonInput {
                #[allow(unused_variables, clippy::diverging_sub_expression)]
                fn serialize_members(&self, ser: &mut dyn ::aws_smithy_schema::serde::ShapeSerializer) -> ::std::result::Result<(), ::aws_smithy_schema::serde::SerdeError> {

                    Ok(())
                }
            }
impl CapturePokemonInput {
                /// Deserializes this structure from a [`ShapeDeserializer`].
                pub fn deserialize(deserializer: &mut dyn ::aws_smithy_schema::serde::ShapeDeserializer) -> ::std::result::Result<Self, ::aws_smithy_schema::serde::SerdeError> {
                    #[allow(unused_variables, unused_mut)]
                    let mut builder = Self::builder();
                    #[allow(unused_variables, unreachable_code, clippy::single_match, clippy::match_single_binding, clippy::diverging_sub_expression)]
                    deserializer.read_struct(&CAPTUREPOKEMONINPUT_SCHEMA, &mut |member, deser| {
                        match member.member_index() {
                            Some(0) => { builder.events = Some({ let _ = member; todo!("deserialize streaming union") }); }
                            _ => {}
                        }
                        Ok(())
                    })?;
                    builder.build().map_err(|e| aws_smithy_schema::serde::SerdeError::custom(e.to_string()))
                }
            }
impl CapturePokemonInput {
                        /// Deserializes this structure from a body deserializer and HTTP response.
                        pub fn deserialize_with_response(
                            deserializer: &mut dyn ::aws_smithy_schema::serde::ShapeDeserializer,
                            _headers: &::aws_smithy_runtime_api::http::Headers,
                            _status: u16,
                            _body: &[u8],
                        ) -> ::std::result::Result<Self, ::aws_smithy_schema::serde::SerdeError> {

                            Self::deserialize(deserializer)
                        }
                    }
impl CapturePokemonInput {
    /// Creates a new builder-style object to manufacture [`CapturePokemonInput`](crate::operation::capture_pokemon::CapturePokemonInput).
    pub fn builder() -> crate::operation::capture_pokemon::builders::CapturePokemonInputBuilder {
        crate::operation::capture_pokemon::builders::CapturePokemonInputBuilder::default()
    }
    #[allow(unused)]
    pub(crate) fn into_builder(self) -> crate::operation::capture_pokemon::builders::CapturePokemonInputBuilder {
        Self::builder()
        .events(self.events)
    }
}

/// A builder for [`CapturePokemonInput`](crate::operation::capture_pokemon::CapturePokemonInput).
#[derive(::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct CapturePokemonInputBuilder {
    pub(crate) events: ::std::option::Option<::aws_smithy_http::event_stream::EventStreamSender<crate::types::AttemptCapturingPokemonEvent, crate::types::error::AttemptCapturingPokemonEventError>>,
}
impl CapturePokemonInputBuilder {
    #[allow(missing_docs)] // documentation missing in model
    pub fn events(mut self, input: ::aws_smithy_http::event_stream::EventStreamSender<crate::types::AttemptCapturingPokemonEvent, crate::types::error::AttemptCapturingPokemonEventError>) -> Self {
        self.events = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_events(mut self, input: ::std::option::Option<::aws_smithy_http::event_stream::EventStreamSender<crate::types::AttemptCapturingPokemonEvent, crate::types::error::AttemptCapturingPokemonEventError>>) -> Self {
        self.events = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_events(&self) -> &::std::option::Option<::aws_smithy_http::event_stream::EventStreamSender<crate::types::AttemptCapturingPokemonEvent, crate::types::error::AttemptCapturingPokemonEventError>> {
        &self.events
    }
    /// Consumes the builder and constructs a [`CapturePokemonInput`](crate::operation::capture_pokemon::CapturePokemonInput).
    /// This method will fail if any of the following fields are not set:
    /// - [`events`](crate::operation::capture_pokemon::builders::CapturePokemonInputBuilder::events)
    pub fn build(self) -> ::std::result::Result<crate::operation::capture_pokemon::CapturePokemonInput, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(
            crate::operation::capture_pokemon::CapturePokemonInput {
                events: self.events
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("events", "events was not specified but it is required when building CapturePokemonInput")
                    )?
                ,
            }
        )
    }
}

