#!/usr/bin/env python3
#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#
# This script is a fake `./gradlew aws:sdk:assemble` stand-in for the fake smithy-rs
# repository created by `create-test-workspace`.
#

import sys
import subprocess
import shlex


def get_cmd_output(command):
    result = subprocess.run(shlex.split(command), capture_output=True, check=True)
    return result.stdout.decode("utf-8").strip()


def get_examples_revision():
    for arg in sys.argv:
        prefix = "-Paws.sdk.examples.revision="
        if arg.startswith(prefix):
            return arg[len(prefix):]
    return None


examples_revision = get_examples_revision()
smithy_rs_revision = get_cmd_output("git rev-parse HEAD")

# Emulate generating the versions.toml
with open("aws/sdk/build/aws-sdk/versions.toml", "w") as versions:
    print(f"smithy_rs_revision = \"{smithy_rs_revision}\"", file=versions)
    print(f"aws_doc_sdk_examples_revision = \"{examples_revision}\"", file=versions)

# Emulate generating code from the models by just copying the model into the build artifacts.
# The model doesn't get copied like this in reality, but this is an easy way to fake it.
subprocess.run(shlex.split("cp aws/sdk/aws-models/s3.json aws/sdk/build/aws-sdk/sdk/s3/"), check=True)

# Emulate copying the examples into the build output
subprocess.run(shlex.split("cp -r aws/sdk/examples aws/sdk/build/aws-sdk/"), check=True)
