// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
/* JsonSerializerGenerator.kt:215 */
pub fn ser_master_ball_unsuccessful_error(
    value: &crate::error::MasterBallUnsuccessful,
) -> ::std::result::Result<String, ::aws_smithy_types::error::operation::SerializationError> {
    /* JsonSerializerGenerator.kt:220 */
    let mut out = ::std::string::String::new();
    let mut object = ::aws_smithy_json::serialize::JsonObjectWriter::new(&mut out);
    /* JsonSerializerGenerator.kt:377 */
    crate::protocol_rest_json1::protocol_serde::shape_master_ball_unsuccessful::ser_master_ball_unsuccessful(&mut object, value)?;
    /* JsonSerializerGenerator.kt:229 */
    object.finish();
    Ok(out)
    /* JsonSerializerGenerator.kt:215 */
}

/* JsonSerializerGenerator.kt:360 */
pub fn ser_master_ball_unsuccessful(
    object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
    input: &crate::error::MasterBallUnsuccessful,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    /* JsonSerializerGenerator.kt:384 */
    if let Some(var_1) = &input.message {
        /* JsonSerializerGenerator.kt:425 */
        object.key("message").string(var_1.as_str());
        /* JsonSerializerGenerator.kt:384 */
    }
    /* JsonSerializerGenerator.kt:374 */
    Ok(())
    /* JsonSerializerGenerator.kt:360 */
}

/* JsonParserGenerator.kt:163 */
pub(crate) fn de_master_ball_unsuccessful_json_err(
    _value: &[u8],
    mut builder: crate::error::master_ball_unsuccessful::Builder,
) -> ::std::result::Result<
    crate::error::master_ball_unsuccessful::Builder,
    ::aws_smithy_json::deserialize::error::DeserializeError,
> {
    /* JsonParserGenerator.kt:170 */
    let mut tokens_owned = ::aws_smithy_json::deserialize::json_token_iter(
        crate::protocol_rest_json1::protocol_serde::or_empty_doc(_value),
    )
    .peekable();
    let tokens = &mut tokens_owned;
    #[allow(unused_variables)]
    let depth = 0u32;
    ::aws_smithy_json::deserialize::token::expect_start_object(tokens.next())?;
    /* JsonParserGenerator.kt:753 */
    loop {
        /* JsonParserGenerator.kt:754 */
        match tokens.next().transpose()? {
            /* JsonParserGenerator.kt:755 */
            Some(::aws_smithy_json::deserialize::Token::EndObject { .. }) => break,
            Some(::aws_smithy_json::deserialize::Token::ObjectKey { key, .. }) => {
                /* JsonParserGenerator.kt:281 */
                match key.to_unescaped()?.as_ref() {
                    /* JsonParserGenerator.kt:283 */
                    "message" => {
                        /* JsonParserGenerator.kt:293 */
                        builder = builder.set_message(
                            /* JsonParserGenerator.kt:377 */
                            ::aws_smithy_json::deserialize::token::expect_string_or_null(
                                tokens.next(),
                            )?
                            .map(|s|
                                /* JsonParserGenerator.kt:362 */s.to_unescaped().map(|u|
                                    /* JsonParserGenerator.kt:371 */u.into_owned()
                                /* JsonParserGenerator.kt:362 */) /* JsonParserGenerator.kt:377 */)
                            .transpose()?, /* JsonParserGenerator.kt:293 */
                        );
                        /* JsonParserGenerator.kt:283 */
                    }
                    /* JsonParserGenerator.kt:311 */
                    _ => ::aws_smithy_json::deserialize::token::skip_value(tokens)?, /* JsonParserGenerator.kt:281 */
                }
                /* JsonParserGenerator.kt:755 */
            }
            /* JsonParserGenerator.kt:764 */
            other => {
                return Err(
                    ::aws_smithy_json::deserialize::error::DeserializeError::custom(format!(
                        "expected object key or end object, found: {other:?}"
                    )),
                )
            } /* JsonParserGenerator.kt:754 */
        }
        /* JsonParserGenerator.kt:753 */
    }
    /* JsonParserGenerator.kt:271 */
    if tokens.next().is_some() {
        /* JsonParserGenerator.kt:272 */
        return Err(
            ::aws_smithy_json::deserialize::error::DeserializeError::custom(
                "found more JSON tokens after completing parsing",
            ),
        );
        /* JsonParserGenerator.kt:271 */
    }
    /* JsonParserGenerator.kt:182 */
    Ok(builder)
    /* JsonParserGenerator.kt:163 */
}
