// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
/* JsonSerializerGenerator.kt:215 */
pub fn ser_get_storage_output_output_output(
    value: &crate::output::GetStorageOutput,
) -> ::std::result::Result<String, ::aws_smithy_types::error::operation::SerializationError> {
    /* JsonSerializerGenerator.kt:220 */
    let mut out = ::std::string::String::new();
    let mut object = ::aws_smithy_json::serialize::JsonObjectWriter::new(&mut out);
    /* JsonSerializerGenerator.kt:377 */
    crate::protocol_rest_json1::protocol_serde::shape_get_storage_output::ser_get_storage_output_output(&mut object, value)?;
    /* JsonSerializerGenerator.kt:229 */
    object.finish();
    Ok(out)
    /* JsonSerializerGenerator.kt:215 */
}

/* JsonSerializerGenerator.kt:360 */
pub fn ser_get_storage_output_output(
    object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
    input: &crate::output::GetStorageOutput,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    /* SerializerUtil.kt:42 */
    {
        /* JsonSerializerGenerator.kt:496 */
        let mut array_1 = object.key("collection").start_array();
        /* JsonSerializerGenerator.kt:536 */
        for item_2 in &input.collection {
            /* SerializerUtil.kt:42 */
            {
                /* JsonSerializerGenerator.kt:425 */
                array_1.value().string(item_2.as_str());
                /* SerializerUtil.kt:42 */
            }
            /* JsonSerializerGenerator.kt:536 */
        }
        /* JsonSerializerGenerator.kt:498 */
        array_1.finish();
        /* SerializerUtil.kt:42 */
    }
    /* JsonSerializerGenerator.kt:374 */
    Ok(())
    /* JsonSerializerGenerator.kt:360 */
}
