// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
/* JsonSerializerGenerator.kt:215 */
pub fn ser_invalid_pokeball_error_error(
    value: &crate::error::InvalidPokeballError,
) -> ::std::result::Result<String, ::aws_smithy_types::error::operation::SerializationError> {
    /* JsonSerializerGenerator.kt:220 */
    let mut out = ::std::string::String::new();
    let mut object = ::aws_smithy_json::serialize::JsonObjectWriter::new(&mut out);
    /* JsonSerializerGenerator.kt:377 */
    crate::protocol_rest_json1::protocol_serde::shape_invalid_pokeball_error::ser_invalid_pokeball_error(&mut object, value)?;
    /* JsonSerializerGenerator.kt:229 */
    object.finish();
    Ok(out)
    /* JsonSerializerGenerator.kt:215 */
}

/* JsonSerializerGenerator.kt:360 */
pub fn ser_invalid_pokeball_error(
    object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
    input: &crate::error::InvalidPokeballError,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    /* SerializerUtil.kt:42 */
    {
        /* JsonSerializerGenerator.kt:425 */
        object.key("pokeball").string(input.pokeball.as_str());
        /* SerializerUtil.kt:42 */
    }
    /* JsonSerializerGenerator.kt:374 */
    Ok(())
    /* JsonSerializerGenerator.kt:360 */
}
