// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
/* RustType.kt:534 */
#[allow(clippy::unnecessary_wraps)]
/* ServerHttpBoundProtocolGenerator.kt:506 */
pub async fn de_get_pokemon_species_http_request<B>(
    #[allow(unused_variables)] request: ::http_1x::Request<B>,
) -> std::result::Result<
    crate::input::GetPokemonSpeciesInput,
    ::aws_smithy_http_server::protocol::rest_xml::rejection::RequestRejection,
>
where
    B: ::aws_smithy_http_server::body::HttpBody + Send,
    B::Data: Send,
    ::aws_smithy_http_server::protocol::rest_xml::rejection::RequestRejection:
        From<<B as ::aws_smithy_http_server::body::HttpBody>::Error>,
{
    /* ServerHttpBoundProtocolGenerator.kt:522 */
    Ok({
        /* RustType.kt:534 */
        #[allow(unused_mut)]
        /* ServerHttpBoundProtocolGenerator.kt:867 */
        let mut input = crate::input::get_pokemon_species_input::Builder::default();
        /* RustType.kt:534 */
        #[allow(unused_variables)]
        /* ServerHttpBoundProtocolGenerator.kt:872 */
        let ::aws_smithy_runtime_api::http::RequestParts {
            uri, headers, body, ..
        } = ::aws_smithy_runtime_api::http::Request::try_from(request)?.into_parts();
        /* ServerHttpBoundProtocolGenerator.kt:1301 */
        let input_string = uri.path();
        /* ServerHttpBoundProtocolGenerator.kt:1313 */
        let (input_string, (_, m1)) =
            ::nom::sequence::tuple::<_, _, ::nom::error::Error<&str>, _>((
                ::nom::sequence::preceded(
                    ::nom::bytes::complete::tag("/"),
                    ::nom::bytes::complete::tag::<_, _, ::nom::error::Error<&str>>(
                        "pokemon-species",
                    ),
                ),
                ::nom::sequence::preceded(
                    ::nom::bytes::complete::tag("/"),
                    ::nom::branch::alt::<_, _, ::nom::error::Error<&str>, _>((
                        ::nom::bytes::complete::take_until("/"),
                        ::nom::combinator::rest,
                    )),
                ),
            ))(input_string)?;
        debug_assert_eq!("", input_string);
        /* ServerHttpBoundProtocolGenerator.kt:1324 */
        input = input.set_name(
            crate::protocol_rest_xml::protocol_serde::shape_get_pokemon_species_input::de_name(m1)?,
        );
        /* ServerHttpBoundProtocolGenerator.kt:1028 */
        input.build()?
        /* ServerHttpBoundProtocolGenerator.kt:522 */
    })
    /* ServerHttpBoundProtocolGenerator.kt:506 */
}

/* RustType.kt:534 */
#[allow(clippy::unnecessary_wraps)]
/* ServerHttpBoundProtocolGenerator.kt:543 */
pub fn ser_get_pokemon_species_http_response(
    #[allow(unused_variables)] output: crate::output::GetPokemonSpeciesOutput,
) -> std::result::Result<
    ::aws_smithy_http_server::response::Response,
    ::aws_smithy_http_server::protocol::rest_xml::rejection::ResponseRejection,
> {
    /* ServerHttpBoundProtocolGenerator.kt:555 */
    Ok({
        /* RustType.kt:534 */
        #[allow(unused_mut)]
        /* ServerHttpBoundProtocolGenerator.kt:645 */
        let mut builder = ::http_1x::Response::builder();
        /* ServerHttpBoundProtocolGenerator.kt:741 */
        builder = ::aws_smithy_http::header::set_response_header_if_absent(
            builder,
            ::http_1x::header::CONTENT_TYPE,
            "application/xml",
        );
        /* ServerHttpBoundProtocolGenerator.kt:826 */
        let http_status: u16 = 200;
        builder = builder.status(http_status);
        /* ServerHttpBoundProtocolGenerator.kt:705 */
        let payload =
            /* HttpBoundProtocolPayloadGenerator.kt:244 */crate::protocol_rest_xml::protocol_serde::shape_get_pokemon_species::ser_get_pokemon_species_output(&output)?
        /* ServerHttpBoundProtocolGenerator.kt:705 */;
        /* ServerHttpBoundProtocolGenerator.kt:807 */
        let content_length = payload.len();
        builder = ::aws_smithy_http::header::set_response_header_if_absent(
            builder,
            ::http_1x::header::CONTENT_LENGTH,
            content_length,
        );
        /* ServerHttpBoundProtocolGenerator.kt:711 */
        let body = ::aws_smithy_http_server::body::to_boxed(payload);
        /* ServerHttpBoundProtocolGenerator.kt:719 */
        builder.body(body)?
        /* ServerHttpBoundProtocolGenerator.kt:555 */
    })
    /* ServerHttpBoundProtocolGenerator.kt:543 */
}

/* RustType.kt:534 */
#[allow(clippy::unnecessary_wraps)]
/* ServerHttpBoundProtocolGenerator.kt:569 */
pub fn ser_get_pokemon_species_http_error(
    error: &crate::error::GetPokemonSpeciesError,
) -> std::result::Result<
    ::aws_smithy_http_server::response::Response,
    ::aws_smithy_http_server::protocol::rest_xml::rejection::ResponseRejection,
> {
    /* ServerHttpBoundProtocolGenerator.kt:574 */
    Ok({
        /* ServerHttpBoundProtocolGenerator.kt:590 */
        match error {
            /* ServerHttpBoundProtocolGenerator.kt:598 */
            crate::error::GetPokemonSpeciesError::ResourceNotFoundException(output) => {
                /* ServerHttpBoundProtocolGenerator.kt:599 */
                let payload = crate::protocol_rest_xml::protocol_serde::shape_resource_not_found_exception::ser_resource_not_found_exception_error(output)?;
                /* RustType.kt:534 */
                #[allow(unused_mut)]
                /* ServerHttpBoundProtocolGenerator.kt:609 */
                let mut builder = ::http_1x::Response::builder();
                /* ServerHttpBoundProtocolGenerator.kt:741 */
                builder = ::aws_smithy_http::header::set_response_header_if_absent(
                    builder,
                    ::http_1x::header::CONTENT_TYPE,
                    "application/xml",
                );
                /* ServerHttpBoundProtocolGenerator.kt:807 */
                let content_length = payload.len();
                builder = ::aws_smithy_http::header::set_response_header_if_absent(
                    builder,
                    ::http_1x::header::CONTENT_LENGTH,
                    content_length,
                );
                /* ServerHttpBoundProtocolGenerator.kt:626 */
                builder
                    .status(404)
                    .body(::aws_smithy_http_server::body::to_boxed(payload))?
                /* ServerHttpBoundProtocolGenerator.kt:598 */
            }
            /* ServerHttpBoundProtocolGenerator.kt:598 */
            crate::error::GetPokemonSpeciesError::ValidationException(output) => {
                /* ServerHttpBoundProtocolGenerator.kt:599 */
                let payload = crate::protocol_rest_xml::protocol_serde::shape_validation_exception::ser_validation_exception_error(output)?;
                /* RustType.kt:534 */
                #[allow(unused_mut)]
                /* ServerHttpBoundProtocolGenerator.kt:609 */
                let mut builder = ::http_1x::Response::builder();
                /* ServerHttpBoundProtocolGenerator.kt:741 */
                builder = ::aws_smithy_http::header::set_response_header_if_absent(
                    builder,
                    ::http_1x::header::CONTENT_TYPE,
                    "application/xml",
                );
                /* ServerHttpBoundProtocolGenerator.kt:807 */
                let content_length = payload.len();
                builder = ::aws_smithy_http::header::set_response_header_if_absent(
                    builder,
                    ::http_1x::header::CONTENT_LENGTH,
                    content_length,
                );
                /* ServerHttpBoundProtocolGenerator.kt:626 */
                builder
                    .status(400)
                    .body(::aws_smithy_http_server::body::to_boxed(payload))?
                /* ServerHttpBoundProtocolGenerator.kt:598 */
            } /* ServerHttpBoundProtocolGenerator.kt:590 */
        }
        /* ServerHttpBoundProtocolGenerator.kt:574 */
    })
    /* ServerHttpBoundProtocolGenerator.kt:569 */
}

/* XmlBindingTraitSerializerGenerator.kt:234 */
pub fn ser_get_pokemon_species_output(
    output: &crate::output::GetPokemonSpeciesOutput,
) -> ::std::result::Result<String, ::aws_smithy_types::error::operation::SerializationError> {
    /* XmlBindingTraitSerializerGenerator.kt:239 */
    let mut out = String::new();
    /* XmlBindingTraitSerializerGenerator.kt:243 */
    {
        /* XmlBindingTraitSerializerGenerator.kt:244 */
        let mut writer = ::aws_smithy_xml::encode::XmlWriter::new(&mut out);
        #[allow(unused_mut)]
        let mut root = writer.start_el("GetPokemonSpeciesOutput");
        /* XmlBindingTraitSerializerGenerator.kt:480 */
        crate::protocol_rest_xml::protocol_serde::shape_get_pokemon_species_output::ser_get_pokemon_species_output_output(output, root)?
        /* XmlBindingTraitSerializerGenerator.kt:243 */
    }
    /* XmlBindingTraitSerializerGenerator.kt:256 */
    Ok(out)
    /* XmlBindingTraitSerializerGenerator.kt:234 */
}
