// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
/* XmlBindingTraitSerializerGenerator.kt:467 */
pub fn ser_validation_exception_field(
    input: &crate::model::ValidationExceptionField,
    writer: ::aws_smithy_xml::encode::ElWriter,
) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    /* RustType.kt:534 */
    #[allow(unused_mut)]
    /* XmlBindingTraitSerializerGenerator.kt:320 */
    let mut scope = writer.finish();
    /* SerializerUtil.kt:42 */
    {
        /* XmlBindingTraitSerializerGenerator.kt:395 */
        let mut inner_writer = scope.start_el("path").finish();
        /* XmlBindingTraitSerializerGenerator.kt:398 */
        inner_writer.data(
            /* XmlBindingTraitSerializerGenerator.kt:343 */
            input.path.as_str(), /* XmlBindingTraitSerializerGenerator.kt:398 */
        );
        /* SerializerUtil.kt:42 */
    }
    /* SerializerUtil.kt:42 */
    {
        /* XmlBindingTraitSerializerGenerator.kt:395 */
        let mut inner_writer = scope.start_el("message").finish();
        /* XmlBindingTraitSerializerGenerator.kt:398 */
        inner_writer.data(
            /* XmlBindingTraitSerializerGenerator.kt:343 */
            input.message.as_str(), /* XmlBindingTraitSerializerGenerator.kt:398 */
        );
        /* SerializerUtil.kt:42 */
    }
    /* XmlBindingTraitSerializerGenerator.kt:325 */
    scope.finish();
    /* XmlBindingTraitSerializerGenerator.kt:477 */
    Ok(())
    /* XmlBindingTraitSerializerGenerator.kt:467 */
}
