// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
/* HttpBindingGenerator.kt:236 */
pub fn de_events_payload(
    body: &mut ::aws_smithy_types::body::SdkBody,
) -> std::result::Result<
    ::aws_smithy_http::event_stream::Receiver<
        crate::model::AttemptCapturingPokemonEvent,
        crate::error::AttemptCapturingPokemonEventError,
    >,
    ::aws_smithy_xml::decode::XmlDecodeError,
> {
    /* HttpBindingGenerator.kt:278 */
    let unmarshaller =
        crate::protocol_rest_xml::event_stream_serde::AttemptCapturingPokemonEventUnmarshaller::new(
        );
    /* HttpBindingGenerator.kt:296 */
    let body = std::mem::replace(body, ::aws_smithy_types::body::SdkBody::taken());
    let receiver = ::aws_smithy_http::event_stream::Receiver::new(unmarshaller, body);
    Ok(receiver)
    /* HttpBindingGenerator.kt:236 */
}

/* ServerHttpBoundProtocolGenerator.kt:1620 */
pub fn de_region(
    value: &str,
) -> std::result::Result<
    ::std::string::String,
    ::aws_smithy_http_server::protocol::rest_xml::rejection::RequestRejection,
> {
    /* ServerHttpBoundProtocolGenerator.kt:1630 */
    let value = ::percent_encoding::percent_decode_str(value)
        .decode_utf8()?
        .into_owned();
    /* ServerHttpBoundProtocolGenerator.kt:1692 */
    Ok(value)
    /* ServerHttpBoundProtocolGenerator.kt:1620 */
}
