#!/usr/bin/env python3
import os
import sys

expected = [os.path.realpath("/tmp"), ["show", "-s", "test_revision", "--format=%H"]]
actual = [os.getcwd(), sys.argv[1:]]
if expected != actual:
    print(f"ERROR\nExpect: {expected}\nActual: {actual}")
    sys.exit(1)

print("success")
