#!/bin/bash
#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Run by CI to check the canary-lambda
set -e
cd "$(dirname "$0")"

SDK_PATH="$(git rev-parse --show-toplevel)"/aws/sdk/build/aws-sdk/sdk
if [[ "${GITHUB_ACTIONS}" == "true" ]]; then
   SDK_PATH="$(git rev-parse --show-toplevel)"/aws-sdk/sdk
fi

# The canary-lambda doesn't have a Cargo.toml in a fresh checkout of smithy-rs, so generate one before checks
pushd ../canary-runner
cargo run -- build-bundle --manifest-only --canary-path ../canary-lambda --sdk-path "${SDK_PATH}"
popd

cargo test --all-features
cargo clippy --all-features
