[package]
name = "cargo-api-linter"
version = "0.1.0"
authors = ["AWS Rust SDK Team <aws-sdk-rust@amazon.com>", "John DiSanti <jdisanti@amazon.com>"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/awslabs/smithy-rs"
publish = false

[dependencies]
anyhow = "1"
cargo_metadata = "0.14"
clap = { version = "~3.1.18", features = ["derive"] }
owo-colors = { version = "3", features = ["supports-colors"] }
pest = "2" # For pretty error formatting
rustdoc-types = "0.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
smithy-rs-tool-common = { version = "0.1", path = "../smithy-rs-tool-common" }
toml = "0.5"
tracing = "0.1"
tracing-attributes = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
wildmatch = "2"

[dev-dependencies]
pretty_assertions = "1.1"
test_bin = "0.4"
