#!/usr/bin/env python3
import os
import sys

expected = ["/tmp", ["rev-list", "end_exclusive..start_inclusive"]]
actual = [os.getcwd(), sys.argv[1:]]
if expected != actual:
    print(f"ERROR\nExpect: {expected}\nActual: {actual}")
    sys.exit(1)

print("second-commit")
print("initial-commit")
