#!/usr/bin/env python3
import os
import sys

expected = ["/tmp", ["rev-parse", "HEAD"]]
actual = [os.getcwd(), sys.argv[1:]]
if expected != actual:
    print(f"ERROR\nExpect: {expected}\nActual: {actual}")
    sys.exit(1)

print("some-commit-hash")
