#!/usr/bin/env python3
import os
import sys

expected = ["/tmp", ["merge", "--ff-only", "test-branch-name"]]
actual = [os.getcwd(), sys.argv[1:]]
if expected != actual:
    print(f"ERROR\nExpect: {expected}\nActual: {actual}")
    sys.exit(1)
