#!/usr/bin/env python3
import os
import sys

expected = ["/tmp", ["ls-files", "--exclude-standard", "--others"]]
actual = [os.getcwd(), sys.argv[1:]]
if expected != actual:
    print(f"ERROR\nExpect: {expected}\nActual: {actual}")
    sys.exit(127)

# print untracked files
print("some-untracked-file")
print("another-untracked-file")
