#!/usr/bin/env python3
import os
import sys

expected = [os.path.realpath("/tmp"), [
    "-c", "user.name=Bot Name",
    "-c", "user.email=bot@example.com",
    "commit", "-m", "Test message",
    "--author", "Some Author <author@example.com>"
]]
actual = [os.getcwd(), sys.argv[1:]]
if expected != actual:
    print(f"ERROR\nExpect: {expected}\nActual: {actual}")
    sys.exit(1)
