#!/usr/bin/env python3
import os
import sys

if sys.argv[1] == "merge":
    expected = [os.path.realpath("/tmp"), ["merge", "--squash", "test-branch-name"]]
    actual = [os.getcwd(), sys.argv[1:]]
    if expected != actual:
        print(f"ERROR\nExpect: {expected}\nActual: {actual}")
        sys.exit(1)
else:
    expected = [
        os.path.realpath("/tmp"),
        ["-c", "user.name=test-author", "-c", "user.email=test-author-email", "commit", "-m", "test message"]
    ]
    actual = [os.getcwd(), sys.argv[1:]]
    if expected != actual:
        print(f"ERROR\nExpect: {expected}\nActual: {actual}")
        sys.exit(1)
