// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#![allow(dead_code)]
static CHECK_HEALTH_OUTPUT_SCHEMA: ::aws_smithy_schema::Schema<'static> = ::aws_smithy_schema::Schema::new_struct(
                            ::aws_smithy_schema::ShapeId::from_parts("com.aws.example.synthetic#CheckHealthOutput", "com.aws.example.synthetic", "CheckHealthOutput"),
                            ::aws_smithy_schema::ShapeType::Structure,
                            &[],
                        );
pub(crate) const CHECK_HEALTH_OUTPUT: &'static ::aws_smithy_schema::Schema<'static> =
                        &CHECK_HEALTH_OUTPUT_SCHEMA;

