// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_flavor_text(input: &crate::model::FlavorText, writer: ::aws_smithy_xml::encode::ElWriter) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    #[allow(unused_mut)]
    let mut scope = writer.finish();
     {
        let mut inner_writer = scope.start_el("flavorText").finish();
        inner_writer.data(
            input.flavor_text.as_str()
        );
    }
     {
        let mut inner_writer = scope.start_el("language").finish();
        inner_writer.data(
            input.language.as_str()
        );
    }
    scope.finish();
    Ok(())
}

