// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_unsupported_region_error_error(error: &crate::error::UnsupportedRegionError) -> ::std::result::Result<String, ::aws_smithy_types::error::operation::SerializationError> {
    let mut out = String::new();
     {
        let mut writer = ::aws_smithy_xml::encode::XmlWriter::new(&mut out);
                                #[allow(unused_mut)]
                                let mut root = writer.start_el("Error");
        crate::protocol_serde::shape_unsupported_region_error::ser_unsupported_region_error(error, root)?
    }
    Ok(out)
}

pub fn ser_unsupported_region_error(input: &crate::error::UnsupportedRegionError, writer: ::aws_smithy_xml::encode::ElWriter) -> ::std::result::Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    #[allow(unused_mut)]
    let mut scope = writer.finish();
     {
        let mut inner_writer = scope.start_el("region").finish();
        inner_writer.data(
            input.region.as_str()
        );
    }
    scope.finish();
    Ok(())
}

