// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
/* ServerHttpBoundProtocolGenerator.kt:335 */
impl<B>
    ::aws_smithy_http_server::request::FromRequest<
        ::aws_smithy_http_server::protocol::aws_json_10::AwsJson1_0,
        B,
    > for crate::input::GetServerStatisticsInput
where
    B: ::aws_smithy_http_server::body::HttpBody + Send,
    B: 'static,

    B::Data: Send,
    ::aws_smithy_http_server::protocol::aws_json::rejection::RequestRejection:
        From<<B as ::aws_smithy_http_server::body::HttpBody>::Error>,
{
    type Rejection = ::aws_smithy_http_server::protocol::aws_json::runtime_error::RuntimeError;
    type Future = crate::operation::GetServerStatisticsInputFuture<
        ::aws_smithy_http_server::protocol::aws_json_10::AwsJson1_0,
    >;

    fn from_request(request: ::http_1x::Request<B>) -> Self::Future {
        let fut = async move {
            if !::aws_smithy_http_server::protocol::accept_header_classifier(
                request.headers(),
                &crate::mimes::CONTENT_TYPE_APPLICATION_X_AMZ_JSON_1_0,
            ) {
                return Err(::aws_smithy_http_server::protocol::aws_json::rejection::RequestRejection::NotAcceptable);
            }
            crate::protocol_aws_json1_0::protocol_serde::shape_get_server_statistics::de_get_server_statistics_http_request(request)
                                .await
        };
        use ::futures_util::future::TryFutureExt;
        let fut = fut.map_err(
            |e: ::aws_smithy_http_server::protocol::aws_json::rejection::RequestRejection| {
                ::tracing::debug!(error = %e, "failed to deserialize request");
                ::aws_smithy_http_server::protocol::aws_json::runtime_error::RuntimeError::from(e)
            },
        );
        crate::operation::GetServerStatisticsInputFuture {
            inner: Box::pin(fut),
        }
    }
}
/* ServerHttpBoundProtocolGenerator.kt:433 */
impl
    ::aws_smithy_http_server::response::IntoResponse<
        ::aws_smithy_http_server::protocol::aws_json_10::AwsJson1_0,
    > for crate::output::GetServerStatisticsOutput
{
    fn into_response(self) -> ::aws_smithy_http_server::response::Response {
        match crate::protocol_aws_json1_0::protocol_serde::shape_get_server_statistics::ser_get_server_statistics_http_response(self) {
                        Ok(response) => response,
                        Err(e) => {
                            ::tracing::error!(error = %e, "failed to serialize response");
                            ::aws_smithy_http_server::response::IntoResponse::<::aws_smithy_http_server::protocol::aws_json_10::AwsJson1_0>::into_response(::aws_smithy_http_server::protocol::aws_json::runtime_error::RuntimeError::from(e))
                        }
                    }
    }
}

/* ServerHttpBoundProtocolGenerator.kt:335 */
impl<B>
    ::aws_smithy_http_server::request::FromRequest<
        ::aws_smithy_http_server::protocol::aws_json_10::AwsJson1_0,
        B,
    > for crate::input::DoNothingInput
where
    B: ::aws_smithy_http_server::body::HttpBody + Send,
    B: 'static,

    B::Data: Send,
    ::aws_smithy_http_server::protocol::aws_json::rejection::RequestRejection:
        From<<B as ::aws_smithy_http_server::body::HttpBody>::Error>,
{
    type Rejection = ::aws_smithy_http_server::protocol::aws_json::runtime_error::RuntimeError;
    type Future = crate::operation::DoNothingInputFuture<
        ::aws_smithy_http_server::protocol::aws_json_10::AwsJson1_0,
    >;

    fn from_request(request: ::http_1x::Request<B>) -> Self::Future {
        let fut = async move {
            if !::aws_smithy_http_server::protocol::accept_header_classifier(
                request.headers(),
                &crate::mimes::CONTENT_TYPE_APPLICATION_X_AMZ_JSON_1_0,
            ) {
                return Err(::aws_smithy_http_server::protocol::aws_json::rejection::RequestRejection::NotAcceptable);
            }
            crate::protocol_aws_json1_0::protocol_serde::shape_do_nothing::de_do_nothing_http_request(request)
                                .await
        };
        use ::futures_util::future::TryFutureExt;
        let fut = fut.map_err(
            |e: ::aws_smithy_http_server::protocol::aws_json::rejection::RequestRejection| {
                ::tracing::debug!(error = %e, "failed to deserialize request");
                ::aws_smithy_http_server::protocol::aws_json::runtime_error::RuntimeError::from(e)
            },
        );
        crate::operation::DoNothingInputFuture {
            inner: Box::pin(fut),
        }
    }
}
/* ServerHttpBoundProtocolGenerator.kt:433 */
impl
    ::aws_smithy_http_server::response::IntoResponse<
        ::aws_smithy_http_server::protocol::aws_json_10::AwsJson1_0,
    > for crate::output::DoNothingOutput
{
    fn into_response(self) -> ::aws_smithy_http_server::response::Response {
        match crate::protocol_aws_json1_0::protocol_serde::shape_do_nothing::ser_do_nothing_http_response(self) {
                        Ok(response) => response,
                        Err(e) => {
                            ::tracing::error!(error = %e, "failed to serialize response");
                            ::aws_smithy_http_server::response::IntoResponse::<::aws_smithy_http_server::protocol::aws_json_10::AwsJson1_0>::into_response(::aws_smithy_http_server::protocol::aws_json::runtime_error::RuntimeError::from(e))
                        }
                    }
    }
}

/* ServerHttpBoundProtocolGenerator.kt:335 */
impl<B>
    ::aws_smithy_http_server::request::FromRequest<
        ::aws_smithy_http_server::protocol::aws_json_10::AwsJson1_0,
        B,
    > for crate::input::CheckHealthInput
where
    B: ::aws_smithy_http_server::body::HttpBody + Send,
    B: 'static,

    B::Data: Send,
    ::aws_smithy_http_server::protocol::aws_json::rejection::RequestRejection:
        From<<B as ::aws_smithy_http_server::body::HttpBody>::Error>,
{
    type Rejection = ::aws_smithy_http_server::protocol::aws_json::runtime_error::RuntimeError;
    type Future = crate::operation::CheckHealthInputFuture<
        ::aws_smithy_http_server::protocol::aws_json_10::AwsJson1_0,
    >;

    fn from_request(request: ::http_1x::Request<B>) -> Self::Future {
        let fut = async move {
            if !::aws_smithy_http_server::protocol::accept_header_classifier(
                request.headers(),
                &crate::mimes::CONTENT_TYPE_APPLICATION_X_AMZ_JSON_1_0,
            ) {
                return Err(::aws_smithy_http_server::protocol::aws_json::rejection::RequestRejection::NotAcceptable);
            }
            crate::protocol_aws_json1_0::protocol_serde::shape_check_health::de_check_health_http_request(request)
                                .await
        };
        use ::futures_util::future::TryFutureExt;
        let fut = fut.map_err(
            |e: ::aws_smithy_http_server::protocol::aws_json::rejection::RequestRejection| {
                ::tracing::debug!(error = %e, "failed to deserialize request");
                ::aws_smithy_http_server::protocol::aws_json::runtime_error::RuntimeError::from(e)
            },
        );
        crate::operation::CheckHealthInputFuture {
            inner: Box::pin(fut),
        }
    }
}
/* ServerHttpBoundProtocolGenerator.kt:433 */
impl
    ::aws_smithy_http_server::response::IntoResponse<
        ::aws_smithy_http_server::protocol::aws_json_10::AwsJson1_0,
    > for crate::output::CheckHealthOutput
{
    fn into_response(self) -> ::aws_smithy_http_server::response::Response {
        match crate::protocol_aws_json1_0::protocol_serde::shape_check_health::ser_check_health_http_response(self) {
                        Ok(response) => response,
                        Err(e) => {
                            ::tracing::error!(error = %e, "failed to serialize response");
                            ::aws_smithy_http_server::response::IntoResponse::<::aws_smithy_http_server::protocol::aws_json_10::AwsJson1_0>::into_response(::aws_smithy_http_server::protocol::aws_json::runtime_error::RuntimeError::from(e))
                        }
                    }
    }
}

/* ServerHttpBoundProtocolGenerator.kt:335 */
impl<B>
    ::aws_smithy_http_server::request::FromRequest<
        ::aws_smithy_http_server::protocol::aws_json_10::AwsJson1_0,
        B,
    > for crate::input::StreamPokemonRadioInput
where
    B: ::aws_smithy_http_server::body::HttpBody + Send,
    B: 'static,

    B::Data: Send,
    ::aws_smithy_http_server::protocol::aws_json::rejection::RequestRejection:
        From<<B as ::aws_smithy_http_server::body::HttpBody>::Error>,
{
    type Rejection = ::aws_smithy_http_server::protocol::aws_json::runtime_error::RuntimeError;
    type Future = crate::operation::StreamPokemonRadioInputFuture<
        ::aws_smithy_http_server::protocol::aws_json_10::AwsJson1_0,
    >;

    fn from_request(request: ::http_1x::Request<B>) -> Self::Future {
        let fut = async move {
            if !::aws_smithy_http_server::protocol::accept_header_classifier(
                request.headers(),
                &crate::mimes::CONTENT_TYPE_APPLICATION_X_AMZ_JSON_1_0,
            ) {
                return Err(::aws_smithy_http_server::protocol::aws_json::rejection::RequestRejection::NotAcceptable);
            }
            crate::protocol_aws_json1_0::protocol_serde::shape_stream_pokemon_radio::de_stream_pokemon_radio_http_request(request)
                                .await
        };
        use ::futures_util::future::TryFutureExt;
        let fut = fut.map_err(
            |e: ::aws_smithy_http_server::protocol::aws_json::rejection::RequestRejection| {
                ::tracing::debug!(error = %e, "failed to deserialize request");
                ::aws_smithy_http_server::protocol::aws_json::runtime_error::RuntimeError::from(e)
            },
        );
        crate::operation::StreamPokemonRadioInputFuture {
            inner: Box::pin(fut),
        }
    }
}
/* ServerHttpBoundProtocolGenerator.kt:433 */
impl
    ::aws_smithy_http_server::response::IntoResponse<
        ::aws_smithy_http_server::protocol::aws_json_10::AwsJson1_0,
    > for crate::output::StreamPokemonRadioOutput
{
    fn into_response(self) -> ::aws_smithy_http_server::response::Response {
        match crate::protocol_aws_json1_0::protocol_serde::shape_stream_pokemon_radio::ser_stream_pokemon_radio_http_response(self) {
                        Ok(response) => response,
                        Err(e) => {
                            ::tracing::error!(error = %e, "failed to serialize response");
                            ::aws_smithy_http_server::response::IntoResponse::<::aws_smithy_http_server::protocol::aws_json_10::AwsJson1_0>::into_response(::aws_smithy_http_server::protocol::aws_json::runtime_error::RuntimeError::from(e))
                        }
                    }
    }
}

/* ServerHttpBoundProtocolGenerator.kt:335 */
impl<B>
    ::aws_smithy_http_server::request::FromRequest<
        ::aws_smithy_http_server::protocol::aws_json_10::AwsJson1_0,
        B,
    > for crate::input::GetPokemonSpeciesInput
where
    B: ::aws_smithy_http_server::body::HttpBody + Send,
    B: 'static,

    B::Data: Send,
    ::aws_smithy_http_server::protocol::aws_json::rejection::RequestRejection:
        From<<B as ::aws_smithy_http_server::body::HttpBody>::Error>,
{
    type Rejection = ::aws_smithy_http_server::protocol::aws_json::runtime_error::RuntimeError;
    type Future = crate::operation::GetPokemonSpeciesInputFuture<
        ::aws_smithy_http_server::protocol::aws_json_10::AwsJson1_0,
    >;

    fn from_request(request: ::http_1x::Request<B>) -> Self::Future {
        let fut = async move {
            if !::aws_smithy_http_server::protocol::accept_header_classifier(
                request.headers(),
                &crate::mimes::CONTENT_TYPE_APPLICATION_X_AMZ_JSON_1_0,
            ) {
                return Err(::aws_smithy_http_server::protocol::aws_json::rejection::RequestRejection::NotAcceptable);
            }
            crate::protocol_aws_json1_0::protocol_serde::shape_get_pokemon_species::de_get_pokemon_species_http_request(request)
                                .await
        };
        use ::futures_util::future::TryFutureExt;
        let fut = fut.map_err(
            |e: ::aws_smithy_http_server::protocol::aws_json::rejection::RequestRejection| {
                ::tracing::debug!(error = %e, "failed to deserialize request");
                ::aws_smithy_http_server::protocol::aws_json::runtime_error::RuntimeError::from(e)
            },
        );
        crate::operation::GetPokemonSpeciesInputFuture {
            inner: Box::pin(fut),
        }
    }
}
/* ServerHttpBoundProtocolGenerator.kt:433 */
impl
    ::aws_smithy_http_server::response::IntoResponse<
        ::aws_smithy_http_server::protocol::aws_json_10::AwsJson1_0,
    > for crate::output::GetPokemonSpeciesOutput
{
    fn into_response(self) -> ::aws_smithy_http_server::response::Response {
        match crate::protocol_aws_json1_0::protocol_serde::shape_get_pokemon_species::ser_get_pokemon_species_http_response(self) {
                        Ok(response) => response,
                        Err(e) => {
                            ::tracing::error!(error = %e, "failed to serialize response");
                            ::aws_smithy_http_server::response::IntoResponse::<::aws_smithy_http_server::protocol::aws_json_10::AwsJson1_0>::into_response(::aws_smithy_http_server::protocol::aws_json::runtime_error::RuntimeError::from(e))
                        }
                    }
    }
}
/* ServerHttpBoundProtocolGenerator.kt:454 */
impl
    ::aws_smithy_http_server::response::IntoResponse<
        ::aws_smithy_http_server::protocol::aws_json_10::AwsJson1_0,
    > for crate::error::GetPokemonSpeciesError
{
    fn into_response(self) -> ::aws_smithy_http_server::response::Response {
        match crate::protocol_aws_json1_0::protocol_serde::shape_get_pokemon_species::ser_get_pokemon_species_http_error(&self) {
            Ok(mut response) => {
                response.extensions_mut().insert(::aws_smithy_http_server::extension::ModeledErrorExtension::new(self.name()));
                response
            },
            Err(e) => {
                ::tracing::error!(error = %e, "failed to serialize response");
                ::aws_smithy_http_server::response::IntoResponse::<::aws_smithy_http_server::protocol::aws_json_10::AwsJson1_0>::into_response(::aws_smithy_http_server::protocol::aws_json::runtime_error::RuntimeError::from(e))
            }
        }
    }
}

/* ServerHttpBoundProtocolGenerator.kt:335 */
impl<B>
    ::aws_smithy_http_server::request::FromRequest<
        ::aws_smithy_http_server::protocol::aws_json_10::AwsJson1_0,
        B,
    > for crate::input::GetStorageInput
where
    B: ::aws_smithy_http_server::body::HttpBody + Send,
    B: 'static,

    B::Data: Send,
    ::aws_smithy_http_server::protocol::aws_json::rejection::RequestRejection:
        From<<B as ::aws_smithy_http_server::body::HttpBody>::Error>,
{
    type Rejection = ::aws_smithy_http_server::protocol::aws_json::runtime_error::RuntimeError;
    type Future = crate::operation::GetStorageInputFuture<
        ::aws_smithy_http_server::protocol::aws_json_10::AwsJson1_0,
    >;

    fn from_request(request: ::http_1x::Request<B>) -> Self::Future {
        let fut = async move {
            if !::aws_smithy_http_server::protocol::accept_header_classifier(
                request.headers(),
                &crate::mimes::CONTENT_TYPE_APPLICATION_X_AMZ_JSON_1_0,
            ) {
                return Err(::aws_smithy_http_server::protocol::aws_json::rejection::RequestRejection::NotAcceptable);
            }
            crate::protocol_aws_json1_0::protocol_serde::shape_get_storage::de_get_storage_http_request(request)
                                .await
        };
        use ::futures_util::future::TryFutureExt;
        let fut = fut.map_err(
            |e: ::aws_smithy_http_server::protocol::aws_json::rejection::RequestRejection| {
                ::tracing::debug!(error = %e, "failed to deserialize request");
                ::aws_smithy_http_server::protocol::aws_json::runtime_error::RuntimeError::from(e)
            },
        );
        crate::operation::GetStorageInputFuture {
            inner: Box::pin(fut),
        }
    }
}
/* ServerHttpBoundProtocolGenerator.kt:433 */
impl
    ::aws_smithy_http_server::response::IntoResponse<
        ::aws_smithy_http_server::protocol::aws_json_10::AwsJson1_0,
    > for crate::output::GetStorageOutput
{
    fn into_response(self) -> ::aws_smithy_http_server::response::Response {
        match crate::protocol_aws_json1_0::protocol_serde::shape_get_storage::ser_get_storage_http_response(self) {
                        Ok(response) => response,
                        Err(e) => {
                            ::tracing::error!(error = %e, "failed to serialize response");
                            ::aws_smithy_http_server::response::IntoResponse::<::aws_smithy_http_server::protocol::aws_json_10::AwsJson1_0>::into_response(::aws_smithy_http_server::protocol::aws_json::runtime_error::RuntimeError::from(e))
                        }
                    }
    }
}
/* ServerHttpBoundProtocolGenerator.kt:454 */
impl
    ::aws_smithy_http_server::response::IntoResponse<
        ::aws_smithy_http_server::protocol::aws_json_10::AwsJson1_0,
    > for crate::error::GetStorageError
{
    fn into_response(self) -> ::aws_smithy_http_server::response::Response {
        match crate::protocol_aws_json1_0::protocol_serde::shape_get_storage::ser_get_storage_http_error(&self) {
            Ok(mut response) => {
                response.extensions_mut().insert(::aws_smithy_http_server::extension::ModeledErrorExtension::new(self.name()));
                response
            },
            Err(e) => {
                ::tracing::error!(error = %e, "failed to serialize response");
                ::aws_smithy_http_server::response::IntoResponse::<::aws_smithy_http_server::protocol::aws_json_10::AwsJson1_0>::into_response(::aws_smithy_http_server::protocol::aws_json::runtime_error::RuntimeError::from(e))
            }
        }
    }
}
