// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
static UNIT_SCHEMA: ::aws_smithy_schema::Schema<'static> = ::aws_smithy_schema::Schema::new(
                ::aws_smithy_schema::ShapeId::from_parts("smithy.api#Unit", "smithy.api", "Unit"),
                ::aws_smithy_schema::ShapeType::Structure,
            );
static CAPTURE_POKEMON_OPERATION_SHAPE: ::aws_smithy_schema::Schema<'static> = ::aws_smithy_schema::Schema::new(
                ::aws_smithy_schema::ShapeId::from_parts("com.aws.example#CapturePokemon", "com.aws.example", "CapturePokemon"),
                ::aws_smithy_schema::ShapeType::Operation,
            );

            static CAPTURE_POKEMON_ERRORS: &[&::aws_smithy_schema::Schema<'static>] = &[
                crate::schema::error::shape_invalid_pokeball_error::INVALID_POKEBALL_ERROR,
crate::schema::error::shape_master_ball_unsuccessful::MASTER_BALL_UNSUCCESSFUL,
crate::schema::error::shape_throttling_error::THROTTLING_ERROR,
crate::schema::error::shape_unsupported_region_error::UNSUPPORTED_REGION_ERROR,
crate::schema::error::shape_validation_exception::VALIDATION_EXCEPTION
            ];

            pub(crate) static CAPTURE_POKEMON: ::aws_smithy_http_server::schema::OperationSchema<'static> = ::aws_smithy_http_server::schema::OperationSchema::new(
                &CAPTURE_POKEMON_OPERATION_SHAPE,
                crate::schema::input::shape_capture_pokemon_input::CAPTURE_POKEMON_INPUT,
                crate::schema::output::shape_capture_pokemon_output::CAPTURE_POKEMON_OUTPUT,
                CAPTURE_POKEMON_ERRORS,
            );
static CHECK_HEALTH_OPERATION_SHAPE: ::aws_smithy_schema::Schema<'static> = ::aws_smithy_schema::Schema::new(
                ::aws_smithy_schema::ShapeId::from_parts("com.aws.example#CheckHealth", "com.aws.example", "CheckHealth"),
                ::aws_smithy_schema::ShapeType::Operation,
            );

            static CHECK_HEALTH_ERRORS: &[&::aws_smithy_schema::Schema<'static>] = &[

            ];

            pub(crate) static CHECK_HEALTH: ::aws_smithy_http_server::schema::OperationSchema<'static> = ::aws_smithy_http_server::schema::OperationSchema::new(
                &CHECK_HEALTH_OPERATION_SHAPE,
                crate::schema::input::shape_check_health_input::CHECK_HEALTH_INPUT,
                crate::schema::output::shape_check_health_output::CHECK_HEALTH_OUTPUT,
                CHECK_HEALTH_ERRORS,
            );
static DO_NOTHING_OPERATION_SHAPE: ::aws_smithy_schema::Schema<'static> = ::aws_smithy_schema::Schema::new(
                ::aws_smithy_schema::ShapeId::from_parts("com.aws.example#DoNothing", "com.aws.example", "DoNothing"),
                ::aws_smithy_schema::ShapeType::Operation,
            );

            static DO_NOTHING_ERRORS: &[&::aws_smithy_schema::Schema<'static>] = &[

            ];

            pub(crate) static DO_NOTHING: ::aws_smithy_http_server::schema::OperationSchema<'static> = ::aws_smithy_http_server::schema::OperationSchema::new(
                &DO_NOTHING_OPERATION_SHAPE,
                crate::schema::input::shape_do_nothing_input::DO_NOTHING_INPUT,
                crate::schema::output::shape_do_nothing_output::DO_NOTHING_OUTPUT,
                DO_NOTHING_ERRORS,
            );
static GET_SERVER_STATISTICS_OPERATION_SHAPE: ::aws_smithy_schema::Schema<'static> = ::aws_smithy_schema::Schema::new(
                ::aws_smithy_schema::ShapeId::from_parts("com.aws.example#GetServerStatistics", "com.aws.example", "GetServerStatistics"),
                ::aws_smithy_schema::ShapeType::Operation,
            );

            static GET_SERVER_STATISTICS_ERRORS: &[&::aws_smithy_schema::Schema<'static>] = &[

            ];

            pub(crate) static GET_SERVER_STATISTICS: ::aws_smithy_http_server::schema::OperationSchema<'static> = ::aws_smithy_http_server::schema::OperationSchema::new(
                &GET_SERVER_STATISTICS_OPERATION_SHAPE,
                crate::schema::input::shape_get_server_statistics_input::GET_SERVER_STATISTICS_INPUT,
                crate::schema::output::shape_get_server_statistics_output::GET_SERVER_STATISTICS_OUTPUT,
                GET_SERVER_STATISTICS_ERRORS,
            );

