// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#![allow(dead_code)]
static GET_POKEMON_SPECIES_OUTPUT_MEMBER_NAME: ::aws_smithy_schema::Schema<'static> = ::aws_smithy_schema::Schema::new_member(
                            ::aws_smithy_schema::ShapeId::from_parts(
                                "com.aws.example.synthetic#GetPokemonSpeciesOutput$name",
                                "com.aws.example.synthetic",
                                "GetPokemonSpeciesOutput",
                            ),
                            ::aws_smithy_schema::ShapeType::String,
                            "name",
                            0,
                        );
static GET_POKEMON_SPECIES_OUTPUT_MEMBER_FLAVOR_TEXT_ENTRIES_MEMBER: ::aws_smithy_schema::Schema<'static> = ::aws_smithy_schema::Schema::new_member(
                        ::aws_smithy_schema::ShapeId::from_parts(
                            "com.aws.example#FlavorTextEntries$member",
                            "com.aws.example",
                            "FlavorTextEntries",
                        ),
                        ::aws_smithy_schema::ShapeType::Structure,
                        "member",
                        0,
                    );
static GET_POKEMON_SPECIES_OUTPUT_MEMBER_FLAVOR_TEXT_ENTRIES: ::aws_smithy_schema::Schema<'static> = ::aws_smithy_schema::Schema::new_member(
                            ::aws_smithy_schema::ShapeId::from_parts(
                                "com.aws.example.synthetic#GetPokemonSpeciesOutput$flavorTextEntries",
                                "com.aws.example.synthetic",
                                "GetPokemonSpeciesOutput",
                            ),
                            ::aws_smithy_schema::ShapeType::List,
                            "flavorTextEntries",
                            1,
                        )
    .with_list_member(&GET_POKEMON_SPECIES_OUTPUT_MEMBER_FLAVOR_TEXT_ENTRIES_MEMBER);
static GET_POKEMON_SPECIES_OUTPUT_SCHEMA: ::aws_smithy_schema::Schema<'static> = ::aws_smithy_schema::Schema::new_struct(
                            ::aws_smithy_schema::ShapeId::from_parts("com.aws.example.synthetic#GetPokemonSpeciesOutput", "com.aws.example.synthetic", "GetPokemonSpeciesOutput"),
                            ::aws_smithy_schema::ShapeType::Structure,
                            &[&GET_POKEMON_SPECIES_OUTPUT_MEMBER_NAME, &GET_POKEMON_SPECIES_OUTPUT_MEMBER_FLAVOR_TEXT_ENTRIES],
                        )
    .with_original_name("GetPokemonSpeciesOutput");
pub(crate) const GET_POKEMON_SPECIES_OUTPUT: &'static ::aws_smithy_schema::Schema<'static> =
                        &GET_POKEMON_SPECIES_OUTPUT_SCHEMA;

